// ======================= ZoneTool =======================
// zonetool, a fastfile linker for various
// Call of Duty titles. 
//
// Project: https://github.com/ZoneTool/gsc-asm
// Author: RektInator (https://github.com/RektInator)
// License: GNU GPL v3.0
// ========================================================
#define OP_SetNewLocalVariableFieldCached0		0x17
#define OP_EvalSelfFieldVariable				0x18
#define OP_Return								0x19
#define OP_CallBuiltin0							0x1A
#define OP_CallBuiltin1							0x1B
#define OP_CallBuiltin2							0x1C
#define OP_CallBuiltin3							0x1D
#define OP_CallBuiltin4							0x1E
#define OP_CallBuiltin5							0x1F
#define OP_CallBuiltin							0x20
#define OP_BoolNot								0x21
#define OP_ScriptFarMethodThreadCall			0x22
#define OP_JumpOnTrueExpr						0x23
#define OP_SetLevelFieldVariableField			0x24
#define OP_CastBool								0x25
#define OP_EvalNewLocalArrayRefCached0			0x26
#define OP_CallBuiltinPointer					0x27
#define OP_inequality							0x28
#define OP_GetThisthread						0x29
#define OP_ClearFieldVariable					0x2A
#define OP_GetFloat								0x2B
#define OP_SafeCreateVariableFieldCached		0x2C
#define OP_ScriptFarFunctionCall2				0x2D
#define OP_ScriptFarFunctionCall				0x2E
#define OP_ScriptFarChildThreadCall				0x2F
#define OP_ClearLocalVariableFieldCached0		0x30
#define OP_ClearLocalVariableFieldCached		0x31
#define OP_checkclearparams						0x32
#define OP_CastFieldObject						0x33
#define OP_End									0x34
#define OP_size									0x35
#define OP_EmptyArray							0x36
#define OP_bit_and								0x37
#define OP_less_equal							0x38
#define OP_voidCodepos							0x39
#define OP_ScriptMethodThreadCallPointer		0x3A
#define OP_endswitch							0x3B
#define OP_ClearVariableField					0x3C
#define OP_divide								0x3D
#define OP_ScriptFarMethodChildThreadCall		0x3E
#define OP_GetUnsignedShort						0x3F
#define OP_JumpOnTrue							0x40
#define OP_GetSelf								0x41
#define OP_ScriptFarThreadCall					0x42
#define OP_ScriptLocalThreadCall				0x43
#define OP_SetLocalVariableFieldCached0			0x44
#define OP_SetLocalVariableFieldCached			0x45
#define OP_plus									0x46
#define OP_BoolComplement						0x47
#define OP_ScriptMethodCallPointer				0x48
#define OP_inc									0x49
#define OP_RemoveLocalVariables					0x4A
#define OP_JumpOnFalseExpr						0x4B
#define OP_switch								0x4C
#define OP_clearparams							0x4D
#define OP_EvalLocalVariableRefCached0			0x4E
#define OP_EvalLocalVariableRefCached			0x4F
#define OP_ScriptLocalMethodCall				0x50
#define OP_EvalFieldVariable					0x51
#define OP_EvalFieldVariableRef					0x52
#define OP_GetString							0x53
#define OP_ScriptFunctionCallPointer			0x54
#define OP_EvalLevelFieldVariable				0x55
#define OP_GetVector							0x56
#define OP_endon								0x57
#define OP_greater_equal						0x58
#define OP_GetSelfObject						0x59
#define OP_SetAnimFieldVariableField			0x5A
#define OP_SetVariableField						0x5B
#define OP_ScriptLocalFunctionCall2				0x5C
#define OP_ScriptLocalFunctionCall				0x5D
#define OP_EvalLocalArrayRefCached0				0x5E
#define OP_EvalLocalArrayRefCached				0x5F
#define OP_GetFarFunction						0x60
#define OP_less									0x61
#define OP_GetGameRef							0x62
#define OP_waittillFrameEnd						0x63
#define OP_SafeSetVariableFieldCached0			0x64
#define OP_SafeSetVariableFieldCached			0x65
#define OP_ScriptMethodChildThreadCallPointer	0x66
#define OP_GetLevel								0x67
#define OP_notify								0x68
#define OP_DecTop								0x69
#define OP_shift_left							0x6A
#define OP_ScriptLocalMethodThreadCall			0x6B
#define OP_ScriptLocalMethodChildThreadCall		0x6C
#define OP_greater								0x6D
#define OP_EvalLocalVariableCached0				0x6E
#define OP_EvalLocalVariableCached1				0x6F
#define OP_EvalLocalVariableCached2				0x70
#define OP_EvalLocalVariableCached3				0x71
#define OP_EvalLocalVariableCached4				0x72
#define OP_EvalLocalVariableCached5				0x73
#define OP_EvalLocalVariableCached				0x74
#define OP_SafeSetWaittillVariableFieldCached	0x75
#define OP_jump									0x76
#define OP_ScriptThreadCallPointer				0x77
#define OP_GetZero								0x78
#define OP_wait									0x79
#define OP_minus								0x7A
#define OP_SetSelfFieldVariableField			0x7B
#define OP_EvalNewLocalVariableRefCached0		0x7C
#define OP_multiply								0x7D
#define OP_CreateLocalVariable					0x7E
#define OP_ScriptLocalChildThreadCall			0x7F
#define OP_GetInteger							0x80
#define OP_mod									0x81
#define OP_EvalAnimFieldVariableRef				0x82
#define OP_GetBuiltinFunction					0x83
#define OP_GetGame								0x84
#define OP_waittill								0x85
#define OP_dec									0x86
#define OP_EvalLocalVariableObjectCached		0x87
#define OP_PreScriptCall						0x88
#define OP_GetAnim								0x89
#define OP_GetUndefined							0x8A
#define OP_EvalLevelFieldVariableRef			0x8B
#define OP_GetAnimObject						0x8C
#define OP_GetLevelObject						0x8D
#define OP_bit_ex_or							0x8E
#define OP_equality								0x8F
#define OP_ClearArray							0x90
#define OP_jumpback								0x91
#define OP_GetAnimation							0x92
#define OP_EvalAnimFieldVariable		0x93
#define OP_GetAnimTree					0x94
#define OP_GetIString					0x95
#define OP_EvalArrayRef					0x96
#define OP_EvalSelfFieldVariableRef		0x97
#define OP_GetNegByte					0x98
#define OP_GetBuiltinMethod				0x99
#define OP_CallBuiltinMethodPointer		0x9A
#define OP_EvalArray				0x9B
#define OP_vector					0x9C
#define OP_ScriptFarMethodCall		0x9D
#define OP_EvalLocalArrayCached		0x9E
#define OP_GetByte					0x9F
#define OP_ScriptChildThreadCallPointer		0xA0
#define OP_bit_or				0xA1
#define OP_AddArray				0xA2
#define OP_waittillmatch2		0xA3
#define OP_waittillmatch		0xA4
#define OP_GetLocalFunction			0xA5
#define OP_GetNegUnsignedShort		0xA6
#define OP_shift_right				0xA7
#define OP_CallBuiltinMethod0		0xA8
#define OP_CallBuiltinMethod1		0xA9
#define OP_CallBuiltinMethod2		0xAA
#define OP_CallBuiltinMethod3		0xAB
#define OP_CallBuiltinMethod4		0xAC
#define OP_CallBuiltinMethod5		0xAD
#define OP_CallBuiltinMethod		0xAE
#define OP_JumpOnFalse				0xAF
#define OP_count					0xB0
