#line 1 "lexer.cpp"
#include "stdafx.hpp"
#include "h2.hpp"
#include "parser.hpp"
using namespace xsk::gsc;

#line 7 "lexer.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define h2__create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer h2__create_buffer
#endif

#ifdef yy_delete_buffer
#define h2__delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer h2__delete_buffer
#endif

#ifdef yy_scan_buffer
#define h2__scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer h2__scan_buffer
#endif

#ifdef yy_scan_string
#define h2__scan_string_ALREADY_DEFINED
#else
#define yy_scan_string h2__scan_string
#endif

#ifdef yy_scan_bytes
#define h2__scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes h2__scan_bytes
#endif

#ifdef yy_init_buffer
#define h2__init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer h2__init_buffer
#endif

#ifdef yy_flush_buffer
#define h2__flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer h2__flush_buffer
#endif

#ifdef yy_load_buffer_state
#define h2__load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state h2__load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define h2__switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer h2__switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define h2_push_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state h2_push_buffer_state
#endif

#ifdef yypop_buffer_state
#define h2_pop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state h2_pop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define h2_ensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack h2_ensure_buffer_stack
#endif

#ifdef yylex
#define h2_lex_ALREADY_DEFINED
#else
#define yylex h2_lex
#endif

#ifdef yyrestart
#define h2_restart_ALREADY_DEFINED
#else
#define yyrestart h2_restart
#endif

#ifdef yylex_init
#define h2_lex_init_ALREADY_DEFINED
#else
#define yylex_init h2_lex_init
#endif

#ifdef yylex_init_extra
#define h2_lex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra h2_lex_init_extra
#endif

#ifdef yylex_destroy
#define h2_lex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy h2_lex_destroy
#endif

#ifdef yyget_debug
#define h2_get_debug_ALREADY_DEFINED
#else
#define yyget_debug h2_get_debug
#endif

#ifdef yyset_debug
#define h2_set_debug_ALREADY_DEFINED
#else
#define yyset_debug h2_set_debug
#endif

#ifdef yyget_extra
#define h2_get_extra_ALREADY_DEFINED
#else
#define yyget_extra h2_get_extra
#endif

#ifdef yyset_extra
#define h2_set_extra_ALREADY_DEFINED
#else
#define yyset_extra h2_set_extra
#endif

#ifdef yyget_in
#define h2_get_in_ALREADY_DEFINED
#else
#define yyget_in h2_get_in
#endif

#ifdef yyset_in
#define h2_set_in_ALREADY_DEFINED
#else
#define yyset_in h2_set_in
#endif

#ifdef yyget_out
#define h2_get_out_ALREADY_DEFINED
#else
#define yyget_out h2_get_out
#endif

#ifdef yyset_out
#define h2_set_out_ALREADY_DEFINED
#else
#define yyset_out h2_set_out
#endif

#ifdef yyget_leng
#define h2_get_leng_ALREADY_DEFINED
#else
#define yyget_leng h2_get_leng
#endif

#ifdef yyget_text
#define h2_get_text_ALREADY_DEFINED
#else
#define yyget_text h2_get_text
#endif

#ifdef yyget_lineno
#define h2_get_lineno_ALREADY_DEFINED
#else
#define yyget_lineno h2_get_lineno
#endif

#ifdef yyset_lineno
#define h2_set_lineno_ALREADY_DEFINED
#else
#define yyset_lineno h2_set_lineno
#endif

#ifdef yyget_column
#define h2_get_column_ALREADY_DEFINED
#else
#define yyget_column h2_get_column
#endif

#ifdef yyset_column
#define h2_set_column_ALREADY_DEFINED
#else
#define yyset_column h2_set_column
#endif

#ifdef yywrap
#define h2_wrap_ALREADY_DEFINED
#else
#define yywrap h2_wrap
#endif

#ifdef yyalloc
#define h2_alloc_ALREADY_DEFINED
#else
#define yyalloc h2_alloc
#endif

#ifdef yyrealloc
#define h2_realloc_ALREADY_DEFINED
#else
#define yyrealloc h2_realloc
#endif

#ifdef yyfree
#define h2_free_ALREADY_DEFINED
#else
#define yyfree h2_free
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin , yyscanner )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart ( FILE *input_file , yyscan_t yyscanner );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size , yyscan_t yyscanner );
void yy_delete_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yy_flush_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
void yypop_buffer_state ( yyscan_t yyscanner );

static void yyensure_buffer_stack ( yyscan_t yyscanner );
static void yy_load_buffer_state ( yyscan_t yyscanner );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file , yyscan_t yyscanner );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER , yyscanner)

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len , yyscan_t yyscanner );

void *yyalloc ( yy_size_t , yyscan_t yyscanner );
void *yyrealloc ( void *, yy_size_t , yyscan_t yyscanner );
void yyfree ( void * , yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define h2_wrap(yyscanner) (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state ( yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  , yyscan_t yyscanner);
static int yy_get_next_buffer ( yyscan_t yyscanner );
static void yynoreturn yy_fatal_error ( const char* msg , yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;
#define YY_NUM_RULES 101
#define YY_END_OF_BUFFER 102
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[306] =
    {   0,
        0,    0,    0,    0,    0,    0,  102,  100,    1,    2,
       89,  100,  100,   88,   92,  100,   49,   50,   86,   84,
       55,   85,   56,   87,   99,   58,   59,   73,   83,   74,
       60,   95,   53,   54,   93,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   51,   91,   52,   90,    5,    6,    5,    9,   10,
        9,   70,    0,   97,    0,    0,    0,    0,   79,    0,
       68,    0,   81,    0,    0,   77,   61,   75,   62,   76,
       98,    0,    8,    4,    3,   78,   98,   99,    0,    0,
       57,   65,   71,   69,   72,   66,   95,   82,   95,   95,

       95,   95,   95,   95,   95,   95,   95,   95,   95,   25,
       30,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   80,   67,    7,   11,    0,   97,    0,    0,
        0,    0,    0,   96,    0,    0,    0,    0,   97,    0,
       98,    0,    3,   98,   98,   94,   63,   64,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   28,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,    0,    0,    0,    0,   96,    0,    0,   96,
        0,    0,   47,   95,   40,   32,   95,   95,   95,   26,
       95,   95,   95,   45,   95,   95,   95,   95,   46,   95,

       95,   95,   41,   95,   20,   95,    0,    0,    0,   44,
       34,   95,   95,   95,   18,   42,   95,   48,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   27,    0,    0,
        0,   95,   95,   95,   95,   95,   19,   95,   95,   36,
       31,   95,   37,   95,   95,   95,    0,    0,    0,   95,
       95,   95,   33,   29,   95,   95,   95,   95,   95,   95,
        0,   15,    0,   95,   95,   35,   95,   14,   95,   95,
       95,   21,   17,    0,   95,   95,   95,   95,   43,   24,
       95,   95,    0,   12,   95,   13,   39,   95,   95,    0,
       38,   95,   95,    0,   95,   95,    0,   95,   22,    0,

       95,   16,   95,   23,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,   24,    1,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       26,   27,   28,   29,   30,    1,   31,   32,   33,   34,

       35,   36,   37,   38,   39,   25,   40,   41,   42,   43,
       44,   45,   25,   46,   47,   48,   49,   50,   51,   25,
       52,   53,   54,   55,   56,   57,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[58] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    1,    4,    1,    1,
        1,    1,    1,    1,    4,    1,    5,    1,    1,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[320] =
    {   0,
        0,    0,   55,   56,   57,   58,  575,  576,  576,  576,
      552,   57,   34,  551,   66,   60,  576,  576,  550,   57,
      576,   63,   48,   74,   74,  552,  576,   55,  548,   59,
      576,  542,  576,  576,  546,   62,   66,   71,   72,   67,
       73,   87,   70,   76,   89,   92,   93,   94,   96,   97,
       99,  576,  100,  576,  576,  576,  576,  550,  576,  576,
      549,  576,  120,  576,  136,  522,  521,  516,  576,  122,
      576,  123,  576,  126,  143,  576,  576,  576,  576,  576,
      118,  523,  576,  576,    0,  576,  125,  140,  132,    0,
      576,  539,  576,  576,  576,  538,  532,  576,  130,  133,

      124,  135,  137,  139,  145,  149,  146,  150,  151,  531,
      530,  152,  155,  154,  157,  158,  161,  162,  163,  170,
      167,  168,  576,  576,  576,  576,  186,  204,  211,  517,
      522,  515,  205,  576,  212,  202,  215,  210,  213,  217,
      576,  500,    0,  205,  576,  525,  576,  576,  194,  203,
      206,  200,  216,  198,  218,  221,  223,  224,  225,  226,
      227,  231,  228,  232,  236,  238,  241,  239,  242,  248,
      246,  249,  509,  509,  506,  273,  274,  277,  275,  276,
      284,  513,  520,  104,  519,  518,  262,  268,  264,  517,
      265,  270,  279,  516,  271,  282,  287,  288,  515,  289,

      272,  292,  514,  294,  297,  300,  492,  490,  501,  576,
      298,  299,  301,  305,  510,  509,  304,  508,  302,  321,
      309,  311,  312,  324,  328,  313,  330,  507,  487,  498,
      501,  333,  334,  314,  335,  337,  503,  338,  339,  502,
      501,  341,  500,  343,  347,  344,  491,  490,  493,  349,
      352,  354,  496,  495,  353,  357,  365,  366,  367,  369,
      486,  576,  477,  368,  370,  492,  375,  491,  372,  379,
      377,  380,  576,  478,  381,  388,  390,  391,  489,  488,
      393,  396,  472,  473,  394,  425,  424,  399,  397,  402,
      422,  404,  405,  398,  407,  409,  405,  408,  315,  193,

      410,  576,  414,  159,  576,  453,  458,  463,  468,  471,
      473,  478,  483,  488,  493,  498,   68,  503,  508
    } ;

static const flex_int16_t yy_def[320] =
    {   0,
      305,    1,  306,  306,  307,  307,  305,  305,  305,  305,
      305,  308,  305,  305,  305,  309,  305,  305,  305,  305,
      305,  305,  305,  305,  310,  305,  305,  305,  305,  305,
      305,  311,  305,  305,  305,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  308,  305,  312,  305,  305,  305,  305,  313,
      305,  314,  305,  309,  315,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  316,  305,  305,  310,  310,  317,
      305,  305,  305,  305,  305,  305,  311,  305,  311,  311,

      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  305,  305,  305,  305,  308,  308,  312,  305,
      305,  305,  313,  305,  318,  314,  319,  309,  309,  315,
      305,  305,  316,  305,  305,  317,  305,  305,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  305,  305,  305,  313,  313,  318,  314,  314,
      319,  305,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,

      311,  311,  311,  311,  311,  311,  305,  305,  305,  305,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  305,  305,
      305,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  305,  305,  305,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      305,  305,  305,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  305,  305,  311,  311,  311,  311,  311,  311,
      311,  311,  305,  311,  311,  311,  311,  311,  311,  305,
      311,  311,  311,  305,  311,  311,  305,  311,  311,  305,

      311,  305,  311,  311,    0,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305
    } ;

static const flex_int16_t yy_nxt[634] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,    8,   34,   35,   32,
       36,   37,   38,   39,   40,   41,   42,   32,   43,   32,
       44,   32,   45,   32,   46,   47,   48,   49,   50,   32,
       51,   32,   32,   52,   53,   54,   55,   57,   57,   60,
       60,   64,   61,   61,   66,   81,   58,   58,   64,   77,
       70,  146,   67,   71,   72,   92,   93,   79,   78,   83,
       95,   96,   68,   65,   80,   84,   75,   73,   90,   87,
       85,   88,   90,   90,   82,   86,   90,   90,   90,   90,

       90,  101,   90,  107,   99,  110,  104,  105,  102,  106,
      112,  100,  111,   90,  103,   90,  108,  109,   90,   90,
       90,  123,   90,   90,   64,   90,  134,  115,  116,  121,
       90,  134,  113,  118,   64,   81,  122,  114,   63,  120,
      128,  119,  144,  211,  117,   74,   65,  305,  135,  137,
       90,  139,   75,  141,  124,   87,   90,   88,   90,   90,
      145,   90,  129,   90,  151,   90,   90,  150,  149,  140,
      152,   90,   90,  153,  155,   90,   90,   90,   90,  154,
       90,   90,  157,   90,   90,   90,  158,   90,   90,   90,
       64,  156,  160,   90,   90,  159,   90,  163,  165,  166,

      167,  161,  162,  170,  164,  171,  172,  168,   64,  134,
      134,  169,   65,   63,  133,  128,  177,  136,   64,   74,
       90,   64,  144,  180,   90,  139,   90,  302,  137,   90,
       65,  135,   90,  184,  186,  183,   75,  129,  178,   75,
      145,  181,   90,  140,   90,  188,  185,   90,  189,   90,
       90,   90,   90,   90,   90,  190,  187,   90,   90,  193,
      194,  195,   90,  197,   90,   90,  191,   90,   90,  196,
      192,  199,   90,  202,   90,   90,  203,  134,  134,  133,
      198,  177,  204,  134,  134,  200,  136,  201,   90,  206,
       90,   90,  180,  205,   90,  212,   90,   90,   90,  135,

      135,  137,  137,  178,  216,   90,  213,  215,   90,  217,
      181,  218,  214,   90,   90,   90,  220,  219,   90,  223,
       90,  222,  224,   90,   90,   90,   90,   90,   90,  225,
       90,   90,  226,  221,  228,   90,  236,   90,   90,   90,
       90,   90,  232,  234,  227,  235,  233,   90,  241,  242,
       90,  240,  238,  237,   90,  239,   90,  243,  245,   90,
       90,   90,  252,   90,   90,   90,  244,   90,  246,   90,
       90,  251,  255,   90,  254,   90,  250,  259,   90,   90,
       90,  256,  253,   90,  260,  258,  257,  264,  266,  267,
      268,   90,   90,   90,   90,   90,   90,  265,   90,  269,

      270,   90,  278,   90,  276,   90,   90,   90,  271,  272,
      275,  280,  279,  277,   90,  281,   90,   90,  285,   90,
       90,  282,   90,   90,  287,   90,  289,  291,  284,  292,
       90,   90,  286,   90,   90,   90,   90,  296,  288,  300,
       90,  298,  301,  297,  293,  295,  299,  304,   90,  294,
       90,   90,  303,   56,   56,   56,   56,   56,   59,   59,
       59,   59,   59,   63,   63,   63,   63,   63,   74,   74,
       74,   74,   74,   89,   89,   89,   97,   97,  127,  127,
      127,  127,  127,  133,  133,  133,  133,  133,  136,  136,
      136,  136,  136,  138,  138,  138,  138,  138,  143,   90,

      143,  143,  143,  176,  176,  176,  176,  176,  179,  179,
      179,  179,  179,  290,   90,   90,  283,   90,   90,  274,
      273,   90,   90,  263,  262,  261,   90,   90,   90,   90,
      249,  248,  247,   90,   90,   90,   90,  231,  230,  229,
       90,   90,   90,   90,   90,   90,   90,  210,  209,  208,
      207,   90,  182,  175,  174,  173,   90,   90,   90,  148,
      147,  142,  132,  131,  130,  126,  125,   98,   90,   94,
       91,   76,   69,   62,  305,    7,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,

      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305
    } ;

static const flex_int16_t yy_chk[634] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    4,    5,
        6,   12,    5,    6,   13,   23,    3,    4,   16,   20,
       15,  317,   13,   15,   15,   28,   28,   22,   20,   24,
       30,   30,   13,   12,   22,   24,   16,   15,   36,   25,
       24,   25,   37,   40,   23,   24,   43,   38,   39,   41,

       25,   38,   44,   41,   36,   43,   39,   40,   38,   40,
       44,   37,   43,   42,   38,   45,   41,   42,   46,   47,
       48,   53,   49,   50,   63,   51,   70,   47,   48,   51,
      184,   72,   45,   49,   74,   81,   51,   46,   65,   50,
       65,   49,   87,  184,   48,   75,   63,   89,   70,   72,
      101,   75,   74,   81,   53,   88,   99,   88,   89,  100,
       87,  102,   65,  103,  101,  104,   88,  100,   99,   75,
      101,  105,  107,  102,  104,  106,  108,  109,  112,  103,
      114,  113,  106,  115,  116,  304,  107,  117,  118,  119,
      127,  105,  109,  121,  122,  108,  120,  114,  116,  117,

      118,  112,  113,  120,  115,  121,  122,  118,  128,  133,
      136,  119,  127,  129,  135,  129,  135,  137,  138,  140,
      149,  139,  144,  137,  154,  140,  152,  300,  136,  150,
      128,  133,  151,  150,  152,  149,  138,  129,  135,  139,
      144,  137,  153,  140,  155,  154,  151,  156,  155,  157,
      158,  159,  160,  161,  163,  156,  153,  162,  164,  159,
      160,  161,  165,  163,  166,  168,  157,  167,  169,  162,
      158,  165,  171,  168,  170,  172,  169,  176,  177,  178,
      164,  178,  170,  179,  180,  166,  181,  167,  187,  172,
      189,  191,  181,  171,  188,  187,  192,  195,  201,  176,

      177,  179,  180,  178,  192,  193,  188,  191,  196,  193,
      181,  195,  189,  197,  198,  200,  197,  196,  202,  201,
      204,  200,  202,  205,  211,  212,  206,  213,  219,  204,
      217,  214,  205,  198,  206,  221,  217,  222,  223,  226,
      234,  299,  211,  213,  205,  214,  212,  220,  222,  223,
      224,  221,  220,  219,  225,  220,  227,  224,  226,  232,
      233,  235,  234,  236,  238,  239,  225,  242,  227,  244,
      246,  233,  238,  245,  236,  250,  232,  245,  251,  255,
      252,  239,  235,  256,  246,  244,  242,  250,  252,  255,
      256,  257,  258,  259,  264,  260,  265,  251,  269,  257,

      258,  267,  269,  271,  265,  270,  272,  275,  259,  260,
      264,  271,  270,  267,  276,  272,  277,  278,  276,  281,
      285,  272,  282,  289,  278,  288,  282,  285,  275,  288,
      292,  293,  277,  295,  298,  296,  301,  293,  281,  297,
      303,  295,  298,  294,  289,  292,  296,  303,  291,  290,
      287,  286,  301,  306,  306,  306,  306,  306,  307,  307,
      307,  307,  307,  308,  308,  308,  308,  308,  309,  309,
      309,  309,  309,  310,  310,  310,  311,  311,  312,  312,
      312,  312,  312,  313,  313,  313,  313,  313,  314,  314,
      314,  314,  314,  315,  315,  315,  315,  315,  316,  284,

      316,  316,  316,  318,  318,  318,  318,  318,  319,  319,
      319,  319,  319,  283,  280,  279,  274,  268,  266,  263,
      261,  254,  253,  249,  248,  247,  243,  241,  240,  237,
      231,  230,  229,  228,  218,  216,  215,  209,  208,  207,
      203,  199,  194,  190,  186,  185,  183,  182,  175,  174,
      173,  146,  142,  132,  131,  130,  111,  110,   97,   96,
       92,   82,   68,   67,   66,   61,   58,   35,   32,   29,
       26,   19,   14,   11,    7,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,

      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "lexer.lpp"
/* Copyright 2021 xensik. All rights reserved.
//
// Use of this source code is governed by a GNU GPLv3 license
// that can be found in the LICENSE file.
*/
#define YY_NO_INPUT 1
#define YY_NO_UNISTD_H 1

#line 23 "lexer.lpp"
#define YY_USER_ACTION  loc.columns(yyleng);
#line 889 "lexer.cpp"

#line 891 "lexer.cpp"

#define INITIAL 0
#define COMMENT_BLOCK_STATE 1
#define DEVELOPER_BLOCK_STATE 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    }; /* end struct yyguts_t */

static int yy_init_globals ( yyscan_t yyscanner );

int yylex_init (yyscan_t* scanner);

int yylex_init_extra ( YY_EXTRA_TYPE user_defined, yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( yyscan_t yyscanner );

int yyget_debug ( yyscan_t yyscanner );

void yyset_debug ( int debug_flag , yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra ( yyscan_t yyscanner );

void yyset_extra ( YY_EXTRA_TYPE user_defined , yyscan_t yyscanner );

FILE *yyget_in ( yyscan_t yyscanner );

void yyset_in  ( FILE * _in_str , yyscan_t yyscanner );

FILE *yyget_out ( yyscan_t yyscanner );

void yyset_out  ( FILE * _out_str , yyscan_t yyscanner );

			int yyget_leng ( yyscan_t yyscanner );

char *yyget_text ( yyscan_t yyscanner );

int yyget_lineno ( yyscan_t yyscanner );

void yyset_lineno ( int _line_number , yyscan_t yyscanner );

int yyget_column  ( yyscan_t yyscanner );

void yyset_column ( int _column_no , yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( yyscan_t yyscanner );
#else
extern int yywrap ( yyscan_t yyscanner );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int , yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * , yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( yyscan_t yyscanner );
#else
static int input ( yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (yyscan_t yyscanner);

#define YY_DECL int yylex (yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
		}

		yy_load_buffer_state( yyscanner );
		}

	{
#line 36 "lexer.lpp"



#line 40 "lexer.lpp"
    loc.step();


#line 1159 "lexer.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 306 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 305 );
		yy_cp = yyg->yy_last_accepting_cpos;
		yy_current_state = yyg->yy_last_accepting_state;

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 43 "lexer.lpp"
{ loc.step(); }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 45 "lexer.lpp"
{ loc.lines(yyleng); loc.step(); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 47 "lexer.lpp"

	YY_BREAK
case 4:
YY_RULE_SETUP
#line 49 "lexer.lpp"
{ BEGIN(COMMENT_BLOCK_STATE); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 50 "lexer.lpp"

	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 51 "lexer.lpp"
{ loc.lines(yyleng); loc.step(); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 52 "lexer.lpp"
{ BEGIN(INITIAL); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 54 "lexer.lpp"
{ BEGIN(DEVELOPER_BLOCK_STATE); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 55 "lexer.lpp"

	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 56 "lexer.lpp"
{ loc.lines(yyleng); loc.step(); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 57 "lexer.lpp"
{ BEGIN(INITIAL); }    
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 59 "lexer.lpp"
{ return h2::parser::make_BREAKPOINT(loc); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 60 "lexer.lpp"
{ return h2::parser::make_PROFBEGIN(loc); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 61 "lexer.lpp"
{ return h2::parser::make_PROFEND(loc); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 62 "lexer.lpp"
{ return h2::parser::make_INCLUDE(loc); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 63 "lexer.lpp"
{ return h2::parser::make_USINGTREE(loc); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 64 "lexer.lpp"
{ return h2::parser::make_ANIMTREE(loc); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 65 "lexer.lpp"
{ return h2::parser::make_ENDON(loc); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 66 "lexer.lpp"
{ return h2::parser::make_NOTIFY(loc); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 67 "lexer.lpp"
{ return h2::parser::make_WAIT(loc); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 68 "lexer.lpp"
{ return h2::parser::make_WAITTILL(loc); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 69 "lexer.lpp"
{ return h2::parser::make_WAITTILLMATCH(loc); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 70 "lexer.lpp"
{ return h2::parser::make_WAITTILLFRAMEEND(loc); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 71 "lexer.lpp"
{ return h2::parser::make_WAITFRAME(loc); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 72 "lexer.lpp"
{ return h2::parser::make_IF(loc); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 73 "lexer.lpp"
{ return h2::parser::make_ELSE(loc); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 74 "lexer.lpp"
{ return h2::parser::make_WHILE(loc); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 75 "lexer.lpp"
{ return h2::parser::make_FOR(loc); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 76 "lexer.lpp"
{ return h2::parser::make_FOREACH(loc); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 77 "lexer.lpp"
{ return h2::parser::make_IN(loc); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 78 "lexer.lpp"
{ return h2::parser::make_SWITCH(loc); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 79 "lexer.lpp"
{ return h2::parser::make_CASE(loc); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 80 "lexer.lpp"
{ return h2::parser::make_DEFAULT(loc); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 81 "lexer.lpp"
{ return h2::parser::make_BREAK(loc); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 82 "lexer.lpp"
{ return h2::parser::make_CONTINUE(loc); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 83 "lexer.lpp"
{ return h2::parser::make_RETURN(loc); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 84 "lexer.lpp"
{ return h2::parser::make_THREAD(loc); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 85 "lexer.lpp"
{ return h2::parser::make_CHILDTHREAD(loc); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 86 "lexer.lpp"
{ return h2::parser::make_THISTHREAD(loc); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 87 "lexer.lpp"
{ return h2::parser::make_CALL(loc); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 88 "lexer.lpp"
{ return h2::parser::make_TRUE(loc); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 89 "lexer.lpp"
{ return h2::parser::make_FALSE(loc); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 90 "lexer.lpp"
{ return h2::parser::make_UNDEFINED(loc); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 91 "lexer.lpp"
{ return h2::parser::make_SIZE(loc); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 92 "lexer.lpp"
{ return h2::parser::make_GAME(loc); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 93 "lexer.lpp"
{ return h2::parser::make_SELF(loc); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 94 "lexer.lpp"
{ return h2::parser::make_ANIM(loc); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 95 "lexer.lpp"
{ return h2::parser::make_LEVEL(loc); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 96 "lexer.lpp"
{ return h2::parser::make_LPAREN(loc); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 97 "lexer.lpp"
{ return h2::parser::make_RPAREN(loc); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 98 "lexer.lpp"
{ return h2::parser::make_LBRACE(loc); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 99 "lexer.lpp"
{ return h2::parser::make_RBRACE(loc); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 100 "lexer.lpp"
{ return h2::parser::make_LBRACKET(loc); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 101 "lexer.lpp"
{ return h2::parser::make_RBRACKET(loc); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 102 "lexer.lpp"
{ return h2::parser::make_COMMA(loc); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 103 "lexer.lpp"
{ return h2::parser::make_DOT(loc); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 104 "lexer.lpp"
{ return h2::parser::make_DOUBLECOLON(loc); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 105 "lexer.lpp"
{ return h2::parser::make_COLON(loc); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 106 "lexer.lpp"
{ return h2::parser::make_SEMICOLON(loc); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 107 "lexer.lpp"
{ return h2::parser::make_QMARK(loc); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 108 "lexer.lpp"
{ return h2::parser::make_INCREMENT(loc); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 109 "lexer.lpp"
{ return h2::parser::make_DECREMENT(loc); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 110 "lexer.lpp"
{ return h2::parser::make_ASSIGN_LSHIFT(loc); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 111 "lexer.lpp"
{ return h2::parser::make_ASSIGN_RSHIFT(loc); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 112 "lexer.lpp"
{ return h2::parser::make_LSHIFT(loc); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 113 "lexer.lpp"
{ return h2::parser::make_RSHIFT(loc); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 114 "lexer.lpp"
{ return h2::parser::make_OR(loc); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 115 "lexer.lpp"
{ return h2::parser::make_AND(loc); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 116 "lexer.lpp"
{ return h2::parser::make_EQUALITY(loc); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 117 "lexer.lpp"
{ return h2::parser::make_INEQUALITY(loc); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 118 "lexer.lpp"
{ return h2::parser::make_LESS_EQUAL(loc); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 119 "lexer.lpp"
{ return h2::parser::make_GREATER_EQUAL(loc); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 120 "lexer.lpp"
{ return h2::parser::make_LESS(loc); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 121 "lexer.lpp"
{ return h2::parser::make_GREATER(loc); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 122 "lexer.lpp"
{ return h2::parser::make_ASSIGN_ADD(loc); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 123 "lexer.lpp"
{ return h2::parser::make_ASSIGN_SUB(loc); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 124 "lexer.lpp"
{ return h2::parser::make_ASSIGN_MULT(loc); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 125 "lexer.lpp"
{ return h2::parser::make_ASSIGN_DIV(loc); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 126 "lexer.lpp"
{ return h2::parser::make_ASSIGN_MOD(loc); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 127 "lexer.lpp"
{ return h2::parser::make_ASSIGN_BITWISE_OR(loc); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 128 "lexer.lpp"
{ return h2::parser::make_ASSIGN_BITWISE_AND(loc); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 129 "lexer.lpp"
{ return h2::parser::make_ASSIGN_BITWISE_EXOR(loc); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 130 "lexer.lpp"
{ return h2::parser::make_ASSIGN(loc); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 131 "lexer.lpp"
{ return h2::parser::make_ADD(loc); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 132 "lexer.lpp"
{ return h2::parser::make_SUB(loc); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 133 "lexer.lpp"
{ return h2::parser::make_MULT(loc); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 134 "lexer.lpp"
{ return h2::parser::make_DIV(loc); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 135 "lexer.lpp"
{ return h2::parser::make_MOD(loc); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 136 "lexer.lpp"
{ return h2::parser::make_NOT(loc); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 137 "lexer.lpp"
{ return h2::parser::make_COMPLEMENT(loc); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 138 "lexer.lpp"
{ return h2::parser::make_BITWISE_OR(loc); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 139 "lexer.lpp"
{ return h2::parser::make_BITWISE_AND(loc); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 140 "lexer.lpp"
{ return h2::parser::make_BITWISE_EXOR(loc); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 141 "lexer.lpp"
{ return h2::parser::make_FILE(utils::string::fordslash(yytext), loc); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 142 "lexer.lpp"
{ return h2::parser::make_NAME((std::string(yytext, 3) == "_ID") ? std::string(yytext) : utils::string::to_lower(yytext), loc); }
	YY_BREAK
case 96:
/* rule 96 can match eol */
YY_RULE_SETUP
#line 143 "lexer.lpp"
{ return h2::parser::make_ISTRING(std::string(yytext).substr(1), loc); }
	YY_BREAK
case 97:
/* rule 97 can match eol */
YY_RULE_SETUP
#line 144 "lexer.lpp"
{ return h2::parser::make_STRING(std::string(yytext), loc); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 145 "lexer.lpp"
{ return h2::parser::make_FLOAT(std::string(yytext), loc); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 146 "lexer.lpp"
{ return h2::parser::make_INTEGER(std::string(yytext), loc); }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT_BLOCK_STATE):
case YY_STATE_EOF(DEVELOPER_BLOCK_STATE):
#line 147 "lexer.lpp"
{ return h2::parser::make_H2EOF(loc); }
	YY_BREAK
case 100:
/* rule 100 can match eol */
YY_RULE_SETUP
#line 148 "lexer.lpp"
{ throw h2::parser::syntax_error(loc, "bad token: \'" + std::string(yytext) + "\'"); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 150 "lexer.lpp"
ECHO;
	YY_BREAK
#line 1729 "lexer.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_last_accepting_cpos;
				yy_current_state = yyg->yy_last_accepting_state;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap( yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  , yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size , yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 306 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	char *yy_cp = yyg->yy_c_buf_p;

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 306 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 305);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr);
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin , yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file , yyscanner);
	yy_load_buffer_state( yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file , yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf , yyscanner );

	yyfree( (void *) b , yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer( b , yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER , yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b , yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) , yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n , yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n , yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param _line_number line number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  _line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_lineno called with no buffer" );
    
    yylineno = _line_number;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_column called with no buffer" );
    
    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

void yyset_out (FILE *  _out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = _out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  _bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = _bdebug ;
}

/* Accessor methods for yylval and yylloc */

/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */
int yylex_init(yyscan_t* ptr_yy_globals)
{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */
int yylex_init_extra( YY_EXTRA_TYPE yy_user_defined, yyscan_t* ptr_yy_globals )
{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    yyset_extra (yy_user_defined, *ptr_yy_globals);

    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = NULL;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = NULL;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER , yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack , yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree( yyg->yy_start_stack , yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 150 "lexer.lpp"


