// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_africa_militia_assault_c");
	self attach("head_africa_militia_a_hat", "", true);
	self.headModel = "head_africa_militia_a_hat";
	self.voice = "african";
}

precache()
{
	precacheModel("body_africa_militia_assault_c");
	precacheModel("head_africa_militia_a_hat");
}
