// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_africa_militia_assault_a");
	codescripts\character::attachHead( "alias_africa_militia_heads_a", xmodelalias\alias_africa_militia_heads_a::main() );
	if ( isendstr( self.headModel, "_hat" ) )
		codescripts\character::attachHat( "alias_africa_militia_hats_a", xmodelalias\alias_africa_militia_hats_a::main() );
	self.voice = "african";
}

precache()
{
	precacheModel("body_africa_militia_assault_a");
	codescripts\character::precacheModelArray(xmodelalias\alias_africa_militia_heads_a::main());
	codescripts\character::precacheModelArray(xmodelalias\alias_africa_militia_hats_a::main());
}
