#line 2 "lexer.cpp"
#include "stdafx.hpp"
#include "iw5.hpp"
#include "parser.hpp"
using namespace xsk::gsc;

#line 8 "lexer.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define iw5__create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer iw5__create_buffer
#endif

#ifdef yy_delete_buffer
#define iw5__delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer iw5__delete_buffer
#endif

#ifdef yy_scan_buffer
#define iw5__scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer iw5__scan_buffer
#endif

#ifdef yy_scan_string
#define iw5__scan_string_ALREADY_DEFINED
#else
#define yy_scan_string iw5__scan_string
#endif

#ifdef yy_scan_bytes
#define iw5__scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes iw5__scan_bytes
#endif

#ifdef yy_init_buffer
#define iw5__init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer iw5__init_buffer
#endif

#ifdef yy_flush_buffer
#define iw5__flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer iw5__flush_buffer
#endif

#ifdef yy_load_buffer_state
#define iw5__load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state iw5__load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define iw5__switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer iw5__switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define iw5_push_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state iw5_push_buffer_state
#endif

#ifdef yypop_buffer_state
#define iw5_pop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state iw5_pop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define iw5_ensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack iw5_ensure_buffer_stack
#endif

#ifdef yylex
#define iw5_lex_ALREADY_DEFINED
#else
#define yylex iw5_lex
#endif

#ifdef yyrestart
#define iw5_restart_ALREADY_DEFINED
#else
#define yyrestart iw5_restart
#endif

#ifdef yylex_init
#define iw5_lex_init_ALREADY_DEFINED
#else
#define yylex_init iw5_lex_init
#endif

#ifdef yylex_init_extra
#define iw5_lex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra iw5_lex_init_extra
#endif

#ifdef yylex_destroy
#define iw5_lex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy iw5_lex_destroy
#endif

#ifdef yyget_debug
#define iw5_get_debug_ALREADY_DEFINED
#else
#define yyget_debug iw5_get_debug
#endif

#ifdef yyset_debug
#define iw5_set_debug_ALREADY_DEFINED
#else
#define yyset_debug iw5_set_debug
#endif

#ifdef yyget_extra
#define iw5_get_extra_ALREADY_DEFINED
#else
#define yyget_extra iw5_get_extra
#endif

#ifdef yyset_extra
#define iw5_set_extra_ALREADY_DEFINED
#else
#define yyset_extra iw5_set_extra
#endif

#ifdef yyget_in
#define iw5_get_in_ALREADY_DEFINED
#else
#define yyget_in iw5_get_in
#endif

#ifdef yyset_in
#define iw5_set_in_ALREADY_DEFINED
#else
#define yyset_in iw5_set_in
#endif

#ifdef yyget_out
#define iw5_get_out_ALREADY_DEFINED
#else
#define yyget_out iw5_get_out
#endif

#ifdef yyset_out
#define iw5_set_out_ALREADY_DEFINED
#else
#define yyset_out iw5_set_out
#endif

#ifdef yyget_leng
#define iw5_get_leng_ALREADY_DEFINED
#else
#define yyget_leng iw5_get_leng
#endif

#ifdef yyget_text
#define iw5_get_text_ALREADY_DEFINED
#else
#define yyget_text iw5_get_text
#endif

#ifdef yyget_lineno
#define iw5_get_lineno_ALREADY_DEFINED
#else
#define yyget_lineno iw5_get_lineno
#endif

#ifdef yyset_lineno
#define iw5_set_lineno_ALREADY_DEFINED
#else
#define yyset_lineno iw5_set_lineno
#endif

#ifdef yyget_column
#define iw5_get_column_ALREADY_DEFINED
#else
#define yyget_column iw5_get_column
#endif

#ifdef yyset_column
#define iw5_set_column_ALREADY_DEFINED
#else
#define yyset_column iw5_set_column
#endif

#ifdef yywrap
#define iw5_wrap_ALREADY_DEFINED
#else
#define yywrap iw5_wrap
#endif

#ifdef yyalloc
#define iw5_alloc_ALREADY_DEFINED
#else
#define yyalloc iw5_alloc
#endif

#ifdef yyrealloc
#define iw5_realloc_ALREADY_DEFINED
#else
#define yyrealloc iw5_realloc
#endif

#ifdef yyfree
#define iw5_free_ALREADY_DEFINED
#else
#define yyfree iw5_free
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin , yyscanner )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart ( FILE *input_file , yyscan_t yyscanner );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size , yyscan_t yyscanner );
void yy_delete_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yy_flush_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
void yypop_buffer_state ( yyscan_t yyscanner );

static void yyensure_buffer_stack ( yyscan_t yyscanner );
static void yy_load_buffer_state ( yyscan_t yyscanner );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file , yyscan_t yyscanner );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER , yyscanner)

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len , yyscan_t yyscanner );

void *yyalloc ( yy_size_t , yyscan_t yyscanner );
void *yyrealloc ( void *, yy_size_t , yyscan_t yyscanner );
void yyfree ( void * , yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define iw5_wrap(yyscanner) (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state ( yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  , yyscan_t yyscanner);
static int yy_get_next_buffer ( yyscan_t yyscanner );
static void yynoreturn yy_fatal_error ( const char* msg , yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;
#define YY_NUM_RULES 106
#define YY_END_OF_BUFFER 107
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[320] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,  107,  105,
        1,    2,   90,  105,  105,   89,   93,  105,   50,   51,
       87,   85,   56,   86,   57,   88,  104,  104,   59,   60,
       74,   84,   75,   61,   96,   54,   55,   94,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   52,   92,   53,   91,    5,    6,
        5,  105,   87,    9,   10,    9,   71,    0,   98,    0,
       13,    0,    0,    0,    0,   80,    0,   69,    0,   82,
        0,    0,   12,   78,   62,   76,   63,   77,  100,    0,
        8,    4,    3,   79,  100,  104,  101,    0,    0,    0,

        0,   58,   66,   72,   70,   73,   67,   96,   83,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   96,   96,
       26,   31,   96,   96,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   81,   68,    7,   11,    0,   98,    0,
        0,    0,    0,    0,    0,   97,    0,    0,    0,    0,
       98,    0,  100,    0,    3,  100,  100,  101,  102,  103,
       95,   64,   65,   96,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   29,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   99,    0,    0,
        0,    0,   97,    0,    0,   97,    0,    0,   48,   96,

       41,   33,   96,   96,   96,   27,   96,   96,   96,   46,
       96,   96,   96,   96,   47,   96,   96,   96,   42,   96,
       22,   96,    0,    0,    0,    0,   45,   35,   96,   96,
       96,   20,   43,   96,   49,   96,   96,   96,   96,   96,
       96,   96,   96,   28,    0,    0,    0,    0,   96,   96,
       96,   96,   96,   21,   96,   96,   37,   32,   96,   38,
       96,   96,   99,    0,    0,    0,   96,   96,   96,   34,
       30,   96,   96,   96,   96,   96,    0,   17,    0,   96,
       96,   36,   96,   16,   96,   96,   23,   19,    0,   96,
       96,   96,   96,   44,   96,   96,    0,   14,   96,   15,

       40,   96,   96,    0,   39,   96,   96,    0,   96,   96,
        0,   96,   24,    0,   96,   18,   96,   25,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   29,   28,   28,   28,   28,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   31,   30,   30,
       32,   33,   34,   35,   36,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   30,   46,   47,   48,   49,
       50,   51,   30,   52,   53,   54,   55,   56,   57,   31,
       58,   59,   60,   61,   62,   63,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[64] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    4,    5,    5,    5,
        5,    1,    1,    1,    1,    1,    1,    5,    5,    6,
        6,    1,    7,    1,    1,    6,    5,    5,    5,    5,
        5,    5,    6,    6,    8,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    8,    6,    6,    6,    6,    1,
        1,    1,    1
    } ;

static const flex_int16_t yy_base[340] =
    {   0,
        0,    0,   61,   62,   60,   63,   64,   65,  690,  691,
      691,  691,  664,   71,   60,  663,   73,   70,  691,  691,
       63,   70,  691,   69,   71,   94,  102,  109,  665,  691,
       61,  661,   76,  691,  652,  691,  691,  659,   60,   74,
       99,   75,   63,  101,   80,  104,  106,  108,  111,  115,
      119,  117,  121,  122,  691,  120,  691,  691,  691,  691,
      666,  140,  657,  691,  691,  664,  691,  157,  691,  168,
      691,    0,  631,  630,  625,  691,  159,  691,  156,  691,
      158,  165,  691,  691,  691,  691,  691,  691,  184,  632,
      691,  691,    0,  691,  188,  194,  200,  163,  164,  218,

        0,  691,  651,  691,  691,  691,  650,  641,  691,   54,
      145,  178,  139,  191,  190,  189,  154,  196,  202,  215,
      640,  639,  208,  195,  167,  211,  219,  217,  228,  212,
      235,  236,  237,  691,  691,  691,  691,  266,  267,  271,
        0,  626,  631,  624,  272,  691,  280,  166,  275,  270,
      277,  284,  691,  609,    0,  270,  691,  276,  300,    0,
      634,  691,  691,  273,  265,  268,  281,  278,  274,  287,
      290,  293,  294,  296,  297,  299,  301,  302,  303,  306,
      308,  312,  309,  316,  318,  319,  320,    0,  618,  618,
      615,  349,  350,  358,  347,  351,  361,  622,  629,  333,

      628,  627,  335,  336,  338,  626,  339,  344,  341,  625,
      343,  353,  356,  354,  624,  363,  364,  366,  623,  365,
      367,  368,    0,  601,  599,  610,  691,  371,  372,  375,
      378,  619,  618,  377,  617,  379,  382,  380,  384,  386,
      394,  398,  399,  616,    0,  596,  607,  610,  400,  402,
      381,  405,  407,  612,  406,  408,  611,  610,  409,  609,
      415,  416,  691,  600,  599,  602,  420,  419,  421,  605,
      604,  412,  427,  425,  435,  423,  595,  691,  586,  436,
      439,  601,  441,  600,  440,  442,  445,  691,  587,  446,
      451,  448,  450,  598,  456,  458,  582,  579,  459,  570,

      528,  461,  463,  496,  516,  468,  470,  469,  469,  471,
      479,  472,  486,  477,  473,  691,  474,  479,  691,  522,
      530,  538,  543,  551,  557,  561,  569,  506,  577,  585,
      593,  601,  605,  248,  613,  621,  188,  183,  109
    } ;

static const flex_int16_t yy_def[340] =
    {   0,
      319,    1,  320,  320,    1,    1,  321,  321,  319,  319,
      319,  319,  319,  322,  323,  319,  319,  324,  319,  319,
      319,  319,  319,  319,  319,  319,  325,  325,  319,  319,
      319,  319,  319,  319,  326,  319,  319,  319,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  319,  319,  319,  319,  319,  319,
      319,  323,  319,  319,  319,  319,  319,  322,  319,  327,
      319,  328,  328,  319,  319,  319,  329,  319,  330,  319,
      324,  331,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  332,  319,  319,  325,  325,  325,  325,  325,

      333,  319,  319,  319,  319,  319,  319,  326,  319,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  319,  319,  319,  319,  322,  322,  327,
      334,  319,  319,  319,  329,  319,  335,  330,  336,  324,
      324,  331,  319,  319,  332,  319,  319,  325,  325,  100,
      333,  319,  319,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  337,  319,  319,
      319,  329,  329,  335,  330,  330,  336,  319,  326,  326,

      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  338,  319,  319,  319,  319,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  339,  319,  319,  319,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  319,  319,  319,  319,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  319,  319,  319,  326,
      326,  326,  326,  326,  326,  326,  326,  319,  319,  326,
      326,  326,  326,  326,  326,  326,  319,  326,  326,  326,

      326,  326,  326,  319,  326,  326,  326,  319,  326,  326,
      319,  326,  326,  319,  326,  319,  326,  326,    0,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319
    } ;

static const flex_int16_t yy_nxt[755] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   28,
       28,   29,   30,   31,   32,   33,   34,   35,   35,   35,
       35,   36,   10,   37,   38,   35,   39,   40,   41,   42,
       43,   44,   45,   35,   46,   35,   47,   35,   48,   35,
       49,   50,   51,   52,   53,   35,   54,   35,   35,   55,
       56,   57,   58,   60,   60,   62,   65,   65,   62,   66,
       66,   63,   61,   61,   63,   69,   71,   77,   69,   83,
       78,   79,   85,   87,  103,  104,  101,   84,   89,   89,
       89,   89,  101,   88,   86,  101,   73,   80,  164,   91,

      106,  107,   82,   70,   74,   92,  101,  101,  110,  116,
       93,  117,  101,  263,   75,  115,  120,   95,   94,   96,
       97,   97,   96,   90,   95,  111,   96,   96,   96,   96,
       99,  101,  100,  101,  101,  112,  101,  118,  101,   99,
      101,  101,  113,  101,  134,  121,  123,  101,  114,  101,
      119,  101,  122,  101,  101,  126,  137,  124,  132,  127,
      129,   69,  125,  146,  146,  133,   69,   81,  130,  131,
       68,  101,  139,  151,  146,  128,   73,  101,  319,  319,
      135,  159,  159,  168,   74,  165,  101,  245,  149,   70,
       82,  147,  223,  172,   75,  101,  101,  152,  149,  101,

      140,   89,   89,   89,   89,  156,  156,  156,  156,   95,
      101,   96,   96,   96,   96,   95,  178,  158,  158,  158,
       96,  101,  101,  101,  166,  153,  101,  101,  101,  157,
      167,  170,  101,  319,  101,  160,  160,  160,  160,  169,
      101,  171,  173,  101,  101,  160,  160,  101,  177,  101,
      101,  101,  188,  174,  160,  160,  160,  160,  160,  160,
      101,  181,  175,  176,  179,  180,  184,  101,  101,  101,
       69,   69,  182,   68,  185,  139,  146,  148,   69,  183,
      186,  187,  145,  196,  193,   69,   81,  156,  156,  156,
      156,   95,  151,  158,  158,  158,   96,  101,   70,   70,

      101,  200,   82,  140,  147,  101,  101,  197,  101,   82,
      101,  157,  194,  101,  201,  319,  152,  159,  159,  101,
      199,  202,  101,  205,  203,  101,  101,  204,  101,  101,
      206,  101,  101,  101,  101,  101,  209,  210,  101,  211,
      101,  101,  207,  213,  101,  212,  208,  215,  101,  218,
      101,  101,  101,  146,  146,  146,  219,  214,  220,  146,
      145,  216,  193,  148,  217,  101,  222,  101,  101,  196,
      101,  101,  221,  101,  229,  101,  101,  234,  228,  149,
      230,  147,  147,  149,  233,  101,  101,  232,  101,  235,
      194,  237,  231,  197,  236,  101,  101,  101,  101,  101,

      101,  239,  241,  101,  101,  238,  242,  101,  244,  101,
      101,  101,  101,  101,  101,  253,  101,  240,  101,  255,
      243,  249,  256,  251,  252,  250,  101,  258,  257,  259,
      101,  101,  101,  260,  101,  269,  254,  101,  101,  101,
      101,  101,  261,  262,  101,  268,  272,  101,  101,  267,
      271,  101,  101,  101,  283,  101,  273,  101,  270,  101,
      274,  282,  276,  275,  280,  285,  284,  101,  101,  287,
      281,  101,  101,  101,  101,  286,  293,  101,  101,  291,
      101,  294,  101,  101,  290,  292,  295,  299,  101,  301,
      101,  101,  296,  101,  303,  101,  300,  306,  305,  298,

      101,  101,  101,  101,  101,  101,  101,  302,  310,  312,
      141,  101,  315,  318,  313,  309,  307,  316,  101,  314,
      311,  317,   59,   59,   59,   59,   59,   59,   59,   59,
       64,   64,   64,   64,   64,   64,   64,   64,   68,   68,
       68,   68,   68,   68,   68,   68,   72,   72,  101,  308,
       72,   81,   81,   81,   81,   81,   81,   81,   81,   98,
      101,   98,   98,   98,   98,  108,  108,  108,  108,  138,
      138,  138,  138,  138,  138,  138,  138,  145,  145,  145,
      145,  145,  145,  145,  145,  148,  148,  148,  148,  148,
      148,  148,  148,  150,  150,  150,  150,  150,  150,  150,

      150,  155,  101,  155,  155,  155,  155,  155,  155,  161,
      161,  101,  161,  192,  192,  192,  192,  192,  192,  192,
      192,  195,  195,  195,  195,  195,  195,  195,  195,  304,
      101,  297,  101,  101,  289,  288,  101,  101,  279,  278,
      277,  101,  101,  101,  101,  266,  265,  264,  101,  101,
      101,  101,  248,  247,  246,  101,  101,  101,  101,  101,
      101,  101,  227,  226,  225,  224,  101,  198,  191,  190,
      189,  101,  101,  101,  163,  162,  154,  144,  143,  142,
      137,   84,  136,  109,  101,  105,  102,   76,   67,  319,
        9,  319,  319,  319,  319,  319,  319,  319,  319,  319,

      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319
    } ;

static const flex_int16_t yy_chk[755] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    4,    5,    7,    8,    6,    7,
        8,    5,    3,    4,    6,   14,   15,   17,   18,   21,
       17,   17,   22,   24,   31,   31,  110,   21,   25,   25,
       25,   25,   39,   24,   22,   43,   15,   17,  110,   26,

       33,   33,   18,   14,   15,   26,   40,   42,   39,   43,
       26,   43,   45,  339,   15,   42,   45,   27,   26,   27,
       27,   27,   27,   25,   28,   40,   28,   28,   28,   28,
       27,   41,   27,   44,   27,   41,   46,   44,   47,   27,
       48,   28,   41,   49,   56,   46,   47,   50,   41,   52,
       44,   51,   46,   53,   54,   50,   62,   48,   54,   51,
       52,   68,   49,   77,   79,   54,   81,   82,   52,   53,
       70,  113,   70,   82,  148,   51,   62,  111,   98,   99,
       56,   99,   99,  113,   62,  111,  117,  338,   79,   68,
       81,   77,  337,  117,   62,   98,   99,   82,  148,  125,

       70,   89,   89,   89,   89,   95,   95,   95,   95,   96,
      112,   96,   96,   96,   96,   97,  125,   97,   97,   97,
       97,  116,  115,  114,  112,   89,   96,  124,  118,   95,
      112,  115,   97,  100,  119,  100,  100,  100,  100,  114,
      123,  116,  118,  126,  130,  100,  100,  120,  124,  128,
      100,  127,  334,  119,  100,  100,  100,  100,  100,  100,
      129,  128,  120,  123,  126,  127,  130,  131,  132,  133,
      138,  139,  129,  140,  131,  140,  145,  149,  150,  129,
      132,  133,  147,  149,  147,  151,  152,  156,  156,  156,
      156,  158,  152,  158,  158,  158,  158,  165,  138,  139,

      166,  165,  150,  140,  145,  164,  169,  149,  158,  151,
      168,  156,  147,  167,  166,  159,  152,  159,  159,  170,
      164,  167,  171,  170,  168,  172,  173,  169,  174,  175,
      171,  176,  159,  177,  178,  179,  174,  175,  180,  176,
      181,  183,  172,  178,  182,  177,  173,  180,  184,  183,
      185,  186,  187,  192,  193,  195,  184,  179,  185,  196,
      194,  181,  194,  197,  182,  200,  187,  203,  204,  197,
      205,  207,  186,  209,  203,  211,  208,  209,  200,  195,
      204,  192,  193,  196,  208,  212,  214,  207,  213,  211,
      194,  213,  205,  197,  212,  216,  217,  220,  218,  221,

      222,  216,  218,  228,  229,  214,  220,  230,  222,  234,
      231,  236,  238,  251,  237,  234,  239,  217,  240,  237,
      221,  228,  237,  230,  231,  229,  241,  239,  238,  240,
      242,  243,  249,  241,  250,  251,  236,  252,  255,  253,
      256,  259,  242,  243,  272,  250,  255,  261,  262,  249,
      253,  268,  267,  269,  272,  276,  256,  274,  252,  273,
      259,  269,  262,  261,  267,  274,  273,  275,  280,  276,
      268,  281,  285,  283,  286,  275,  285,  287,  290,  281,
      292,  286,  293,  291,  280,  283,  287,  291,  295,  293,
      296,  299,  287,  302,  296,  303,  292,  302,  299,  290,

      306,  309,  307,  310,  312,  315,  317,  295,  307,  309,
      328,  318,  312,  317,  310,  306,  303,  314,  313,  311,
      308,  315,  320,  320,  320,  320,  320,  320,  320,  320,
      321,  321,  321,  321,  321,  321,  321,  321,  322,  322,
      322,  322,  322,  322,  322,  322,  323,  323,  305,  304,
      323,  324,  324,  324,  324,  324,  324,  324,  324,  325,
      301,  325,  325,  325,  325,  326,  326,  326,  326,  327,
      327,  327,  327,  327,  327,  327,  327,  329,  329,  329,
      329,  329,  329,  329,  329,  330,  330,  330,  330,  330,
      330,  330,  330,  331,  331,  331,  331,  331,  331,  331,

      331,  332,  300,  332,  332,  332,  332,  332,  332,  333,
      333,  298,  333,  335,  335,  335,  335,  335,  335,  335,
      335,  336,  336,  336,  336,  336,  336,  336,  336,  297,
      294,  289,  284,  282,  279,  277,  271,  270,  266,  265,
      264,  260,  258,  257,  254,  248,  247,  246,  244,  235,
      233,  232,  226,  225,  224,  219,  215,  210,  206,  202,
      201,  199,  198,  191,  190,  189,  161,  154,  144,  143,
      142,  122,  121,  108,  107,  103,   90,   75,   74,   73,
       66,   63,   61,   38,   35,   32,   29,   16,   13,    9,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,

      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "lexer.lpp"
/* Copyright 2021 xensik. All rights reserved.
//
// Use of this source code is governed by a GNU GPLv3 license
// that can be found in the LICENSE file.
*/
#define YY_NO_INPUT 1
#define YY_NO_UNISTD_H 1

#line 23 "lexer.lpp"
#define YY_USER_ACTION  loc.columns(yyleng);
#line 922 "lexer.cpp"

/*
    this is an inclusive start condition, so rules not explicitly specifying "DEVBLOCK_ON_STATE" will also match
    http://dinosaur.compilertools.net/flex/flex_11.html
*/

#line 929 "lexer.cpp"

#define INITIAL 0
#define COMMENT_BLOCK_STATE 1
#define DEVBLOCK_ON_STATE 2
#define DEVBLOCK_OFF_STATE 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    }; /* end struct yyguts_t */

static int yy_init_globals ( yyscan_t yyscanner );

int yylex_init (yyscan_t* scanner);

int yylex_init_extra ( YY_EXTRA_TYPE user_defined, yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( yyscan_t yyscanner );

int yyget_debug ( yyscan_t yyscanner );

void yyset_debug ( int debug_flag , yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra ( yyscan_t yyscanner );

void yyset_extra ( YY_EXTRA_TYPE user_defined , yyscan_t yyscanner );

FILE *yyget_in ( yyscan_t yyscanner );

void yyset_in  ( FILE * _in_str , yyscan_t yyscanner );

FILE *yyget_out ( yyscan_t yyscanner );

void yyset_out  ( FILE * _out_str , yyscan_t yyscanner );

			int yyget_leng ( yyscan_t yyscanner );

char *yyget_text ( yyscan_t yyscanner );

int yyget_lineno ( yyscan_t yyscanner );

void yyset_lineno ( int _line_number , yyscan_t yyscanner );

int yyget_column  ( yyscan_t yyscanner );

void yyset_column ( int _column_no , yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( yyscan_t yyscanner );
#else
extern int yywrap ( yyscan_t yyscanner );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int , yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * , yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( yyscan_t yyscanner );
#else
static int input ( yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (yyscan_t yyscanner);

#define YY_DECL int yylex (yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
		}

		yy_load_buffer_state( yyscanner );
		}

	{
#line 45 "lexer.lpp"



#line 49 "lexer.lpp"
    loc.step();


#line 1198 "lexer.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 320 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 319 );
		yy_cp = yyg->yy_last_accepting_cpos;
		yy_current_state = yyg->yy_last_accepting_state;

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 52 "lexer.lpp"
{ loc.step(); }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 54 "lexer.lpp"
{ loc.lines(yyleng); loc.step(); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 56 "lexer.lpp"

	YY_BREAK
case 4:
YY_RULE_SETUP
#line 58 "lexer.lpp"
{ BEGIN(COMMENT_BLOCK_STATE); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 59 "lexer.lpp"

	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 60 "lexer.lpp"
{ loc.lines(yyleng); loc.step(); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 61 "lexer.lpp"
{ BEGIN(INITIAL); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 63 "lexer.lpp"
{ BEGIN(comp_mode == xsk::gsc::compilation_mode::dev ? DEVBLOCK_ON_STATE : DEVBLOCK_OFF_STATE); }
	YY_BREAK
/* ignore everything if we're in devblock-off state */
case 9:
YY_RULE_SETUP
#line 65 "lexer.lpp"

	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 66 "lexer.lpp"
{ loc.lines(yyleng); loc.step(); }
	YY_BREAK
/* always exit devblock state when seeing #/ */
case 11:
YY_RULE_SETUP
#line 68 "lexer.lpp"
{ BEGIN(INITIAL); }
	YY_BREAK
/* for better errors */
case 12:
YY_RULE_SETUP
#line 71 "lexer.lpp"
{ throw iw5::parser::syntax_error(loc, "unmatched multiline comment end ('*/')"); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 72 "lexer.lpp"
{ throw iw5::parser::syntax_error(loc, "unmatched devblock end ('#/')"); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 74 "lexer.lpp"
{ return iw5::parser::make_BREAKPOINT(loc); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 75 "lexer.lpp"
{ return iw5::parser::make_PROFBEGIN(loc); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 76 "lexer.lpp"
{ return iw5::parser::make_PROFEND(loc); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 77 "lexer.lpp"
{ return iw5::parser::make_INCLUDE(loc); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 78 "lexer.lpp"
{ return iw5::parser::make_USINGTREE(loc); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 79 "lexer.lpp"
{ return iw5::parser::make_ANIMTREE(loc); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 80 "lexer.lpp"
{ return iw5::parser::make_ENDON(loc); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 81 "lexer.lpp"
{ return iw5::parser::make_NOTIFY(loc); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 82 "lexer.lpp"
{ return iw5::parser::make_WAIT(loc); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 83 "lexer.lpp"
{ return iw5::parser::make_WAITTILL(loc); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 84 "lexer.lpp"
{ return iw5::parser::make_WAITTILLMATCH(loc); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 85 "lexer.lpp"
{ return iw5::parser::make_WAITTILLFRAMEEND(loc); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 86 "lexer.lpp"
{ return iw5::parser::make_IF(loc); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 87 "lexer.lpp"
{ return iw5::parser::make_ELSE(loc); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 88 "lexer.lpp"
{ return iw5::parser::make_WHILE(loc); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 89 "lexer.lpp"
{ return iw5::parser::make_FOR(loc); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 90 "lexer.lpp"
{ return iw5::parser::make_FOREACH(loc); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 91 "lexer.lpp"
{ return iw5::parser::make_IN(loc); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 92 "lexer.lpp"
{ return iw5::parser::make_SWITCH(loc); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 93 "lexer.lpp"
{ return iw5::parser::make_CASE(loc); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 94 "lexer.lpp"
{ return iw5::parser::make_DEFAULT(loc); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 95 "lexer.lpp"
{ return iw5::parser::make_BREAK(loc); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 96 "lexer.lpp"
{ return iw5::parser::make_CONTINUE(loc); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 97 "lexer.lpp"
{ return iw5::parser::make_RETURN(loc); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 98 "lexer.lpp"
{ return iw5::parser::make_THREAD(loc); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 99 "lexer.lpp"
{ return iw5::parser::make_CHILDTHREAD(loc); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 100 "lexer.lpp"
{ return iw5::parser::make_THISTHREAD(loc); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 101 "lexer.lpp"
{ return iw5::parser::make_CALL(loc); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 102 "lexer.lpp"
{ return iw5::parser::make_TRUE(loc); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 103 "lexer.lpp"
{ return iw5::parser::make_FALSE(loc); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 104 "lexer.lpp"
{ return iw5::parser::make_UNDEFINED(loc); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 105 "lexer.lpp"
{ return iw5::parser::make_SIZE(loc); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 106 "lexer.lpp"
{ return iw5::parser::make_GAME(loc); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 107 "lexer.lpp"
{ return iw5::parser::make_SELF(loc); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 108 "lexer.lpp"
{ return iw5::parser::make_ANIM(loc); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 109 "lexer.lpp"
{ return iw5::parser::make_LEVEL(loc); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 110 "lexer.lpp"
{ return iw5::parser::make_LPAREN(loc); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 111 "lexer.lpp"
{ return iw5::parser::make_RPAREN(loc); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 112 "lexer.lpp"
{ return iw5::parser::make_LBRACE(loc); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 113 "lexer.lpp"
{ return iw5::parser::make_RBRACE(loc); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 114 "lexer.lpp"
{ return iw5::parser::make_LBRACKET(loc); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 115 "lexer.lpp"
{ return iw5::parser::make_RBRACKET(loc); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 116 "lexer.lpp"
{ return iw5::parser::make_COMMA(loc); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 117 "lexer.lpp"
{ return iw5::parser::make_DOT(loc); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 118 "lexer.lpp"
{ return iw5::parser::make_DOUBLECOLON(loc); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 119 "lexer.lpp"
{ return iw5::parser::make_COLON(loc); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 120 "lexer.lpp"
{ return iw5::parser::make_SEMICOLON(loc); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 121 "lexer.lpp"
{ return iw5::parser::make_QMARK(loc); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 122 "lexer.lpp"
{ return iw5::parser::make_INCREMENT(loc); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 123 "lexer.lpp"
{ return iw5::parser::make_DECREMENT(loc); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 124 "lexer.lpp"
{ return iw5::parser::make_ASSIGN_LSHIFT(loc); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 125 "lexer.lpp"
{ return iw5::parser::make_ASSIGN_RSHIFT(loc); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 126 "lexer.lpp"
{ return iw5::parser::make_LSHIFT(loc); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 127 "lexer.lpp"
{ return iw5::parser::make_RSHIFT(loc); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 128 "lexer.lpp"
{ return iw5::parser::make_OR(loc); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 129 "lexer.lpp"
{ return iw5::parser::make_AND(loc); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 130 "lexer.lpp"
{ return iw5::parser::make_EQUALITY(loc); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 131 "lexer.lpp"
{ return iw5::parser::make_INEQUALITY(loc); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 132 "lexer.lpp"
{ return iw5::parser::make_LESS_EQUAL(loc); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 133 "lexer.lpp"
{ return iw5::parser::make_GREATER_EQUAL(loc); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 134 "lexer.lpp"
{ return iw5::parser::make_LESS(loc); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 135 "lexer.lpp"
{ return iw5::parser::make_GREATER(loc); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 136 "lexer.lpp"
{ return iw5::parser::make_ASSIGN_ADD(loc); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 137 "lexer.lpp"
{ return iw5::parser::make_ASSIGN_SUB(loc); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 138 "lexer.lpp"
{ return iw5::parser::make_ASSIGN_MULT(loc); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 139 "lexer.lpp"
{ return iw5::parser::make_ASSIGN_DIV(loc); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 140 "lexer.lpp"
{ return iw5::parser::make_ASSIGN_MOD(loc); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 141 "lexer.lpp"
{ return iw5::parser::make_ASSIGN_BITWISE_OR(loc); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 142 "lexer.lpp"
{ return iw5::parser::make_ASSIGN_BITWISE_AND(loc); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 143 "lexer.lpp"
{ return iw5::parser::make_ASSIGN_BITWISE_EXOR(loc); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 144 "lexer.lpp"
{ return iw5::parser::make_ASSIGN(loc); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 145 "lexer.lpp"
{ return iw5::parser::make_ADD(loc); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 146 "lexer.lpp"
{ return iw5::parser::make_SUB(loc); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 147 "lexer.lpp"
{ return iw5::parser::make_MULT(loc); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 148 "lexer.lpp"
{ return iw5::parser::make_DIV(loc); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 149 "lexer.lpp"
{ return iw5::parser::make_MOD(loc); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 150 "lexer.lpp"
{ return iw5::parser::make_NOT(loc); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 151 "lexer.lpp"
{ return iw5::parser::make_COMPLEMENT(loc); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 152 "lexer.lpp"
{ return iw5::parser::make_BITWISE_OR(loc); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 153 "lexer.lpp"
{ return iw5::parser::make_BITWISE_AND(loc); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 154 "lexer.lpp"
{ return iw5::parser::make_BITWISE_EXOR(loc); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 155 "lexer.lpp"
{ return iw5::parser::make_FILE(utils::string::fordslash(yytext), loc); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 156 "lexer.lpp"
{ return iw5::parser::make_NAME((std::string(yytext, 3) == "_ID") ? std::string(yytext) : utils::string::to_lower(yytext), loc); }
	YY_BREAK
case 97:
/* rule 97 can match eol */
YY_RULE_SETUP
#line 157 "lexer.lpp"
{ return iw5::parser::make_ISTRING(std::string(yytext).substr(1), loc); }
	YY_BREAK
case 98:
/* rule 98 can match eol */
YY_RULE_SETUP
#line 158 "lexer.lpp"
{ return iw5::parser::make_STRING(std::string(yytext), loc); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 159 "lexer.lpp"
{ return iw5::parser::make_COLOR(std::string(yytext).substr(1), loc); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 160 "lexer.lpp"
{ return iw5::parser::make_FLOAT(std::string(yytext), loc); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 161 "lexer.lpp"
{ return iw5::parser::make_INT_OCT(utils::string::oct_to_dec(yytext), loc); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 162 "lexer.lpp"
{ return iw5::parser::make_INT_BIN(utils::string::bin_to_dec(yytext), loc); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 163 "lexer.lpp"
{ return iw5::parser::make_INT_HEX(utils::string::hex_to_dec(yytext), loc); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 164 "lexer.lpp"
{ return iw5::parser::make_INT_DEC(std::string(yytext), loc); }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT_BLOCK_STATE):
case YY_STATE_EOF(DEVBLOCK_ON_STATE):
case YY_STATE_EOF(DEVBLOCK_OFF_STATE):
#line 165 "lexer.lpp"
{ return iw5::parser::make_IW5EOF(loc); }
	YY_BREAK
case 105:
/* rule 105 can match eol */
YY_RULE_SETUP
#line 166 "lexer.lpp"
{ throw iw5::parser::syntax_error(loc, "bad token: '" + std::string(yytext) + "'"); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 168 "lexer.lpp"
ECHO;
	YY_BREAK
#line 1797 "lexer.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_last_accepting_cpos;
				yy_current_state = yyg->yy_last_accepting_state;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap( yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  , yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size , yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 320 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	char *yy_cp = yyg->yy_c_buf_p;

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 320 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 319);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr);
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin , yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file , yyscanner);
	yy_load_buffer_state( yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file , yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf , yyscanner );

	yyfree( (void *) b , yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer( b , yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER , yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b , yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) , yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n , yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n , yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param _line_number line number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  _line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_lineno called with no buffer" );
    
    yylineno = _line_number;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_column called with no buffer" );
    
    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

void yyset_out (FILE *  _out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = _out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  _bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = _bdebug ;
}

/* Accessor methods for yylval and yylloc */

/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */
int yylex_init(yyscan_t* ptr_yy_globals)
{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */
int yylex_init_extra( YY_EXTRA_TYPE yy_user_defined, yyscan_t* ptr_yy_globals )
{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    yyset_extra (yy_user_defined, *ptr_yy_globals);

    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = NULL;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = NULL;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER , yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack , yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree( yyg->yy_start_stack , yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 168 "lexer.lpp"


