// Copyright 2020 xensik. All rights reserved.
//
// Use of this source code is governed by a GNU GPLv3 license
// that can be found in the LICENSE file.

#include "IW6.hpp"

namespace IW6
{

auto resolver::opcode_id(const std::string& name) -> opcode
{
	const auto itr = opcode_map.find(name);

	if (itr != opcode_map.end())
	{
		return itr->second;
	}

	LOG_ERROR("Couldn't resolve opcode id for name '%s'!", name.data());
	return opcode::OP_Count;
}

auto resolver::opcode_name(opcode id) -> std::string
{
	for (auto& opcode : opcode_map)
	{
		if (opcode.second == id)
		{
			return opcode.first;
		}
	}

	LOG_ERROR("Couldn't resolve opcode name for id '0x%hhX'!", id);
	return "";
}

auto resolver::builtin_func_id(const std::string& name) -> std::uint16_t
{
	for (auto& field : builtin_function_map)
	{
		if (utils::string::to_lower(field.second) == name)
		{
			return field.first;
		}
	}

	LOG_DEBUG("Couldn't resolve builtin function id for name '%s'!", name.data());
	return 0xFFFF;
}

auto resolver::builtin_func_name(std::uint16_t id) -> std::string
{
	const auto itr = builtin_function_map.find(id);

	if (itr != builtin_function_map.end())
	{
		return itr->second;
	}

	LOG_DEBUG("Couldn't resolve builtin function name for id '%i'!", id);
	return utils::string::va("id#%i", id);
}

auto resolver::builtin_method_id(const std::string& name) -> std::uint16_t
{
	for (auto& field : builtin_method_map)
	{
		if (utils::string::to_lower(field.second) == name)
		{
			return field.first;
		}
	}

	LOG_DEBUG("Couldn't resolve builtin method id for name '%s'!", name.data());
	return 0xFFFF;
}

auto resolver::builtin_method_name(std::uint16_t id) -> std::string
{
	const auto itr = builtin_method_map.find(id);

	if (itr != builtin_method_map.end())
	{
		return itr->second;
	}

	LOG_DEBUG("Couldn't resolve builtin method name for id '%i'!", id);
	return utils::string::va("id#%i", id);
}

auto resolver::file_id(const std::string& name) -> std::uint16_t
{
	const auto itr = file_map.find(name);

	if (itr != file_map.end())
	{
		return itr->second;
	}

	LOG_DEBUG("Couldn't resolve file id for name '%s'!", name.data());
	return 0;
}

auto resolver::file_name(std::uint16_t id) -> std::string
{
	for (auto& file : file_map)
	{
		if (file.second == id)
		{
			return file.first;
		}
	}

	LOG_DEBUG("Couldn't resolve file name for id '%i'!", id);
	return utils::string::va("id#%i", id);
}

auto resolver::token_id(const std::string& name) -> std::uint16_t
{
	const auto itr = token_map.find(name);

	if (itr != token_map.end())
	{
		return itr->second;
	}

	LOG_DEBUG("Couldn't resolve token id for name '%s'!", name.data());
	return 0;
}

auto resolver::token_name(std::uint16_t id) -> std::string
{
	for (auto& func : token_map)
	{
		if (func.second == id)
		{
			return func.first;
		}
	}

	//LOG_DEBUG("Couldn't resolve token name for id '%i'!", id);
	return utils::string::va("id#%i", id);
}

std::unordered_map<std::string, opcode> resolver::opcode_map
{
	{ "end", opcode::OP_End },
	{ "retn", opcode::OP_Return },
	{ "get_byte", opcode::OP_GetByte },
	{ "get_neg_byte", opcode::OP_GetNegByte },
	{ "get_ushort", opcode::OP_GetUnsignedShort },
	{ "get_neg_ushort", opcode::OP_GetNegUnsignedShort },
	{ "get_int", opcode::OP_GetInteger },
	{ "get_builtin_func", opcode::OP_GetBuiltinFunction },
	{ "get_builtin_method", opcode::OP_GetBuiltinMethod },
	{ "get_float", opcode::OP_GetFloat },
	{ "get_string", opcode::OP_GetString },
	{ "get_undefined", opcode::OP_GetUndefined },
	{ "get_zero", opcode::OP_GetZero },
	{ "waittill_frame_end", opcode::OP_waittillFrameEnd },
	{ "create_local_variable", opcode::OP_CreateLocalVariable },
	{ "remove_local_variables", opcode::OP_RemoveLocalVariables },
	{ "eval_local_variable_cached0", opcode::OP_EvalLocalVariableCached0 },
	{ "eval_local_variable_cached1", opcode::OP_EvalLocalVariableCached1 },
	{ "eval_local_variable_cached2", opcode::OP_EvalLocalVariableCached2 },
	{ "eval_local_variable_cached3", opcode::OP_EvalLocalVariableCached3 },
	{ "eval_local_variable_cached4", opcode::OP_EvalLocalVariableCached4 },
	{ "eval_local_variable_cached5", opcode::OP_EvalLocalVariableCached5 },
	{ "eval_local_variable_cached", opcode::OP_EvalLocalVariableCached },
	{ "eval_local_array_cached", opcode::OP_EvalLocalArrayCached },
	{ "eval_array", opcode::OP_EvalArray },
	{ "eval_new_local_array_ref_cached0", opcode::OP_EvalNewLocalArrayRefCached0 },
	{ "eval_local_array_ref_cached0", opcode::OP_EvalLocalArrayRefCached0 },
	{ "eval_local_array_ref_cached", opcode::OP_EvalLocalArrayRefCached },
	{ "eval_array_ref", opcode::OP_EvalArrayRef },
	{ "clear_array", opcode::OP_ClearArray },
	{ "empty_array", opcode::OP_EmptyArray },
	{ "add_array", opcode::OP_AddArray },
	{ "pre_script_call", opcode::OP_PreScriptCall },
	{ "script_local_func_call2", opcode::OP_ScriptLocalFunctionCall2 },
	{ "script_local_func_call", opcode::OP_ScriptLocalFunctionCall },
	{ "script_local_method_call", opcode::OP_ScriptLocalMethodCall },
	{ "script_local_thread_call", opcode::OP_ScriptLocalThreadCall },
	{ "script_local_child_thread_call", opcode::OP_ScriptLocalChildThreadCall },
	{ "script_local_method_thread_call", opcode::OP_ScriptLocalMethodThreadCall },
	{ "script_local_method_child_thread_call", opcode::OP_ScriptLocalMethodChildThreadCall },
	{ "script_far_func_call2", opcode::OP_ScriptFarFunctionCall2 },
	{ "script_far_func_call", opcode::OP_ScriptFarFunctionCall },
	{ "script_far_method_call", opcode::OP_ScriptFarMethodCall },
	{ "script_far_thread_call", opcode::OP_ScriptFarThreadCall },
	{ "script_far_child_thread_call", opcode::OP_ScriptFarChildThreadCall },
	{ "script_far_method_thread_call", opcode::OP_ScriptFarMethodThreadCall },
	{ "script_far_method_child_thread_call", opcode::OP_ScriptFarMethodChildThreadCall },
	{ "script_func_call_pointer", opcode::OP_ScriptFunctionCallPointer },
	{ "script_method_call_pointer", opcode::OP_ScriptMethodCallPointer },
	{ "script_thread_call_pointer", opcode::OP_ScriptThreadCallPointer },
	{ "script_method_thread_call_pointer", opcode::OP_ScriptMethodThreadCallPointer },
	{ "script_method_child_thread_call_pointer", opcode::OP_ScriptMethodChildThreadCallPointer },
	{ "call_builtin_pointer", opcode::OP_CallBuiltinPointer },
	{ "call_builtin_method_pointer", opcode::OP_CallBuiltinMethodPointer },
	{ "get_istring", opcode::OP_GetIString },
	{ "get_vector", opcode::OP_GetVector },
	{ "get_level_obj", opcode::OP_GetLevelObject },
	{ "get_anim_obj", opcode::OP_GetAnimObject },
	{ "get_self", opcode::OP_GetSelf },
	{ "get_this_thread", opcode::OP_GetThisthread },
	{ "get_level", opcode::OP_GetLevel },
	{ "get_game", opcode::OP_GetGame },
	{ "get_anim", opcode::OP_GetAnim },
	{ "get_animation", opcode::OP_GetAnimation },
	{ "get_game_ref", opcode::OP_GetGameRef },
	{ "increment", opcode::OP_inc },
	{ "decrement", opcode::OP_dec },
	{ "bit_or", opcode::OP_bit_or },
	{ "jump_expr<false>", opcode::OP_JumpOnFalseExpr },
	{ "bit_ex_or", opcode::OP_bit_ex_or },
	{ "bit_and", opcode::OP_bit_and },
	{ "equality", opcode::OP_equality },
	{ "inequality", opcode::OP_inequality },
	{ "less", opcode::OP_less },
	{ "greater", opcode::OP_greater },
	{ "jump_expr<true>", opcode::OP_JumpOnTrueExpr },
	{ "less_equal", opcode::OP_less_equal },
	{ "jump_back", opcode::OP_jumpback },
	{ "waittillmatch2", opcode::OP_waittillmatch2 },
	{ "waittill", opcode::OP_waittill },
	{ "notify", opcode::OP_notify },
	{ "endon", opcode::OP_endon },
	{ "void_codepos", opcode::OP_voidCodepos },
	{ "switch", opcode::OP_switch },
	{ "endswitch", opcode::OP_endswitch },
	{ "vector", opcode::OP_vector },
	{ "jump<false>", opcode::OP_JumpOnFalse },
	{ "greater_equal", opcode::OP_greater_equal },
	{ "shift_left", opcode::OP_shift_left },
	{ "shift_right", opcode::OP_shift_right },
	{ "plus", opcode::OP_plus },
	{ "jump", opcode::OP_jump },
	{ "minus", opcode::OP_minus },
	{ "multiply", opcode::OP_multiply },
	{ "divide", opcode::OP_divide },
	{ "mod", opcode::OP_mod },
	{ "jump<true>", opcode::OP_JumpOnTrue },
	{ "size", opcode::OP_size },
	{ "waittillmatch", opcode::OP_waittillmatch },
	{ "get_local_func", opcode::OP_GetLocalFunction },
	{ "get_far_func", opcode::OP_GetFarFunction },
	{ "get_self_obj", opcode::OP_GetSelfObject },
	{ "eval_level_field_variable", opcode::OP_EvalLevelFieldVariable },
	{ "eval_anim_field_variable", opcode::OP_EvalAnimFieldVariable },
	{ "eval_self_field_variable", opcode::OP_EvalSelfFieldVariable },
	{ "eval_field_variable", opcode::OP_EvalFieldVariable },
	{ "eval_level_field_variable_ref", opcode::OP_EvalLevelFieldVariableRef },
	{ "eval_anim_field_variable_ref", opcode::OP_EvalAnimFieldVariableRef },
	{ "eval_self_field_variable_ref", opcode::OP_EvalSelfFieldVariableRef },
	{ "eval_field_variable_ref", opcode::OP_EvalFieldVariableRef },
	{ "clear_field_variable", opcode::OP_ClearFieldVariable },
	{ "safe_create_variable_field_cached", opcode::OP_SafeCreateVariableFieldCached },
	{ "safe_set_variable_field_cached0", opcode::OP_SafeSetVariableFieldCached0 },
	{ "safe_set_variable_field_cached", opcode::OP_SafeSetVariableFieldCached },
	{ "safe_set_waittill_variable_field_cached", opcode::OP_SafeSetWaittillVariableFieldCached },
	{ "get_animtree", opcode::OP_GetAnimTree },
	{ "clearparams", opcode::OP_clearparams },
	{ "checkclearparams", opcode::OP_checkclearparams },
	{ "eval_local_variable_ref_cached0", opcode::OP_EvalLocalVariableRefCached0 },
	{ "eval_new_local_variable_ref_cached0", opcode::OP_EvalNewLocalVariableRefCached0 },
	{ "eval_local_variable_ref_cached", opcode::OP_EvalLocalVariableRefCached},
	{ "set_level_field_variable_field", opcode::OP_SetLevelFieldVariableField },
	{ "set_variable_field", opcode::OP_SetVariableField },
	{ "clear_variable_field", opcode::OP_ClearVariableField },
	{ "set_anim_field_variable_field", opcode::OP_SetAnimFieldVariableField },
	{ "set_self_field_variable_field", opcode::OP_SetSelfFieldVariableField },
	{ "set_local_variable_field_cached0", opcode::OP_SetLocalVariableFieldCached0 },
	{ "set_new_local_variable_field_cached0", opcode::OP_SetNewLocalVariableFieldCached0 },
	{ "set_local_variable_field_cached", opcode::OP_SetLocalVariableFieldCached },
	{ "clear_local_variable_field_cached", opcode::OP_ClearLocalVariableFieldCached },
	{ "clear_local_variable_field_cached0", opcode::OP_ClearLocalVariableFieldCached0 },
	{ "call<0>", opcode::OP_CallBuiltin0 },
	{ "call<1>", opcode::OP_CallBuiltin1 },
	{ "call<2>", opcode::OP_CallBuiltin2 },
	{ "call<3>", opcode::OP_CallBuiltin3 },
	{ "call<4>", opcode::OP_CallBuiltin4 },
	{ "call<5>", opcode::OP_CallBuiltin5 },
	{ "call", opcode::OP_CallBuiltin },
	{ "method<0>", opcode::OP_CallBuiltinMethod0 },
	{ "method<1>", opcode::OP_CallBuiltinMethod1 },
	{ "method<2>", opcode::OP_CallBuiltinMethod2 },
	{ "method<3>", opcode::OP_CallBuiltinMethod3 },
	{ "method<4>", opcode::OP_CallBuiltinMethod4 },
	{ "method<5>", opcode::OP_CallBuiltinMethod5 },
	{ "method", opcode::OP_CallBuiltinMethod },
	{ "wait", opcode::OP_wait },
	{ "decrement_top", opcode::OP_DecTop },
	{ "cast_field_obj", opcode::OP_CastFieldObject },
	{ "eval_local_variable_obj_cached", opcode::OP_EvalLocalVariableObjectCached },
	{ "cast_bool", opcode::OP_CastBool },
	{ "bool_not", opcode::OP_BoolNot },
	{ "bool_complement", opcode::OP_BoolComplement },
};

std::unordered_map<std::uint16_t, std::string> resolver::builtin_function_map
{
	//------------------------------------------------------------------------
	// FUNCTION COMMON 272
	{ 0x010, "Print" },
	{ 0x011, "PrintLn" },
	{ 0x001, "PrecacheTurret" },
	{ 0x002, "GetWeaponArray" },
	{ 0x018, "SpawnTurret" },
	{ 0x019, "CanSpawnTurret" },
	{ 0x01A, "assertexCmd" },
	{ 0x02B, "assertexCmd" },
	{ 0x02C, "SetPathnodeField" },
	{ 0x02D, "IsDefined" },
	{ 0x02E, "IsValidMissile" },
	{ 0x02F, "IsString" },
	{ 0x0C5, "IsSentient" },
	{ 0x0C4, "GetIndexForLuiNCString" },
	{ 0x030, "SetOmnvar" },
	{ 0x031, "GetOmnvar" },
	{ 0x032, "SetDvar" },
	{ 0x033, "SetDynamicDvar" },
	{ 0x034, "SetDvarIfUninitialized" },
	{ 0x035, "SetDvar" },
	{ 0x036, "SetDvarIfUninitialized" },
	{ 0x037, "GetDvar" },
	{ 0x038, "GetDvarInt" },
	{ 0x039, "GetDvarFloat" },
	{ 0x03A, "GetDvarVector" },
	{ 0x03B, "GetTime" },
	{ 0x03C, "GetEntByNum" },
	{ 0x03D, "GetWeaponModel" },
	{ 0x059, "GetWeaponDisplayName" },
	{ 0x05A, "GetWeaponBaseName" },
	{ 0x05B, "GetWeaponAttachments" },
	{ 0x05C, "GetWeaponAttachmentDisplayNames" },
	{ 0x05D, "GetWeaponCamoName" },
	{ 0x05E, "GetWeaponReticleName" },
	{ 0x05F, "GetWeaponHideTags" },
	{ 0x060, "GetAnimLength" },
	{ 0x061, "AnimHasNotetrack" },
	{ 0x062, "GetNotetrackTimes" },
	{ 0x063, "Spawn" },
	{ 0x064, "Spawn" },
	{ 0x065, "SetPathnodeField" },
	{ 0x066, "BulletTrace" },
	{ 0x082, "BulletTracePassed" },
	{ 0x083, "SightTracePassed" },
	{ 0x084, "PhysicsTrace" },
	{ 0x085, "PlayerPhysicsTrace" },
	{ 0x086, "GetGroundPosition" },
	{ 0x087, "GetMoveDelta" },
	{ 0x088, "GetAngleDelta" },
	{ 0x211, "GetAngleDelta3D" },
	{ 0x089, "GetNorthYaw" },
	{ 0x0A4, "SetNorthYaw" },
	{ 0x0A5, "SetSlowMotion" },
	{ 0x0A6, "RandomInt" },
	{ 0x0A7, "RandomFloat" },
	{ 0x0A8, "RandomIntRange" },
	{ 0x0A9, "RandomFloatRange" },
	{ 0x0AA, "sin" },
	{ 0x0AB, "cos" },
	{ 0x0AC, "tan" },
	{ 0x0AD, "asin" },
	{ 0x0AE, "acos" },
	{ 0x0AF, "atan" },
	{ 0x0B0, "CastInt" },
	{ 0x0B1, "CastFloat" },
	{ 0x0B2, "abs" },
	{ 0x0B3, "min" },
	{ 0x0D5, "max" },
	{ 0x0D6, "floor" },
	{ 0x0D7, "ceil" },
	{ 0x0D8, "exp" },
	{ 0x0D9, "log" },
	{ 0x0DA, "sqrt" },
	{ 0x0DB, "squared" },
	{ 0x0DC, "clamp" },
	{ 0x1DE, "pow" },
	{ 0x0DD, "AngleClamp360" },
	{ 0x0DE, "AngleClamp180" },
	{ 0x0DF, "VectorFromLineToPoint" },
	{ 0x0E0, "PointOnSegmentNearestToPoint" },
	{ 0x21A, "IsPointInVolume" },
	{ 0x0E1, "Distance" },
	{ 0x0E2, "Distance2D" },
	{ 0x210, "Distance2DSquared" },
	{ 0x0E3, "DistanceSquared" },
	{ 0x0E4, "Length" },
	{ 0x0E5, "Length2D" },
	{ 0x0E6, "LengthSquared" },
	{ 0x0E7, "Length2DSquared" },
	{ 0x0E8, "Closer" },
	{ 0x0E9, "VectorDot" },
	{ 0x0EA, "VectorCross" },
	{ 0x107, "VectorNormalize" },
	{ 0x108, "VectorToAngles" },
	{ 0x109, "VectorToYaw" },
	{ 0x10A, "VectorLerp" },
	{ 0x0EB, "AxisToAngles" },
	{ 0x225, "AnglesToAxis" },
	{ 0x10B, "AnglesToUp" },
	{ 0x10C, "AnglesToRight" },
	{ 0x10D, "AnglesToForward" },
	{ 0x10E, "AnglesDelta" },
	{ 0x10F, "CombineAngles" },
	{ 0x110, "TransformMove" },
	{ 0x111, "RotateVector" },
	{ 0x112, "RotatePointAroundVector" },
	{ 0x22A, "InvertAngles" },
	{ 0x22B, "RotateVectorInverted" },
	{ 0x22C, "CalculateStartOrientation" },
	{ 0x113, "IsSubStr" },
	{ 0x114, "IsEndStr" },
	{ 0x115, "GetSubStr" },
	{ 0x116, "ToLower" },
	{ 0x117, "StrTok" },
	{ 0x118, "StrICmp" },
	{ 0x139, "AmbientStop" },
	{ 0x13A, "PrecacheModel" },
	{ 0x13B, "PrecacheShellShock" },
	{ 0x13C, "PrecacheItem" },
	{ 0x13D, "PrecacheMaterial" },
	{ 0x13E, "PrecacheString" },
	{ 0x13F, "PrecacheMenu" },
	{ 0x140, "PrecacheRumble" },
	{ 0x141, "PrecacheLocationSelector" },
	{ 0x142, "PrecacheLeaderboards" },
	{ 0x15C, "PrecacheHeadIcon" },
	{ 0x143, "LoadFX" },
	{ 0x144, "PlayFX" },
	{ 0x145, "PlayFXOnTag" },
	{ 0x146, "StopFXOnTag" },
	{ 0x147, "KillFXOnTag" },
	{ 0x148, "PlayLoopedFX" },
	{ 0x149, "SpawnFX" },
	{ 0x24B, "SpawnFXForClient" },
	{ 0x14A, "TriggerFX" },
	{ 0x14B, "PlayFXOnTagForClients" },
	{ 0x170, "PhysicsExplosionSphere" },
	{ 0x171, "PhysicsExplosionCylinder" },
	{ 0x172, "PhysicsRadiusJolt" },
	{ 0x173, "PhysicsRadiusJitter" },
	{ 0x174, "SetExponentialFog" },
	{ 0x222, "ClearFog" },
	{ 0x175, "IsExplosiveDamageMOD" },
	{ 0x176, "RadiusDamage" },
	{ 0x177, "SetPlayerIgnoreRadiusDamage" },
	{ 0x178, "GlassRadiusDamage" },
	{ 0x179, "Earthquake" },
	{ 0x17A, "GetNumParts" },
	{ 0x19C, "GetPartName" },
	{ 0x19D, "WeaponFireTime" },
	{ 0x19E, "WeaponClipSize" },
	{ 0x19F, "WeaponIsAuto" },
	{ 0x1A0, "WeaponIsSemiAuto" },
	{ 0x1A1, "WeaponIsBoltAction" },
	{ 0x1A2, "WeaponInheritsPerks" },
	{ 0x1A3, "WeaponBurstCount" },
	{ 0x1A4, "WeaponType" },
	{ 0x1A5, "WeaponClass" },
	{ 0x1D0, "WeaponInventoryType" },
	{ 0x1D1, "WeaponStartAmmo" },
	{ 0x1D2, "WeaponMaxAmmo" },
	{ 0x1D3, "WeaponAltWeaponName" },
	{ 0x1D4, "IsWeaponClipOnly" },
	{ 0x1D5, "IsWeaponDetonationTimed" },
	{ 0x1D6, "WeaponHasThermalScope" },
	{ 0x1D7, "VehPathCmd_GetNode" },
	{ 0x1D8, "VehPathCmd_GetNodeArray" },
	{ 0x1D9, "VehPathCmd_GetAllNodes" },
	{ 0x1DA, "VehicleScript_GetActiveCount" },
	{ 0x1DB, "VehicleScript_Precache" },
	{ 0x1DC, "VehicleScript_Spawn" },
	{ 0x1DD, "VehicleScript_GetArray" },
	{ 0x1B3, "VehicleScript_GetSpawnerArray" },
	{ 0x1B4, "PlayRumbleOnPosition" },
	{ 0x1B5, "PlayRumbleLoopOnPosition" },
	{ 0x1B6, "StopAllRumbles" },
	{ 0x1B7, "SoundExists" },
	{ 0x1BE, "SetMiniMap" },
	{ 0x1BF, "SetThermalBodyMaterial" },
	{ 0x249, "SetGlareGrimeMaterial" },
	{ 0x1C0, "GetArrayKeys" },
	{ 0x1C1, "GetFirstArrayKey" },
	{ 0x1A6, "GetNextArrayKey" },
	{ 0x1A7, "SortByDistance" },
	{ 0x1A8, "TableLookup" },
	{ 0x1A9, "TableLookupIStringByRow" },
	{ 0x1AA, "TableLookupIString" },
	{ 0x1AB, "TableLookupIStringByRow" },
	{ 0x1AC, "TableLookupRowNum" },
	{ 0x1AD, "TableExists" },
	{ 0x220, "LookupSoundLength" },
	{ 0x1AE, "GetMissileOwner" },
	{ 0x1AF, "MagicBullet" },
	{ 0x1B0, "GetWeaponFlashTagname" },
	{ 0x1B1, "AveragePoint" },
	{ 0x1B2, "AverageNormal" },
	{ 0x1C2, "GetGlass" },
	{ 0x1C3, "GetGlassArray" },
	{ 0x1C4, "GetGlassOrigin" },
	{ 0x1C5, "IsGlassDestroyed" },
	{ 0x1C6, "DestroyGlass" },
	{ 0x1C7, "DeleteGlass" },
	{ 0x1C8, "IsHairRunning" },
	{ 0x1C9, "GetEntChannelName" },
	{ 0x01F, "BadPlace_Delete" },
	{ 0x020, "BadPlace_Cylinder" },
	{ 0x021, "BadPlace_Arc" },
	{ 0x022, "BadPlace_Brush" },
	{ 0x1FD, "BadPlace_Global" },
	{ 0x0BC, "GetClosestNodeInSight" },
	{ 0x1FF, "GetLinkedNodes" },
	{ 0x212, "ActivateClientExploder" },
	{ 0x213, "TrajectoryCalculateInitialVelocity" },
	{ 0x214, "TrajectoryCalculateMinimumVelocity" },
	{ 0x215, "TrajectoryCalculateExitAngle" },
	{ 0x216, "TrajectoryEstimateDesiredInAirTime" },
	{ 0x217, "TrajectoryComputeDeltaHeightAtTime" },
	{ 0x218, "TrajectoryCanAttemptAccurateJump" },
	{ 0x0C2, "IsArray" },
	{ 0x21F, "GetEnemySquadData" },
	{ 0x25C, "GetEnemySquadDogType" },
	{ 0x24D, "GetSquadAssaultELO" },
	{ 0x221, "GetScriptableArray" },
	{ 0x200, "DisconnectNodePair" },
	{ 0x201, "ConnectNodePair" },
	{ 0x22D, "GetCSplineCount" },
	{ 0x22E, "GetCSplinePointCount" },
	{ 0x22F, "GetCSplineLength" },
	{ 0x230, "GetCSplinePointId" },
	{ 0x231, "GetCSplinePointLabel" },
	{ 0x232, "GetCSplinePointTension" },
	{ 0x233, "GetCSplinePointPosition" },
	{ 0x234, "GetCSplinePointCorridorDims" },
	{ 0x235, "GetCSplinePointTangent" },
	{ 0x236, "GetCSplinePointDistToNextPoint" },
	{ 0x237, "CalcCSplinePosition" },
	{ 0x238, "CalcCSplineTangent" },
	{ 0x239, "CalcCSplineCorridor" },
	{ 0x23A, "SetNoJIPScore" },
	{ 0x23B, "SetNoJIPTime" },
	{ 0x24E, "LoadLuiFile" },
	{ 0x254, "GetSquadAssaultSquadIndex" },
	{ 0x257, "IsHairRunning" },

	// ------------------------------------------------------------------------
	//FUNCTION OBJECTIVES 16
	{ 0x0CA, "Add" },
	{ 0x0CB, "Delete" },
	{ 0x0CC, "State" },
	{ 0x0CD, "Icon" },
	{ 0x0CE, "Position" },
	{ 0x0CF, "Current" },
	{ 0x07B, "OnEntity" },
	{ 0x07C, "OnEntityWithRotation" },
	{ 0x07D, "Team" },
	{ 0x07E, "Player" },
	{ 0x07F, "PlayerTeam" },
	{ 0x080, "PlayerEnemyTeam" },
	{ 0x081, "PlayerMask_HideFromAll" },
	{ 0x082, "PlayerMask_HideFrom" },
	{ 0x083, "PlayerMask_ShowToAll" },
	{ 0x084, "PlayerMask_ShowTo" },

	// ------------------------------------------------------------------------
	//FUNCTION SENTIENT 7
	{ 0x0FA, "CreateThreatBiasGroup" },
	{ 0x0FB, "ThreatBiasGroupExists" },
	{ 0x0FC, "GetThreatBias" },
	{ 0x0FD, "SetThreatBias" },
	{ 0x0FE, "SetThreatBiasAgainstAll" },
	{ 0x0FF, "SetIgnoreMeGroup" },
	{ 0x100, "IsEnemyTeam" },

	// ------------------------------------------------------------------------
	// FUNCTION 158
	{ 0x185, "iprintln" },
	{ 0x186, "iprintlnbold" },
	{ 0x188, "GetEnt" },
	{ 0x189, "GetEntArray" },
	{ 0x18A, "GetSpawnArray" },
	{ 0x06A, "GetStartOrigin" },
	{ 0x06B, "GetStartAngles" },
	{ 0x18B, "SpawnPlane" },
	{ 0x18C, "AddStruct" },
	{ 0x18D, "SpawnHelicopter" },
	{ 0x18E, "IsAlive" },
	{ 0x18F, "IsSpawner" },
	{ 0x190, "MissileCreateAttractorEnt" },
	{ 0x191, "MissileCreateAttractorOrigin" },
	{ 0x192, "MissileCreateRepulsorEnt" },
	{ 0x193, "MissileCreateRepulsorOrigin" },
	{ 0x194, "MissileDeleteAttractor" },
	{ 0x195, "PlaySoundAtPos" },
	{ 0x207, "PrecacheSound" },
	{ 0x196, "NewHudElem" },
	{ 0x197, "NewClientHudElem" },
	{ 0x198, "NewTeamHudElem" },
	{ 0x199, "ResetTimeout" },
	{ 0x19A, "IsPlayer" },
	{ 0x19B, "IsPlayerNumber" },
	{ 0x0C3, "IsAI" },
	{ 0x041, "SetSunLight" },
	{ 0x042, "ResetSunLight" },
	{ 0x14C, "SetWinningTeam" },
	{ 0x14D, "Announcement" },
	{ 0x14E, "ClientAnnouncement" },
	{ 0x150, "GetTeamScore" },
	{ 0x151, "SetTeamScore" },
	{ 0x152, "SetClientNameMode" },
	{ 0x153, "UpdateClientNames" },
	{ 0x154, "GetTeamPlayersAlive" },
	{ 0x259, "PlayCinematicForAll" },
	{ 0x25A, "PreloadCinematicForAll" },
	{ 0x25B, "StopCinematicForAll" },
	{ 0x156, "WorldEntNumber" },
	{ 0x157, "Obituary" },
	{ 0x158, "positionWouldTelefrag" },
	{ 0x159, "CanSpawn" },
	{ 0x25D, "CapsuleTracePassed" },
	{ 0x15A, "getStartTime" },
	{ 0x15B, "PrecacheStatusIcon" },
	{ 0x15D, "PrecacheMiniMapIcon" },
	{ 0x15E, "PrecacheMpAnim" },
	{ 0x15F, "MapRestart" },
	{ 0x160, "ExitLevel" },
	{ 0x161, "AddTestClient" },
	{ 0x162, "AddAgent" },
	{ 0x164, "AllClientsPrint" },
	{ 0x165, "ClientPrint" },
	{ 0x166, "MapExists" },
	{ 0x167, "IsValidGameType" },
	{ 0x169, "SetPlayerTeamRank" },
	{ 0x16B, "SetTeamRadar" },
	{ 0x16C, "GetTeamRadar" },
	{ 0x16D, "SetTeamRadarStrength" },
	{ 0x16E, "GetTeamRadarStrength" },
	{ 0x16F, "GetUAVStrengthMin" },
	{ 0x11A, "GetUAVStrengthMax" },
	{ 0x11B, "IsHairRunning" },
	{ 0x11C, "GetUAVStrengthLevelShowEnemyFastSweep" },
	{ 0x11D, "GetUAVStrengthMax" },
	{ 0x11E, "BlockTeamRadar" },
	{ 0x11F, "UnblockTeamRadar" },
	{ 0x120, "IsTeamRadarBlocked" },
	{ 0x121, "IsHairRunning" },
	{ 0x122, "SetMatchData" },
	{ 0x123, "GetMatchData" },
	{ 0x124, "SendMatchData" },
	{ 0x125, "ClearMatchData" },
	{ 0x126, "SetMatchDataDef" },
	{ 0x127, "SetMatchClientIP" },
	{ 0x128, "SetMatchDataID" },
	{ 0x129, "SetClientMatchData" },
	{ 0x12A, "GetClientMatchData" },
	{ 0x12B, "SetClientMatchDataDef" },
	{ 0x12C, "SendClientMatchData" },
	{ 0x12D, "GetBuildVersion" },
	{ 0x12E, "GetBuildNumber" },
	{ 0x12F, "GetSystemTime" },
	{ 0x130, "GetMatchRulesData" },
	{ 0x131, "IsUsingMatchRulesData" },
	{ 0x132, "KickPlayer" },
	{ 0x133, "IsHairRunning" },
	{ 0x134, "SetMapCenter" },
	{ 0x135, "SetGameEndTime" },
	{ 0x136, "VisionSetNaked" },
	{ 0x137, "VisionSetNight" },
	{ 0x138, "VisionSetMissilecam" },
	{ 0x0EC, "VisionSetThermal" },
	{ 0x0ED, "VisionSetPain" },
	{ 0x255, "VisionSetPostApply" },
	{ 0x0EF, "SetAC130Ambience" },
	{ 0x0F0, "GetMapCustomField" },
	{ 0x0F1, "SpawnSightTrace" },
	{ 0x0F2, "IncrementCounter" },
	{ 0x0F3, "GetCounterTotal" },
	{ 0x14F, "SetTeamMode" },
	{ 0x0B7, "GetNode" },
	{ 0x0B8, "GetNodeArray" },
	{ 0x0B9, "GetAllNodes" },
	{ 0x0BA, "GetNodesInRadius" },
	{ 0x0BB, "GetNodesInRadiusSorted" },
	{ 0x1F0, "GetZoneCount" },
	{ 0x1F1, "GetZoneNearest" },
	{ 0x1F5, "GetNodeZone" },
	{ 0x1F2, "GetZoneNodes" },
	{ 0x1F6, "GetZoneNodesByDist" },
	{ 0x1F7, "GetZoneNodeForIndex" },
	{ 0x1F3, "GetZonePath" },
	{ 0x1F4, "GetZoneOrigin" },
	{ 0x1FC, "FindEntrances" },
	{ 0x1FB, "NodeExposedToSky" },
	{ 0x1ED, "GetNodesInTrigger" },
	{ 0x1EE, "NodesVisible" },
	{ 0x1EF, "GetNodesOnPath" },
	{ 0x1E8, "IsBot" },
	{ 0x1EC, "BotGetClosestNavigablePoint" },
	{ 0x1E4, "BotMemoryFlags" },
	{ 0x1E5, "BotFlagMemoryEvents" },
	{ 0x1DF, "BotGetMemoryEvents" },
	{ 0x1E0, "BotAutoConnectEnabled" },
	{ 0x1E1, "BotZoneGetCount" },
	{ 0x1E6, "BotZoneGetIndoorPercent" },
	{ 0x1E2, "BotZoneSetTeam" },
	{ 0x1E3, "BotZoneNearestCount" },
	{ 0x1E7, "BotSentientSwap" },
	{ 0x24A, "BotGetTeamLimit" },
	{ 0x24C, "BotGetTeamDifficulty" },
	{ 0x1F8, "GetWeaponExplosionRadius" },
	{ 0x23C, "GetPredictedEntityPosition" },
	{ 0x1FE, "GetPathDist" },
	{ 0x1F9, "MarkDangerousNodes" },
	{ 0x1FA, "MarkDangerousNodesInTrigger" },
	{ 0x1E9, "IsAgent" },
	{ 0x1EA, "GetMaxAgents" },
	{ 0x223, "SetLevelDopplerPreset" },
	{ 0x243, "QueueDialog" },
	{ 0x248, "TriggerPortableRadarPing" },
	{ 0x24F, "IsDedicatedServer" },
	{ 0x250, "GetPlaylistVersion" },
	{ 0x251, "GetPlaylistID" },
	{ 0x252, "GetActiveClientCount" },
	{ 0x253, "IsSquadsMode" },
	{ 0x256, "AddBot" },
	{ 0x258, "GetSquadAssaultEnemyPrestige" },
};

std::unordered_map<std::uint16_t, std::string> resolver::builtin_method_map
{
	// ------------------------------------------------------------------------
	// METHOD COMMON 230
	{ 0x8018, "attach" },
	{ 0x8019, "attachShieldModel" },
	{ 0x8026, "detach" },
	{ 0x8027, "detachShieldModel" },
	{ 0x8028, "moveShieldModel" },
	{ 0x8029, "detachAll" },
	{ 0x802A, "GetAttachSize" },
	{ 0x802B, "GetAttachModelName" },
	{ 0x802C, "GetAttachTagName" },
	{ 0x8044, "GetAttachIgnoreCollision" },
	{ 0x8045, "hidepart" },
	{ 0x8046, "hidepartAllInstances" },
	{ 0x8047, "hideallparts" },
	{ 0x8048, "showpart" },
	{ 0x8049, "showallparts" },
	{ 0x804A, "LinkTo" },
	{ 0x804B, "LinkToBlendToTag" },
	{ 0x804C, "Unlink" },
	{ 0x8067, "IsLinked" },
	{ 0x83B8, "GetLinkedParent" },
	{ 0x8402, "GetLinkedChildren" },
	{ 0x83B9, "GetMovingPlatformParent" },
	{ 0x8413, "AutoboltMissileEffects" },
	{ 0x8068, "EnableLinkTo" },
	{ 0x8079, "PlayerLinkTo" },
	{ 0x807A, "PlayerLinkToDelta" },
	{ 0x807B, "PlayerLinkWeaponViewToDelta" },
	{ 0x807C, "PlayerLinkToAbsolute" },
	{ 0x807D, "PlayerLinkToBlend" },
	{ 0x807E, "PlayerLinkedOffsetEnable" },
	{ 0x8098, "PlayerLinkedOffsetDisable" },
	{ 0x8099, "PlayerLinkedSetViewZnear" },
	{ 0x809A, "PlayerLinkedSetUseBaseAngleForViewClamp" },
	{ 0x809B, "LerpViewAngleClamp" },
	{ 0x80A1, "GetEye" },
	{ 0x840E, "GetViewOrigin" },
	{ 0x80A2, "IsTouching" },
	{ 0x80A3, "GetIsTouchingEntities" },
	{ 0x80A4, "StopLoopSound" },
	{ 0x80A5, "StopSounds" },
	{ 0x80A6, "PlayRumbleOnEntity" },
	{ 0x80A7, "PlayRumbleLoopOnEntity" },
	{ 0x80A8, "StopRumble" },
	{ 0x80A9, "Delete" },
	{ 0x80AA, "SetModel" },
	{ 0x80AB, "LaserOn" },
	{ 0x80AC, "LaserOff" },
	{ 0x80AD, "LaserAltViewOn" },
	{ 0x80AE, "LaserAltViewOff" },
	{ 0x80AF, "ThermalVisionOn" },
	{ 0x80B0, "ThermalVisionOnShadowOff" },
	{ 0x80B1, "ThermalVisionOff" },
	{ 0x8025, "ThermalDrawEnable" },
	{ 0x8000, "ThermalDrawDisable" },
	{ 0x80B2, "ThermalVisionFOFOverlayOn" },
	{ 0x80B3, "ThermalVisionFOFOverlayOff" },
	{ 0x80B4, "AutoSpotOverlayOn" },
	{ 0x80B5, "AutoSpotOverlayOff" },
	{ 0x80B6, "SetEyesOnUplinkEnabled" },
	{ 0x80B7, "SetContents" },
	{ 0x80B8, "MakeUsable" },
	{ 0x80B9, "MakeUnusable" },
	{ 0x80D1, "SetCursorHint" },
	{ 0x80D2, "SetHintString" },
	{ 0x80D3, "ForceUseHintOn" },
	{ 0x80D4, "ForceUseHintOff" },
	{ 0x80D5, "MakeSoft" },
	{ 0x80D6, "MakeHard" },
	{ 0x80D7, "EntityWillNeverChange" },
	{ 0x80D8, "StartFiring" },
	{ 0x80D9, "StopFiring" },
	{ 0x80DA, "IsFiringTurret" },
	{ 0x80DB, "StartBarrelSpin" },
	{ 0x80DC, "StopBarrelSpin" },
	{ 0x80DD, "GetBarrelSpinRate" },
	{ 0x80DE, "RemoteControlTurret" },
	{ 0x80DF, "RemoteControlTurretOff" },
	{ 0x80E0, "ShootTurret" },
	{ 0x80E1, "GetTurretOwner" },
	{ 0x80F9, "SetSentryOwner" },
	{ 0x80FA, "SetSentryCarrier" },
	{ 0x80FB, "SetTurretMinimapVisible" },
	{ 0x80FC, "SetTargetEntity" },
	{ 0x80FD, "SnapToTargetEntity" },
	{ 0x80FE, "ClearTargetEntity" },
	{ 0x80FF, "GetTurretTarget" },
	{ 0x8100, "SetPlayerSpread" },
	{ 0x8101, "EnableMouseSteer" },
	{ 0x8102, "EnableMouseSteer" },
	{ 0x812C, "SetConvergenceTime" },
	{ 0x812D, "SetConvergenceHeightPercent" },
	{ 0x812E, "SetTurretTeam" },
	{ 0x812F, "MakeTurretSolid" },
	{ 0x8130, "MakeTurretOperable" },
	{ 0x8131, "MakeTurretInoperable" },
	{ 0x814E, "SetRightArc" },
	{ 0x814F, "SetLeftArc" },
	{ 0x8150, "SetTopArc" },
	{ 0x8151, "SetBottomArc" },
	{ 0x8152, "SetAutoRotationDelay" },
	{ 0x8153, "SetDefaultDropPitch" },
	{ 0x8154, "RestoreDefaultDropPitch" },
	{ 0x8155, "TurretFireDisable" },
	{ 0x8174, "TurretFireEnable" },
	{ 0x83F0, "TurretSetBarrelSpinEnabled" },
	{ 0x8175, "SetTurretModeChangeWait" },
	{ 0x8031, "GetHighestNodeStance" },
	{ 0x8032, "DoesNodeAllowStance" },
	{ 0x8176, "UseTriggerRequireLookAt" },
	{ 0x8177, "GetStance" },
	{ 0x8178, "SetStance" },
	{ 0x8179, "ItemWeaponSetAmmo" },
	{ 0x817A, "GetAmmoCount" },
	{ 0x817B, "GetTagOrigin" },
	{ 0x817C, "GetTagAngles" },
	{ 0x817D, "ShellShock" },
	{ 0x817E, "StunPlayer" },
	{ 0x83AE, "EnableMouseSteer" },
	{ 0x83C4, "EnableMouseSteer" },
	{ 0x817F, "StopShellShock" },
	{ 0x8180, "FadeOutShellShock" },
	{ 0x8181, "SetDepthOfField" },
	{ 0x8182, "SetViewModelDepthOfField" },
	{ 0x8183, "EnableMouseSteer" },
	{ 0x81A8, "EnableMouseSteer" },
	{ 0x81A9, "EnableMouseSteer" },
	{ 0x81AA, "ViewKick" },
	{ 0x81AB, "LocalToWorldCoords" },
	{ 0x81AC, "GetEntityNumber" },
	{ 0x81AD, "GetEntityVelocity" },
	{ 0x81AE, "EnableGrenadeTouchDamage" },
	{ 0x81AF, "DisableGrenadeTouchDamage" },
	{ 0x81B0, "EnableAimAssist" },
	{ 0x81CF, "DisableAimAssist" },
	{ 0x81D0, "EntityRadiusDamage" },
	{ 0x804E, "DoDamage" },
	{ 0x81D1, "Detonate" },
	{ 0x81D2, "DamageConeTrace" },
	{ 0x81D3, "SightConeTrace" },
	{ 0x81D4, "MissileSetTargetEnt" },
	{ 0x81D5, "MissileSetTargetPos" },
	{ 0x81D6, "MissileClearTarget" },
	{ 0x81D7, "MissileSetFlightmodeDirect" },
	{ 0x81D8, "MissileSetFlightmodeTop" },
	{ 0x81D9, "GetLightIntensity" },
	{ 0x81DA, "SetLightIntensity" },
	{ 0x81DB, "IsRagdoll" },
	{ 0x81DC, "SetMoveSpeedScale" },
	{ 0x83E9, "SetGrenadeThrowScale" },
	{ 0x83EA, "SetGrenadeCookScale" },
	{ 0x81DD, "CameraLinkTo" },
	{ 0x81DE, "CameraUnlink" },
	{ 0x81FB, "ControlsLinkTo" },
	{ 0x81FC, "ControlsUnlink" },
	{ 0x8410, "RideVehicle" },
	{ 0x8411, "StopRidingVehicle" },
	{ 0x83E4, "DisableMissileBoosting" },
	{ 0x83E5, "EnableMissileBoosting" },
	{ 0x8416, "SetMissileMinimapVisible" },
	{ 0x81FD, "MakeVehicleSolidCapsule" },
	{ 0x81FF, "MakeVehicleSolidSphere" },
	{ 0x8201, "RemoteControlVehicle" },
	{ 0x8202, "RemoteControlVehicleOff" },
	{ 0x8203, "IsFiringVehicleTurret" },
	{ 0x8204, "RemoteControlVehicleTarget" },
	{ 0x8205, "RemoteControlVehicleTargetOff" },
	{ 0x83BF, "MakeVehicleNotCollideWithPlayers" },
	{ 0x8206, "DriveVehicleAndControlTurret" },
	{ 0x8207, "DriveVehicleAndControlTurretOff" },
	{ 0x8208, "GetPlayerSetting" },
	{ 0x8209, "GetPlayerSetting" },
	{ 0x820A, "EnableMouseSteer" },
	{ 0x820B, "RemoteCameraSoundscapeOn" },
	{ 0x820C, "RemoteCameraSoundscapeOff" },
	{ 0x820D, "EnableMouseSteer" },
	{ 0x820E, "EnableMouseSteer" },
	{ 0x83CC, "WorldPointToScreenPos" },
	{ 0x820F, "WorldPointInReticle_Circle" },
	{ 0x8210, "WorldPointInReticle_Rect" },
	{ 0x8211, "GetPointInBounds" },
	{ 0x8212, "TransferMarksToNewScriptModel" },
	{ 0x8213, "GSetWaterSheeting" },
	{ 0x8216, "GSetWeaponHudIconOverride" },
	{ 0x8217, "GGetWeaponHudIconOverride" },
	{ 0x8218, "SetEMPJammed" },
	{ 0x8219, "PlayerSetExponentialFog" },
	{ 0x821A, "IsItemUnlocked" },
	{ 0x821B, "GetPlayerData" },
	{ 0x823A, "SetPlayerData" },
	{ 0x821C, "GetRankedPlayerData" },
	{ 0x823B, "SetRankedPlayerData" },
	{ 0x821D, "GetPrivatePlayerData" },
	{ 0x823C, "SetPrivatePlayerData" },
	{ 0x821E, "GetCoopPlayerData" },
	{ 0x823D, "SetCoopPlayerData" },
	{ 0x821F, "GetCommonPlayerData" },
	{ 0x823E, "SetCommonPlayerData" },
	{ 0x823F, "GetCaCPlayerData" },
	{ 0x8240, "TrackerUpdate" },
	{ 0x8056, "DisconnectPaths" },
	{ 0x8057, "ConnectPaths" },
	{ 0x8058, "DisconnectNode" },
	{ 0x8059, "ConnectNode" },
	{ 0x8375, "SetAISightLineVisible" },
	{ 0x83A7, "SetClothType" },
	{ 0x83B0, "SetSurfaceType" },
	{ 0x83B1, "AIPhysicsTrace" },
	{ 0x83B2, "AIPhysicsTracePassed" },
	{ 0x808F, "DontInterpolate" },
	{ 0x83C2, "SetScriptablePartState" },
	{ 0x8407, "SetScriptableDamageOwner" },
	{ 0x83C3, "StopSliding" },
	{ 0x83EC, "HudOutlineEnableForClient" },
	{ 0x83ED, "HudOutlineDisableForClient" },
	{ 0x83EE, "HudOutlineEnableForClients" },
	{ 0x83EF, "HudOutlineDisableForClients" },
	{ 0x83C6, "HudOutlineEnable" },
	{ 0x83C7, "HudOutlineDisable" },
	{ 0x83C8, "MotionBlurHQEnable" },
	{ 0x83C9, "MotionBlurHQDisable" },
	{ 0x8419, "MakeCollideWithItemClip" },
	{ 0x841C, "SetCommonPlayerDataReservedInt" },
	{ 0x8424, "GetCommonPlayerDataReservedInt" },
	{ 0x841E, "GetRankedPlayerDataReservedInt" },
	{ 0x841F, "SetRankedPlayerDataReservedInt" },
	{ 0x8425, "GetCoopPlayerDataReservedInt" },
	{ 0x8426, "SetCoopPlayerDataReservedInt" },

	// ------------------------------------------------------------------------
	// PLAYER 57
	{ 0x8241, "pingPlayer" },
	{ 0x8242, "buttonPressedDEVONLY" },
	{ 0x8243, "SayAll" },
	{ 0x8244, "SayTeam" },
	{ 0x8245, "setSpawnWeapon" },
	{ 0x8246, "dropItem" },
	{ 0x8247, "DropScavengerBag" },
	{ 0x8260, "finishPlayerDamage" },
	{ 0x8261, "Suicide" },
	{ 0x8262, "CloseInGameMenu" },
	{ 0x8263, "iclientprintln" },
	{ 0x8264, "iclientprintlnbold" },
	{ 0x8265, "spawn" },
	{ 0x8266, "setEnterTime" },
	{ 0x8267, "ClonePlayer" },
	{ 0x8268, "IsTalking" },
	{ 0x8269, "AllowSpectateTeam" },
	{ 0x826A, "GetGuid" },
	{ 0x828C, "GetXuid" },
	{ 0x828D, "GetUcdIdLow" },
	{ 0x828E, "GetUcdIdLow" },
	{ 0x828F, "GetClanIdHigh" },
	{ 0x8290, "GetClanIdLow" },
	{ 0x8291, "IsHost" },
	{ 0x8292, "GetSpectatingPlayer" },
	{ 0x8293, "PredictStreamPos" },
	{ 0x8296, "SetRank" },
	{ 0x82BA, "SetCardDisplaySlot" },
	{ 0x82BB, "KC_RegWeaponForFXRemoval" },
	{ 0x82BC, "LastStandRevive" },
	{ 0x82BD, "SetSpectateDefaults" },
	{ 0x82BE, "GetThirdPersonCrosshairOffset" },
	{ 0x82C1, "IsSplitscreenPlayer" },
	{ 0x82DC, "IsSplitscreenPlayerPrimary" },
	{ 0x829F, "RegisterParty" },
	{ 0x82A0, "GetFireteamMembers" },
	{ 0x82DD, "MarkForEyesOn" },
	{ 0x82DE, "IsSighted" },
	{ 0x82DF, "GetSightedPlayers" },
	{ 0x82E0, "GetPlayersSightingMe" },
	{ 0x8378, "GetNearestNode" },
	{ 0x83D8, "GetCustomizationBody" },
	{ 0x83D9, "GetCustomizationHead" },
	{ 0x83DA, "GetCustomizationViewmodel" },
	{ 0x83E8, "LoadCustomizationPlayerView" },
	{ 0x83F1, "HasLoadedCustomizationPlayerView" },
	{ 0x8406, "HasFemaleCustomizationModel" },
	{ 0x83FD, "SetMLGCameraDefaults" },
	{ 0x83FE, "IsMLGSpectator" },
	{ 0x8422, "SetMLGSpectator" },
	{ 0x8423, "GetMLGSpectatorTeam" },
	{ 0x8427, "GetJoinType" },

	// ------------------------------------------------------------------------
	// PLAYER COMMON 229
	{ 0x82E1, "GetViewmodel" },
	{ 0x82E2, "fragButtonPressed" },
	{ 0x82E3, "secondaryOffhandButtonPressed" },
	{ 0x82E4, "getCurrentWeaponClipAmmo" },
	{ 0x82E5, "SetVelocity" },
	{ 0x82E6, "getViewHeight" },
	{ 0x833C, "EnableMouseSteer" },
	{ 0x82E7, "getNormalizedMovement" },
	{ 0x8301, "getNormalizedCameraMovement" },
	{ 0x8302, "giveWeapon" },
	{ 0x8303, "takeWeapon" },
	{ 0x840C, "GetHybridScopeState" },
	{ 0x840D, "SetHybridScopeState" },
	{ 0x8304, "takeAllWeapons" },
	{ 0x8305, "getCurrentWeapon" },
	{ 0x8306, "getCurrentPrimaryWeapon" },
	{ 0x8307, "getCurrentOffhand" },
	{ 0x8308, "hasWeapon" },
	{ 0x8309, "switchToWeapon" },
	{ 0x830A, "switchToWeaponImmediate" },
	{ 0x830B, "switchToOffhand" },
	{ 0x840F, "setWeaponModelVariant" },
	{ 0x8325, "giveStartAmmo" },
	{ 0x8326, "giveMaxAmmo" },
	{ 0x8327, "getFractionStartAmmo" },
	{ 0x8328, "getFractionMaxAmmo" },
	{ 0x8329, "isDualWielding" },
	{ 0x832A, "isReloading" },
	{ 0x832B, "isSwitchingWeapon" },
	{ 0x8417, "isOffhandWeaponReadyToThrow" },
	{ 0x832C, "setOrigin" },
	{ 0x832D, "GetVelocity" },
	{ 0x832E, "setAngles" },
	{ 0x832F, "getAngles" },
	{ 0x83A4, "IsSprinting" },
	{ 0x8418, "IsLeaning" },
	{ 0x8330, "useButtonPressed" },
	{ 0x8331, "attackButtonPressed" },
	{ 0x8332, "adsButtonPressed" },
	{ 0x8333, "meleeButtonPressed" },
	{ 0x83AA, "jumpButtonPressed" },
	{ 0x8334, "playerADS" },
	{ 0x8335, "isOnGround" },
	{ 0x8336, "isUsingTurret" },
	{ 0x8337, "SetViewmodel" },
	{ 0x8338, "setOffhandPrimaryClass" },
	{ 0x8339, "getOffhandPrimaryClass" },
	{ 0x830C, "setOffhandSecondaryClass" },
	{ 0x830D, "getOffhandSecondaryClass" },
	{ 0x830E, "BeginLocationSelection" },
	{ 0x830F, "EndLocationSelection" },
	{ 0x8310, "DisableWeapons" },
	{ 0x8311, "EnableWeapons" },
	{ 0x8312, "DisableOffhandWeapons" },
	{ 0x8313, "EnableOffhandWeapons" },
	{ 0x8314, "DisableWeaponSwitch" },
	{ 0x8315, "EnableWeaponSwitch" },
	{ 0x8316, "OpenPopupMenu" },
	{ 0x8317, "OpenPopupMenuNoMouse" },
	{ 0x8318, "ClosePopupMenu" },
	{ 0x8319, "OpenMenu" },
	{ 0x831A, "CloseMenu" },
	{ 0x831C, "FreezeControls" },
	{ 0x831D, "DisableUsability" },
	{ 0x831E, "EnableUsability" },
	{ 0x831F, "SetWhizbySpreads" },
	{ 0x8320, "SetWhizbyRadii" },
	{ 0x8323, "SetVolMod" },
	{ 0x8324, "SetChannelVolume" },
	{ 0x82E8, "SetChannelVolumes" },
	{ 0x82E9, "DeactivateChannelVolumes" },
	{ 0x82EA, "PlayLocalSound" },
	{ 0x82EB, "StopLocalSound" },
	{ 0x82EC, "SetWeaponAmmoClip" },
	{ 0x82ED, "SetWeaponAmmoStock" },
	{ 0x82EE, "GetWeaponAmmoClip" },
	{ 0x82EF, "GetWeaponAmmoStock" },
	{ 0x82F0, "AnyAmmoForWeaponModes" },
	{ 0x82F1, "SetClientOmnvar" },
	{ 0x82F2, "SetClientDvar" },
	{ 0x82F3, "SetClientDvars" },
	{ 0x82F4, "SetClientSpawnSightTraces" },
	{ 0x82F5, "ClientSpawnSightTracePassed" },
	{ 0x82F6, "AllowADS" },
	{ 0x82F7, "AllowJump" },
	{ 0x82F8, "AllowSprint" },
	{ 0x82F9, "SetSpreadOverride" },
	{ 0x82FA, "ResetSpreadOverride" },
	{ 0x82FB, "SetAimSpreadMovementScale" },
	{ 0x82FC, "SetActionSlot" },
	{ 0x82FD, "SetViewKickScale" },
	{ 0x82FE, "GetViewKickScale" },
	{ 0x82FF, "GetWeaponsListAll" },
	{ 0x8300, "GetWeaponsListPrimaries" },
	{ 0x82C2, "GetWeaponsListOffhands" },
	{ 0x82C3, "GetWeaponsListItems" },
	{ 0x82C4, "GetWeaponsListExclusives" },
	{ 0x82C5, "GetWeaponsList" },
	{ 0x82C6, "CanPlayerPlaceSentry" },
	{ 0x82C7, "CanPlayerPlaceTank" },
	{ 0x82C8, "VisionSetNakedForPlayer" },
	{ 0x83B6, "VisionSetStage" },
	{ 0x82C9, "VisionSetNightForPlayer" },
	{ 0x82CA, "VisionSetMissileCamForPlayer" },
	{ 0x82CB, "VisionSetThermalForPlayer" },
	{ 0x82CC, "VisionSetPainForPlayer" },
	{ 0x841B, "VisionSetPostApplyForPlayer" },
	{ 0x82CD, "SetBlurForPlayer" },
	{ 0x82CE, "GetPlayerWeaponModel" },
	{ 0x82CF, "GetPlayerWeaponModel" },
	{ 0x82D1, "notifyOnPlayerCommand" },
	{ 0x82D2, "CanMantle" },
	{ 0x82D3, "ForceMantle" },
	{ 0x8405, "CancelMantle" },
	{ 0x82D4, "IsMantling" },
	{ 0x82D5, "PlayFX" },
	{ 0x82D6, "PlayerRecoilScaleOn" },
	{ 0x82D7, "PlayerRecoilScaleOff" },
	{ 0x82D8, "WeaponLockStart" },
	{ 0x82D9, "WeaponLockFinalize" },
	{ 0x82DA, "WeaponLockFree" },
	{ 0x82DB, "WeaponLockTargetTooClose" },
	{ 0x8298, "WeaponLockNoClearance" },
	{ 0x82BF, "DisableWeaponPickup" },
	{ 0x82C0, "EnableWeaponPickup" },
	{ 0x83FF, "DisableAutoReload" },
	{ 0x8400, "EnableAutoReload" },
	{ 0x8127, "IsMeleeing" },
	{ 0x815E, "GetEnemyInfo" },
	{ 0x8341, "BotSetFlag" },
	{ 0x8342, "BotSetStance" },
	{ 0x835D, "BotLookAtPoint" },
	{ 0x8343, "BotSetScriptMove" },
	{ 0x8344, "BotSetScriptGoal" },
	{ 0x8345, "BotSetScriptGoalNode" },
	{ 0x8346, "BotClearScriptGoal" },
	{ 0x8347, "BotSetScriptEnemy" },
	{ 0x8348, "BotClearScriptEnemy" },
	{ 0x8369, "BotSetPathingStyle" },
	{ 0x8349, "BotSetAttacker" },
	{ 0x8364, "BotSetAwareness" },
	{ 0x836E, "BotPressButton" },
	{ 0x836F, "BotClearButton" },
	{ 0x8357, "BotThrowGrenade" },
	{ 0x8355, "BotHasScriptGoal" },
	{ 0x834A, "BotGetScriptGoal" },
	{ 0x8366, "BotGetScriptGoalNode" },
	{ 0x834B, "BotGetScriptGoalRadius" },
	{ 0x834C, "BotGetScriptGoalYaw" },
	{ 0x834D, "BotGetScriptGoalType" },
	{ 0x8365, "BotPursuingScriptGoal" },
	{ 0x834F, "BotGetWorldSize" },
	{ 0x835C, "BotGetWorldClosestEdge" },
	{ 0x8350, "BotNodeAvailable" },
	{ 0x8351, "BotFindNodeRandom" },
	{ 0x8352, "BotMemoryEvent" },
	{ 0x8354, "BotNodePick" },
	{ 0x8361, "BotNodePickMultiple" },
	{ 0x8370, "BotNodeScoreMultiple" },
	{ 0x8356, "BotGetPersonality" },
	{ 0x8359, "BotSetPersonality" },
	{ 0x835A, "BotSetDifficulty" },
	{ 0x835B, "BotGetDifficulty" },
	{ 0x836A, "BotSetDifficultySetting" },
	{ 0x836B, "BotGetDifficultySetting" },
	{ 0x835E, "BotPredictSeePoint" },
	{ 0x835F, "BotCanSeeEntity" },
	{ 0x8360, "BotGetNodesOnPath" },
	{ 0x836C, "BotGetPathDist" },
	{ 0x8363, "BotGetFovDot" },
	{ 0x8367, "BotGetImperfectEnemyInfo" },
	{ 0x836D, "BotIsRandomized" },
	{ 0x8371, "GetNodeNumber" },
	{ 0x8377, "NodeIsDisconnected" },
	{ 0x83CF, "BotFirstAvailableGrenade" },
	{ 0x8403, "BotPredictEnemyCampSpots" },
	{ 0x837B, "SpawnAgent" },
	{ 0x837C, "FinishAgentDamage" },
	{ 0x837D, "SetAgentAttacker" },
	{ 0x837E, "CloneAgent" },
	{ 0x837F, "AgentCanSeeSentient" },
	{ 0x839C, "SetAnimClass" },
	{ 0x839D, "EnableAnimState" },
	{ 0x839E, "SetAnimState" },
	{ 0x839F, "GetAnimEntry" },
	{ 0x83A0, "GetAnimEntryName" },
	{ 0x83A1, "GetAnimEntryAlias" },
	{ 0x83A2, "GetAnimEntryCount" },
	{ 0x83AC, "ScrGetLookaheadDir" },
	{ 0x83AD, "ScrGetPathGoalPos" },
	{ 0x8381, "ScrSetGoalPos" },
	{ 0x8382, "ScrGetGoalPos" },
	{ 0x8383, "ScrSetGoalNode" },
	{ 0x8384, "ScrSetGoalEntity" },
	{ 0x8385, "ScrSetGoalRadius" },
	{ 0x8380, "ScrSetWaypoint" },
	{ 0x8198, "ScrGetNegotiationStartNode" },
	{ 0x8199, "ScrGetNegotiationEndNode" },
	{ 0x819A, "ScrGetNegotiationNextNode" },
	{ 0x8386, "ScrSetAnimScale" },
	{ 0x8387, "ScrSetOrientMode" },
	{ 0x8388, "ScrSetAnimMode" },
	{ 0x8389, "ScrSetPhysicsMode" },
	{ 0x838A, "ScrSetClipMode" },
	{ 0x838D, "ScrBeginMelee" },
	{ 0x838B, "ScrSetMaxTurnSpeed" },
	{ 0x838C, "ScrGetMaxTurnSpeed" },
	{ 0x838E, "ScrSetScripted" },
	{ 0x838F, "ScrDoTrajectory" },
	{ 0x8390, "ScrDoAnimLerp" },
	{ 0x83F4, "ScrDoAnimRelative" },
	{ 0x8391, "ScrSetViewHeight" },
	{ 0x8392, "ScrClaimNode" },
	{ 0x8393, "ScrRelinquishClaimedNode" },
	{ 0x8421, "ScrUseModelCollisionBounds" },
	{ 0x8428, "ScrSetWallRunCost" },
	{ 0x8299, "VisionSyncWithPlayer" },
	{ 0x83BA, "SetNameplateMaterial" },
	{ 0x829A, "ShowHudSplash" },
	{ 0x829B, "SetPerk" },
	{ 0x829C, "HasPerk" },
	{ 0x829D, "ClearPerks" },
	{ 0x829E, "UnsetPerk" },
	{ 0x833E, "usingGamepad" },

	// ------------------------------------------------------------------------
	// METHOD SCRIPTENT 34
	{ 0x82A3, "MoveTo" },
	{ 0x82A4, "MoveX" },
	{ 0x82A5, "MoveY" },
	{ 0x82A6, "MoveZ" },
	{ 0x82A7, "GravityMove" },
	{ 0x82A8, "MoveSlide" },
	{ 0x82A9, "StopMoveSlide" },
	{ 0x82AA, "RotateTo" },
	{ 0x83AB, "RotateBy" },
	{ 0x82AB, "RotatePitch" },
	{ 0x82AC, "RotateYaw" },
	{ 0x82AD, "RotateRoll" },
	{ 0x82AE, "AddPitch" },
	{ 0x82AF, "AddYaw" },
	{ 0x82B0, "AddRoll" },
	{ 0x82B1, "Vibrate" },
	{ 0x82B2, "RotateVelocity" },
	{ 0x82B3, "Solid" },
	{ 0x82B4, "NotSolid" },
	{ 0x82B5, "SetCanDamage" },
	{ 0x82B6, "SetCanRadiusDamage" },
	{ 0x82B7, "PhysicsLaunchClient" },
	{ 0x826B, "PhysicsLaunchServer" },
	{ 0x826C, "PhysicsLaunchServerItem" },
	{ 0x826D, "CloneBrushModelToScriptModel" },
	{ 0x826E, "ScriptModelPlayAnim" },
	{ 0x826F, "ScriptModelClearAnim" },
	{ 0x8270, "ScriptModelPlayAnimDeltaMotion" },
	{ 0x83DE, "PhysicsSetMaxLinVel" },
	{ 0x83DF, "PhysicsSetMaxAngVel" },
	{ 0x83E0, "PhysicsGetLinVel" },
	{ 0x83E1, "PhysicsGetLinSpeed" },
	{ 0x83E2, "PhysicsGetAngVel" },
	{ 0x83E3, "PhysicsGetAngSpeed" },

	// ------------------------------------------------------------------------
	// METHOD VEHICLESCRIPT 62
	{ 0x8271, "Teleport" },
	{ 0x8272, "AttachPath" },
	{ 0x8273, "GetAttachPos" },
	{ 0x8274, "StartPath" },
	{ 0x8275, "SetSwitchNode" },
	{ 0x8276, "SetWaitSpeed" },
	{ 0x8277, "FinishDamage" },
	{ 0x8278, "SetSpeed" },
	{ 0x8279, "SetSpeedImmediate" },
	{ 0x827A, "RotateYaw" },
	{ 0x827B, "GetSpeed" },
	{ 0x827C, "GetVelocity" },
	{ 0x827D, "GetBodyVelocity" },
	{ 0x827E, "GetSteering" },
	{ 0x827F, "GetThrottle" },
	{ 0x8280, "TurnEngineOff" },
	{ 0x8281, "TurnEngineOn" },
	{ 0x8283, "GetGoalSpeedMPH" },
	{ 0x8284, "SetAcceleration" },
	{ 0x8285, "SetDeceleration" },
	{ 0x8286, "ResumeSpeed" },
	{ 0x8287, "SetYawSpeed" },
	{ 0x8288, "SetYawSpeedByName" },
	{ 0x8289, "SetMaxPitchRoll" },
	{ 0x828A, "SetAirResitance" },
	{ 0x828B, "SetTurningAbility" },
	{ 0x8248, "SetJitterParams" },
	{ 0x8249, "SetHoverParams" },
	{ 0x824A, "JoltBody" },
	{ 0x824B, "FreeVehicle" },
	{ 0x824C, "GetWheelSurface" },
	{ 0x824D, "GetVehicleOwner" },
	{ 0x83C5, "SetDroneGoalPos" },
	{ 0x824E, "SetVehicleLookatText" },
	{ 0x824F, "SetVehicleTeam" },
	{ 0x8250, "NearGoalNotifyDist" },
	{ 0x8251, "SetGoalPos" },
	{ 0x8252, "SetGoalYaw" },
	{ 0x8253, "ClearGoalYaw" },
	{ 0x8254, "SetTargetYaw" },
	{ 0x8255, "ClearTargetYaw" },
	{ 0x8256, "HeliSetGoal" },
	{ 0x8257, "SetTurretTargetVec" },
	{ 0x8258, "SetTurretTargetEnt" },
	{ 0x8259, "ClearTurretTargetEnt" },
	{ 0x825A, "CanTurretTargetPoint" },
	{ 0x825B, "SetLookAtEnt" },
	{ 0x825C, "ClearLookAtEnt" },
	{ 0x825D, "SetWeapon" },
	{ 0x825E, "FireWeapon" },
	{ 0x825F, "VehicleTurretControlOn" },
	{ 0x8220, "VehicleTurretControlOff" },
	{ 0x8221, "IsTurretReady" },
	{ 0x8222, "VehicleDriveTo" },
	{ 0x8223, "DoSpawn" },
	{ 0x8224, "IsPhysVeh" },
	{ 0x8225, "Crash" },
	{ 0x8226, "Launch" },
	{ 0x8227, "DisableCrashing" },
	{ 0x8228, "EnableCrashing" },
	{ 0x8229, "SetSpeed" },
	{ 0x822A, "SetConveyorBelt" },

	// ------------------------------------------------------------------------
	// METHOD HELICOPTER 2
	{ 0x822B, "FreeVehicle" },
	{ 0x8002, "SetDamageStage" },

	// ------------------------------------------------------------------------
	// METHOD HUDELEM 28
	{ 0x80C1, "SetText" },
	{ 0x80C3, "SetMaterial" },
	{ 0x80C4, "SetTargetEnt" },
	{ 0x80C5, "ClearTargetEnt" },
	{ 0x80C6, "SetTimer" },
	{ 0x80C7, "SetTimerUp" },
	{ 0x80C8, "SetTimerStatic" },
	{ 0x80C9, "SetTenthsTimer" },
	{ 0x80CA, "SetTenthsTimerUp" },
	{ 0x80CB, "SetTenthsTimerStatic" },
	{ 0x80CC, "SetClock" },
	{ 0x80CD, "SetClockUp" },
	{ 0x80CE, "SetValue" },
	{ 0x80CF, "SetWaypoint" },
	{ 0x80D0, "SetWaypointEdgeStyle_RotatingIcon" },
	{ 0x807F, "SetWaypointEdgeStyle_SecondaryArrow" },
	{ 0x8080, "SetWaypointIconOffscreenOnly" },
	{ 0x8081, "FadeOverTime" },
	{ 0x8082, "ScaleOverTime" },
	{ 0x8083, "MoveOverTime" },
	{ 0x8084, "Reset" },
	{ 0x8085, "Destroy" },
	{ 0x8086, "SetPulseFX" },
	{ 0x8087, "SetPlayerNameString" },
	{ 0x8088, "ChangeFontScaleOverTime" },
	{ 0x83B7, "LinkWaypointToTargetWithOffset" },

	// ------------------------------------------------------------------------
	// METHOD SENTIENT 9
	{ 0x8170, "GetEnemySqDist" },
	{ 0x8171, "GetClosestEnemySqDist" },
	{ 0x8172, "SetThreatBiasGroup" },
	{ 0x8173, "GetThreatBiasGroup" },
	{ 0x8132, "MakeEntitySentient" },
	{ 0x8133, "FreeEntitySentient" },
	{ 0x81BB, "LastKnownTime" },
	{ 0x81BC, "LastKnownPos" },
	{ 0x8420, "SetIgnoreFoliageSightingMe" },

	// ------------------------------------------------------------------------
	// METHOD 59
	{ 0x8092, "GetOrigin" },
	{ 0x8096, "UseBy" },
	{ 0x8097, "PlaySoundAsMaster" },
	{ 0x8072, "PlaySoundAsMaster" },
	{ 0x8003, "PlaySoundToTeam" },
	{ 0x8004, "PlaySoundToPlayer" },
	{ 0x8404, "PlaySoundOnMovingEnt" },
	{ 0x8073, "PlayLoopSound" },
	{ 0x8078, "GetNormalHealth" },
	{ 0x804D, "SetNormalHealth" },
	{ 0x8373, "SetOtherEnt" },
	{ 0x8376, "SetEntityOwner" },
	{ 0x8050, "Show" },
	{ 0x8051, "Hide" },
	{ 0x8005, "PlayerHide" },
	{ 0x8006, "ShowToPlayer" },
	{ 0x8007, "EnablePlayerUse" },
	{ 0x8008, "DisablePlayerUse" },
	{ 0x833D, "SetScriptMoverKillCam" },
	{ 0x8009, "MakeScrambler" },
	{ 0x800A, "MakePortableRadar" },
	{ 0x800B, "ClearScrambler" },
	{ 0x800C, "ClearPortableRadar" },
	{ 0x8064, "SetMode" },
	{ 0x8065, "GetMode" },
	{ 0x800E, "SetTeamForTrigger" },
	{ 0x800F, "ClientClaimTrigger" },
	{ 0x8010, "ClientReleaseTrigger" },
	{ 0x8011, "ReleaseClaimedTrigger" },
	{ 0x8012, "IsUsingOnlineDataOffline" },
	{ 0x8013, "GetRestedTime" },
	{ 0x8015, "IsOnLadder" },
	{ 0x801F, "StartRagdoll" },
	{ 0x8016, "GetCorpseAnim" },
	{ 0x83AF, "SetCorpseFalling" },
	{ 0x83F8, "GetCorpseEntity" },
	{ 0x8017, "PlayerForceDeathAnim" },
	{ 0x833A, "StartAC130" },
	{ 0x833B, "StartAC130" },
	{ 0x833F, "ForceThirdPersonWhenFollowing" },
	{ 0x8340, "DisableForceThirdPersonWhenFollowing" },
	{ 0x8372, "SetClientOwner" },
	{ 0x808E, "PlayerSetGroundReferenceEnt" },
	{ 0x8374, "PlayerCommandBot" },
	{ 0x8379, "MakeEntityNoMeleeTarget" },
	{ 0x83D5, "EmissiveBlend" },
	{ 0x8414, "DisableMissileStick" },
	{ 0x8415, "EnableMissileStick" },
	{ 0x83E6, "CanSpawnTestClient" },
	{ 0x83E7, "SpawnTestClient" },
	{ 0x83EB, "SetPlaneSplineId" },
	{ 0x83FA, "LogMatchDataLife" },
	{ 0x83FB, "LogMatchDataDeath" },
	{ 0x83FC, "QueueDialogForPlayer" },
	{ 0x8408, "SetFXKillDefOnDelete" },
	{ 0x841D, "GetClanWarsBonusForCurrentPlaylist" },
	{ 0x8429, "AliensCheckIsItemPurchased" },
};

std::unordered_map<std::string, std::uint16_t> resolver::file_map
{
	{ "codescripts\\character", 911 },
	{ "codescripts\\delete", 912 },
	{ "codescripts\\struct", 913 },
	{ "common_scripts\\_unk1", 914 },
	{ "common_scripts\\_unk2", 915 },
	{ "common_scripts\\_createfx", 916 },
	{ "common_scripts\\_createfxmenu", 917 },
	{ "common_scripts\\_unk3", 918 },
	{ "common_scripts\\_destructible", 919 },
	{ "common_scripts\\_dynamic_world", 920 },
	{ "common_scripts\\_elevator", 921 },
	{ "common_scripts\\_unk4", 922 },
	{ "common_scripts\\_fx", 923 },
	{ "common_scripts\\_pipes", 924 },
	{ "common_scripts\\utility", 927 },
// destructible_scripts
	{ "destructible_scripts\\toy_filecabinet", 935 },
	{ "destructible_scripts\\toy_light_ceiling_fluorescent", 937 },
	{ "destructible_scripts\\toy_transformer_small01", 940 },
	{ "destructible_scripts\\toy_trashcan_metal_closed", 941 },
	{ "destructible_scripts\\toy_tv_common", 942 },
	{ "destructible_scripts\\toy_tv_video_monitor", 944 },
// maps/animated_models
	{ "maps\\animatedmodels\\com_roofvent2_animated", 1201 },

	{ "maps\\animated_models\\clothes_line_sheet_iw6", 1205 }, // not exactly
	{ "maps\\animated_models\\debris_water_trash_bob", 1206 },
	{ "maps\\animated_models\\debris_water_trash_spiral", 1207 },
	{ "maps\\animated_models\\mp_flooded_street_water", 1208 },
	{ "maps\\animated_models\\mp_frag_crane_sway", 1209 },
// maps/createart
	{ "maps\\createart\\mp_alien_town_art", 1236 },
	{ "maps\\createart\\mp_alien_town_fog", 1237 },
	{ "maps\\createart\\mp_chasm_art", 1238 },
	{ "maps\\createart\\mp_chasm_fog", 1239 },
	{ "maps\\createart\\mp_dart_art", 1240 },
	{ "maps\\createart\\mp_dart_fog", 1241 },
	{ "maps\\createart\\mp_fahrenheit_art", 1242 },
	{ "maps\\createart\\mp_fahrenheit_fog", 1243 },
	{ "maps\\createart\\mp_flooded_art", 1244 },
	{ "maps\\createart\\mp_flooded_fog", 1245 },
	{ "maps\\createart\\mp_frag_art", 1246 },
	{ "maps\\createart\\mp_frag_fog", 1247 },
	{ "maps\\createart\\mp_hashima_art", 1248 },
	{ "maps\\createart\\mp_hashima_fog", 1249 },
	{ "maps\\createart\\mp_lonestar_art", 1250 },
	{ "maps\\createart\\mp_lonestar_fog", 1251 },
	{ "maps\\createart\\mp_prisonbreak_art", 1252 },
	{ "maps\\createart\\mp_prisonbreak_fog", 1253 },
	{ "maps\\createart\\mp_siege_unk", 1254 },
	{ "maps\\createart\\mp_skeleton_art", 1255 },
	{ "maps\\createart\\mp_skeleton_fog", 1256 },
	{ "maps\\createart\\mp_snow_art", 1257 },
	{ "maps\\createart\\mp_snow_fog", 1258 },
	{ "maps\\createart\\mp_sovereign_art", 1259 },
	{ "maps\\createart\\mp_sovereign_fog", 1260 },
	{ "maps\\createart\\mp_strikezone_art", 1261 },
	{ "maps\\createart\\mp_strikezone_fog", 1262 },
	{ "maps\\createart\\mp_warhawk_art", 1263 },
	{ "maps\\createart\\mp_warhawk_fog", 1264 },
	{ "maps\\createart\\mp_zebra_art", 1265 },
	{ "maps\\createart\\mp_zebra_fog", 1266 },
// maps/createfx
	{ "maps\\createfx\\mp_alient_town_fx", 1305 },
	{ "maps\\createfx\\mp_chasm_fx", 1306 },
	{ "maps\\createfx\\mp_dart_fx", 1307 },
	{ "maps\\createfx\\mp_fahrenheit_fx", 1308 },
	{ "maps\\createfx\\mp_flooded_fx", 1309 },
	{ "maps\\createfx\\mp_frag_fx", 1310 },
	{ "maps\\createfx\\mp_hashima_fx", 1311 },
	{ "maps\\createfx\\mp_lonestar_fx", 1312 },
	{ "maps\\createfx\\mp_prisonbreak_fx", 1313 },
	{ "maps\\createfx\\mp_skeleton_fx", 1314 },
	{ "maps\\createfx\\mp_snow_fx", 1315 },
	{ "maps\\createfx\\mp_sovereign_fx", 1316 },
	{ "maps\\createfx\\mp_strikezone_fx", 1317 },
	{ "maps\\createfx\\mp_warhawk_fx", 1318 },
	{ "maps\\createfx\\mp_zebra_fx", 1319 },
// maps/interactive_models
	{ "maps\\interactive_models\\_unk1", 1340},
// maps/mp
	{ "maps\\mp\\_animatedmodels", 1351 },
	{ "maps\\mp\\_areas", 1352 },
	{ "maps\\mp\\_art", 1353 },
	{ "maps\\mp\\_audio", 1354 },
	{ "maps\\mp\\_awards", 1355 },
	{ "maps\\mp\\_b_unk1", 1356 },
	{ "maps\\mp\\_compass", 1357 },
	{ "maps\\mp\\_createfx", 1358 },
	{ "maps\\mp\\_crib", 1359 },
	{ "maps\\mp\\_defcon", 1360 },
	{ "maps\\mp\\_destructables", 1361 },
	{ "maps\\mp\\_elevator", 1362 },
	{ "maps\\mp\\_emp", 1363 },
	{ "maps\\mp\\_entityheadicons", 1364 },
	{ "maps\\mp\\_events", 1365 },
	{ "maps\\mp\\_flashgrenades", 1366 },
	{ "maps\\mp\\_fx", 1367 },
	{ "maps\\mp\\_global_fx", 1368 },
	{ "maps\\mp\\_global_fx2", 1369 },
	{ "maps\\mp\\_highlights", 1370 },
	{ "maps\\mp\\_javelin", 1371 },
	{ "maps\\mp\\_laser_guided_launcher", 1372 },
	{ "maps\\mp\\_load", 1373 },
	{ "maps\\mp\\_matchdata", 1374 },
	{ "maps\\mp\\_matchevent", 1375 },
	{ "maps\\mp\\_mi_unk2", 1376 },
	{ "maps\\mp\\_minefields", 1377 },
	{ "maps\\mp\\_mover_unk3", 1378 },
	{ "maps\\mp\\_mover_unk4", 1379 },
	{ "maps\\mp\\_radiation", 1380 },
	{ "maps\\mp\\_scoreboard", 1381 },
	{ "maps\\mp\\_shutter", 1382 },
	{ "maps\\mp\\_stinger", 1383 },
	{ "maps\\mp\\_teleport", 1384 },
	{ "maps\\mp\\_utility", 1385 },
	{ "maps\\mp\\_water", 1386 },
	{ "maps\\mp\\_zipline", 1387 },
	{ "maps\\mp\\mp_alien_town_fx", 1388 },
	{ "maps\\mp\\mp_alien_town_precache", 1389 },
	{ "maps\\mp\\mp_chasm_fx", 1390 },
	{ "maps\\mp\\mp_chasm_precache", 1391 },
	{ "maps\\mp\\mp_dart_fx", 1392 },
	{ "maps\\mp\\mp_dart_precache", 1393 },
	{ "maps\\mp\\mp_fahrenheit_fx", 1394 },
	{ "maps\\mp\\mp_fahrenheit_precache", 1395 },
	{ "maps\\mp\\mp_flooded_fx", 1396 },
	{ "maps\\mp\\mp_flooded_precache", 1397 },
	{ "maps\\mp\\mp_frag_fx", 1398 },
	{ "maps\\mp\\mp_frag_precache", 1399 },
	{ "maps\\mp\\mp_hashima_fx", 1400 },
	{ "maps\\mp\\mp_hashima_precache", 1401 },
	{ "maps\\mp\\mp_lonestar_fx", 1402 },
	{ "maps\\mp\\mp_lonestar_precache", 1403 },
	{ "maps\\mp\\mp_prisonbreak_fx", 1404 },
	{ "maps\\mp\\mp_prisonbreak_precache", 1405 },
	{ "maps\\mp\\mp_skeleton_fx", 1406 },
	{ "maps\\mp\\mp_skeleton_precache", 1407 },
	{ "maps\\mp\\mp_snow_fx", 1408 },
	{ "maps\\mp\\mp_snow_precache", 1409 },
	{ "maps\\mp\\mp_sovereign_fx", 1410 },
	{ "maps\\mp\\mp_sovereign_precache", 1411 },
	{ "maps\\mp\\mp_strikezone_fx", 1412 },
	{ "maps\\mp\\mp_strikezone_precache", 1413 },
	{ "maps\\mp\\mp_warhawk_fx", 1414 },
	{ "maps\\mp\\mp_warhawk_precache", 1415 },
	{ "maps\\mp\\mp_zebra_fx", 1416 },
	{ "maps\\mp\\mp_zebra_precache", 1417 },
// maps/mp/agents/alien? 1418-29

// maps/mp/alien? 1441-64

// maps/mp/gametypes
	{ "maps\\mp\\gametypes\\_battlebuddy", 1465 },
	{ "maps\\mp\\gametypes\\_battlechatter_mp", 1466 },
	{ "maps\\mp\\gametypes\\_callbacksetup", 1467 },
	{ "maps\\mp\\gametypes\\_class", 1468 },
	{ "maps\\mp\\gametypes\\_d_unk1", 1469 },
	{ "maps\\mp\\gametypes\\_damage", 1470 },
	{ "maps\\mp\\gametypes\\_damagefeedback", 1471 },
	{ "maps\\mp\\gametypes\\_deathicons", 1472 },
	{ "maps\\mp\\gametypes\\_dev", 1473 },
	{ "maps\\mp\\gametypes\\_e_unk2", 1474 },
	{ "maps\\mp\\gametypes\\_friendicons", 1475 },
	{ "maps\\mp\\gametypes\\_gamelogic", 1476 },
	{ "maps\\mp\\gametypes\\_gameobjects", 1477 },
	{ "maps\\mp\\gametypes\\_gamescore", 1478 },
	{ "maps\\mp\\gametypes\\_globalentities", 1479 },
	{ "maps\\mp\\gametypes\\_globallogic", 1480 },
	{ "maps\\mp\\gametypes\\_h_unk3", 1481 },
	{ "maps\\mp\\gametypes\\_healthoverlay", 1482 },
	{ "maps\\mp\\gametypes\\_hh_unk4", 1483 },
	{ "maps\\mp\\gametypes\\_hh_unk5", 1484 },
	{ "maps\\mp\\gametypes\\_hh_unk6", 1485 },
	{ "maps\\mp\\gametypes\\_hostmigration", 1486 },
	{ "maps\\mp\\gametypes\\_hud", 1487 },
	{ "maps\\mp\\gametypes\\_hud_message", 1488 },
	{ "maps\\mp\\gametypes\\_hud_util", 1489 },
	{ "maps\\mp\\gametypes\\_i_unk7", 1490 },
	{ "maps\\mp\\gametypes\\_i_unk8", 1491 },
	{ "maps\\mp\\gametypes\\_killcam", 1492 },
	{ "maps\\mp\\gametypes\\_menus", 1493 },
	{ "maps\\mp\\gametypes\\_missions", 1494 },
	{ "maps\\mp\\gametypes\\_music_and_dialog", 1495 },
	{ "maps\\mp\\gametypes\\_objpoints", 1496 },
	{ "maps\\mp\\gametypes\\_p_unk9", 1497 },
	{ "maps\\mp\\gametypes\\_persistence", 1498 },
	{ "maps\\mp\\gametypes\\_pl_unk10", 1499 },
	{ "maps\\mp\\gametypes\\_playerlogic", 1500 },
	{ "maps\\mp\\gametypes\\_rank", 1501 },
	{ "maps\\mp\\gametypes\\_serversettings", 1502 },
	{ "maps\\mp\\gametypes\\_shellshock", 1503 },
	{ "maps\\mp\\gametypes\\_spawn_unk1", 1504 },
	{ "maps\\mp\\gametypes\\_spawnlogic", 1505 },
	{ "maps\\mp\\gametypes\\_spawn_unk2", 1506 },
	{ "maps\\mp\\gametypes\\_spectating", 1507 },
	{ "maps\\mp\\gametypes\\_teams", 1508 },
	{ "maps\\mp\\gametypes\\_tm_unk11", 1509 },
	{ "maps\\mp\\gametypes\\_tweakables", 1510 },
	{ "maps\\mp\\gametypes\\_weapons", 1511 },
// maps/mp/killstreaks
	{ "maps\\mp\\killstreaks\\__unk1", 1512 },
	{ "maps\\mp\\killstreaks\\__unk2", 1513 },
	{ "maps\\mp\\killstreaks\\__unk3", 1514 },
	{ "maps\\mp\\killstreaks\\__unk4", 1515 },
	// 1516-70 killstreaks
// maps/mp/perks
	{ "maps\\mp\\perks\\_perkfunctions", 1571 },
	{ "maps\\mp\\perks\\_perks", 1572 },


// onslaugh dlc
	{ "destructible_scripts\\toy_wall_fan", 36603 },
	{ "destructible_scripts\\vehicle_pickup", 36604 },
	{ "maps\\createart\\mp_alien_armory_art", 36605 },
	{ "maps\\createart\\mp_alien_armory_fog", 36606 },
	{ "maps\\createart\\mp_boneyard_ns_art", 36607 },
	{ "maps\\createart\\mp_boneyard_ns_fog", 36608 },
	{ "maps\\createart\\mp_ca_red_river_art", 36609 },
	{ "maps\\createart\\mp_ca_red_river_fog", 36610 },
	{ "maps\\createart\\mp_ca_rumble_art", 36611 },
	{ "maps\\createart\\mp_ca_rumble_fog", 36612 },
	{ "maps\\createart\\mp_swamp_art", 36613 },
	{ "maps\\createart\\mp_swamp_fog", 36614 },
	{ "maps\\cretaefx\\mp_alien_armory_fx", 36615 },
	{ "maps\\createfx\\mp_boneyard_ns_fx", 36616 },
	{ "maps\\createfx\\mp_ca_red_river_fx", 36617 },
	{ " maps\\createfx\\mp_ca_rumble_fx", 36618 },
	{ "maps\\createfx\\mp_swamp_fx", 36619 },
	// { "maps\\mp\\dlc_unk", 36620 },
	{ "maps\\mp\\mp_alien_armory_fx", 36621 },
	{ "maps\\mp\\mp_alien_armory_precache", 36622 },
	{ "maps\\mp\\mp_boneyard_ns_fx", 36623 },
	{ "maps\\mp\\mp_boneyard_ns_precache", 36624 },
	{ "maps\\mp\\mp_ca_red_river_fx", 36625 },
	{ "maps\\mp\\mp_ca_red_river_precache", 36626 },
	{ "maps\\mp\\mp_ca_rumble_fx", 36627 },
	{ "maps\\mp\\mp_ca_rumble_precache", 36628 },
	{ "maps\\mp\\mp_swamp_fx", 36629 },
	{ "maps\\mp\\mp_swamp_precache", 36630 },
	// 36631-44, effects?
};

std::unordered_map <std::string, std::uint16_t> resolver::token_map
{
	{ "origin", 430 },
	{ "pers", 450 },
	{ "team", 643 },

	{ "_effect", 1644 },
	{ "CreateStruct", 8482 },
	{ "init", 17631 },
	{ "main", 20445 },
	{ "InitStructs", 18005 },

	{ "setupMiniMap", 29184 },

	{ "struct", 31988 },

	{ "gameType", 14086 },
	{ "splitscreen", 31068 },
	{ "initializeMatchRules", 17960 },
	{ "reInitializeMatchRulesOnMigration", 25726 },

	{ "onPrecacheGameType", 22892 },
	{ "onStartGameType", 22905 },
	{ "getSpawnPoint", 15341 },
	{ "onSpawnPlayer", 22902 },
	{ "onPlayerKilled", 22886 },
	{ "checkAllowSpectating", 7057 },

	{ "CodeCallback_StartGameType", 7654 },
	{ "CodeCallback_PlayerConnect", 7648 },
	{ "CodeCallback_PlayerDisconnect", 7650 },
	{ "CodeCallback_PlayerDamage", 7649 },
	{ "CodeCallback_PlayerKilled", 7651 },
	{ "CodeCallback_VehicleDamage", 7655 },
	{ "CodeCallback_CodeEndGame", 7645 },
	{ "CodeCallback_PlayerLastStand", 7652 },
	{ "CodeCallback_PlayerMigrated", 7653 },
	{ "CodeCallback_HostMigration", 7646 },
	{ "SetupDamageFlags", 29170 },
	{ "SetupCallbacks", 29168 },
	{ "SetDefaultCallbacks", 28693 },
	{ "AbortLevel", 1983 },
	{ "callbackVoid", 6492 },
	{ "gametypestarted", 14087 },
	{ "callbackStartGameType", 6491 },
	{ "callbackPlayerConnect", 6484 },
	{ "callbackPlayerDisconnect", 6486 },
	{ "callbackPlayerDamage", 6485 },
	{ "callbackPlayerKilled", 6487 },
	{ "damageCallback", 8960 },
	{ "callbackCodeEndGame", 6482 },
	{ "callbackPlayerLastStand", 6488 },
	{ "callbackPlayerMigrated", 6489 },
	{ "callbackHostMigration", 6483 },
	{ "Callback_StartGameType", 6480 },
	{ "Callback_PlayerConnect", 6471 },
	{ "Callback_PlayerDisconnect", 6474 },
	{ "Callback_PlayerDamage", 6472 },
	{ "Callback_PlayerKilled", 6475 },
	{ "Callback_CodeEndGame", 6468 },
	{ "Callback_PlayerLastStand", 6476 },
	{ "Callback_PlayerMigrated", 6479 },
	{ "Callback_HostMigration", 6469 },
	{ "iDFLAGS_RADIUS", 17344 },
	{ "iDFLAGS_NO_ARMOR", 17338 },
	{ "iDFLAGS_NO_KNOCKBACK", 17339 },
	{ "iDFLAGS_PENETRATION", 17343 },
	{ "iDFLAGS_STUN", 17348 },
	{ "iDFLAGS_SHIELD_EXPLOSIVE_IMPACT", 17345 },
	{ "iDFLAGS_SHIELD_EXPLOSIVE_IMPACT_HUGE", 17346 },
	{ "iDFLAGS_SHIELD_EXPLOSIVE_SPLASH", 17347 },
	{ "iDFLAGS_NO_TEAM_PROTECTION", 17341 },
	{ "iDFLAGS_NO_PROTECTION", 17340 },
	{ "iDFLAGS_PASSTHRU", 17342 },
	
};

} // namespace IW6
