#line 1 "lexer.cpp"
#include "stdafx.hpp"
#include "iw8.hpp"
#include "parser.hpp"
using namespace xsk::gsc;
void iw8_push_header(xsk::gsc::context* ctx, const std::string& file);
void iw8_pop_header(xsk::gsc::context* ctx);

#line 9 "lexer.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define iw8__create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer iw8__create_buffer
#endif

#ifdef yy_delete_buffer
#define iw8__delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer iw8__delete_buffer
#endif

#ifdef yy_scan_buffer
#define iw8__scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer iw8__scan_buffer
#endif

#ifdef yy_scan_string
#define iw8__scan_string_ALREADY_DEFINED
#else
#define yy_scan_string iw8__scan_string
#endif

#ifdef yy_scan_bytes
#define iw8__scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes iw8__scan_bytes
#endif

#ifdef yy_init_buffer
#define iw8__init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer iw8__init_buffer
#endif

#ifdef yy_flush_buffer
#define iw8__flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer iw8__flush_buffer
#endif

#ifdef yy_load_buffer_state
#define iw8__load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state iw8__load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define iw8__switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer iw8__switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define iw8_push_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state iw8_push_buffer_state
#endif

#ifdef yypop_buffer_state
#define iw8_pop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state iw8_pop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define iw8_ensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack iw8_ensure_buffer_stack
#endif

#ifdef yylex
#define iw8_lex_ALREADY_DEFINED
#else
#define yylex iw8_lex
#endif

#ifdef yyrestart
#define iw8_restart_ALREADY_DEFINED
#else
#define yyrestart iw8_restart
#endif

#ifdef yylex_init
#define iw8_lex_init_ALREADY_DEFINED
#else
#define yylex_init iw8_lex_init
#endif

#ifdef yylex_init_extra
#define iw8_lex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra iw8_lex_init_extra
#endif

#ifdef yylex_destroy
#define iw8_lex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy iw8_lex_destroy
#endif

#ifdef yyget_debug
#define iw8_get_debug_ALREADY_DEFINED
#else
#define yyget_debug iw8_get_debug
#endif

#ifdef yyset_debug
#define iw8_set_debug_ALREADY_DEFINED
#else
#define yyset_debug iw8_set_debug
#endif

#ifdef yyget_extra
#define iw8_get_extra_ALREADY_DEFINED
#else
#define yyget_extra iw8_get_extra
#endif

#ifdef yyset_extra
#define iw8_set_extra_ALREADY_DEFINED
#else
#define yyset_extra iw8_set_extra
#endif

#ifdef yyget_in
#define iw8_get_in_ALREADY_DEFINED
#else
#define yyget_in iw8_get_in
#endif

#ifdef yyset_in
#define iw8_set_in_ALREADY_DEFINED
#else
#define yyset_in iw8_set_in
#endif

#ifdef yyget_out
#define iw8_get_out_ALREADY_DEFINED
#else
#define yyget_out iw8_get_out
#endif

#ifdef yyset_out
#define iw8_set_out_ALREADY_DEFINED
#else
#define yyset_out iw8_set_out
#endif

#ifdef yyget_leng
#define iw8_get_leng_ALREADY_DEFINED
#else
#define yyget_leng iw8_get_leng
#endif

#ifdef yyget_text
#define iw8_get_text_ALREADY_DEFINED
#else
#define yyget_text iw8_get_text
#endif

#ifdef yyget_lineno
#define iw8_get_lineno_ALREADY_DEFINED
#else
#define yyget_lineno iw8_get_lineno
#endif

#ifdef yyset_lineno
#define iw8_set_lineno_ALREADY_DEFINED
#else
#define yyset_lineno iw8_set_lineno
#endif

#ifdef yyget_column
#define iw8_get_column_ALREADY_DEFINED
#else
#define yyget_column iw8_get_column
#endif

#ifdef yyset_column
#define iw8_set_column_ALREADY_DEFINED
#else
#define yyset_column iw8_set_column
#endif

#ifdef yywrap
#define iw8_wrap_ALREADY_DEFINED
#else
#define yywrap iw8_wrap
#endif

#ifdef yyalloc
#define iw8_alloc_ALREADY_DEFINED
#else
#define yyalloc iw8_alloc
#endif

#ifdef yyrealloc
#define iw8_realloc_ALREADY_DEFINED
#else
#define yyrealloc iw8_realloc
#endif

#ifdef yyfree
#define iw8_free_ALREADY_DEFINED
#else
#define yyfree iw8_free
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin , yyscanner )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart ( FILE *input_file , yyscan_t yyscanner );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size , yyscan_t yyscanner );
void yy_delete_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yy_flush_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
void yypop_buffer_state ( yyscan_t yyscanner );

static void yyensure_buffer_stack ( yyscan_t yyscanner );
static void yy_load_buffer_state ( yyscan_t yyscanner );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file , yyscan_t yyscanner );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER , yyscanner)

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len , yyscan_t yyscanner );

void *yyalloc ( yy_size_t , yyscan_t yyscanner );
void *yyrealloc ( void *, yy_size_t , yyscan_t yyscanner );
void yyfree ( void * , yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define iw8_wrap(yyscanner) (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state ( yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  , yyscan_t yyscanner);
static int yy_get_next_buffer ( yyscan_t yyscanner );
static void yynoreturn yy_fatal_error ( const char* msg , yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;
#define YY_NUM_RULES 113
#define YY_END_OF_BUFFER 114
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[346] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,  114,  112,
        1,    2,   97,  112,  112,   96,  100,  112,   57,   58,
       94,   92,   63,   93,   64,   95,  111,  111,   66,   67,
       81,   91,   82,   68,  103,  103,   61,   62,  101,  103,
      103,  103,  103,  103,  103,  103,  103,  103,  103,  103,
      103,  103,  103,  103,  103,   59,   99,   60,   98,    5,
        6,    5,   12,   13,   12,  112,   94,   95,   78,    0,
      105,    0,   15,    0,    0,    0,    0,   87,    0,   76,
        0,   89,    0,    0,    8,   85,   69,   83,   70,   84,
      107,    0,   11,    4,    3,   86,  107,  111,  108,    0,

        0,    0,    0,   65,   73,   79,   77,   80,   74,  103,
      103,   90,  103,  103,  103,  103,  103,  103,   29,  103,
      103,  103,  103,  103,   27,   33,  103,  103,  103,  103,
      103,  103,  103,  103,  103,  103,  103,   88,   75,    7,
       14,   10,    9,    0,  105,    0,    0,    0,    0,    0,
        0,  104,    0,    0,    0,    0,  105,    0,  107,    0,
        3,  107,  107,  108,  109,  110,  102,   71,   72,  103,
      103,  103,  103,  103,  103,  103,  103,  103,  103,  103,
      103,   31,  103,  103,  103,  103,  103,  103,  103,  103,
      103,  103,  103,  103,  103,  106,    0,    0,    0,    0,

        0,  104,    0,    0,  104,    0,    0,  103,  103,   53,
      103,   46,   35,  103,  103,  103,   28,  103,  103,  103,
       51,  103,  103,  103,  103,   52,  103,  103,  103,   47,
      103,   22,  103,    0,    0,    0,    0,    0,   50,  103,
      103,   37,  103,  103,  103,   20,   48,  103,   54,  103,
      103,  103,  103,  103,  103,  103,  103,  103,   30,    0,
        0,    0,    0,    0,  103,   56,  103,  103,  103,  103,
      103,   21,  103,  103,   39,   34,  103,   43,  103,  103,
      103,  106,    0,    0,   16,    0,  103,  103,  103,  103,
       36,   32,  103,  103,  103,  103,  103,  103,    0,   17,

        0,  103,  103,  103,   38,  103,   42,  103,  103,  103,
       23,   19,    0,   55,  103,  103,  103,  103,   49,   26,
      103,  103,    0,   40,  103,   41,   45,  103,  103,    0,
       44,  103,  103,    0,  103,  103,    0,  103,   24,    0,
      103,   18,  103,   25,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   29,   28,   30,   31,   32,
       33,   33,   34,   33,   33,   33,   33,   35,   33,   33,
       33,   36,   37,   38,   39,   33,   33,   40,   33,   33,
       41,   42,   43,   44,   45,    1,   46,   47,   48,   49,

       50,   51,   52,   53,   54,   33,   55,   56,   57,   58,
       59,   60,   33,   61,   62,   63,   64,   65,   66,   40,
       67,   68,   69,   70,   71,   72,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[73] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    4,    5,    5,    5,
        5,    1,    1,    1,    1,    1,    1,    5,    5,    5,
        5,    5,    6,    6,    6,    6,    6,    6,    6,    6,
        1,    7,    1,    1,    6,    5,    5,    5,    5,    5,
        5,    6,    6,    8,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    8,    6,    6,    6,    6,    1,    1,
        1,    1
    } ;

static const flex_int16_t yy_base[366] =
    {   0,
        0,    0,   70,   71,   72,   73,   74,   75,  763,  764,
      764,  764,  737,   72,   67,  736,   80,   81,  764,  764,
       76,   81,  764,   82,   90,  110,   99,  124,  738,  764,
       71,  734,   73,  764,  716,   87,  764,  764,  732,   90,
       92,  105,  112,  114,   91,   58,  118,   88,  115,  117,
      123,  125,  126,  119,  139,  764,  138,  764,  764,  764,
      764,  739,  764,  764,  738,  165,  729,  177,  764,  179,
      764,  183,  764,    0,  695,  694,  689,  764,  185,  764,
       94,  764,  184,  192,  764,  764,  764,  764,  764,  764,
      179,  696,  764,  764,    0,  764,  185,  196,  221,  180,

      191,  248,    0,  764,  724,  764,  764,  764,  723,  705,
      223,  764,  178,  181,  193,  202,  201,  203,  704,  186,
      208,   70,  209,  205,  703,  702,   60,  210,  216,  218,
      229,  246,  247,  182,  242,  250,  251,  764,  764,  764,
      764,  764,  764,  269,  277,  304,    0,  689,  254,  688,
      278,  764,  309,  294,  312,  297,  307,  314,  764,  673,
        0,  306,  764,  313,  319,    0,  698,  764,  764,  310,
      286,  288,  298,  306,  300,  311,  301,  317,  316,  323,
      326,  327,  328,  329,  330,  332,  331,  334,  333,  338,
      339,  344,  348,  345,  349,    0,  682,  682,  683,  678,

      387,  388,  394,  392,  393,  400,  685,  372,  368,  692,
      364,  691,  690,  369,  370,  373,  689,  375,  371,  374,
      688,  383,  380,  396,  384,  687,  398,  385,  401,  686,
      402,  407,  409,    0,  664,  662,  667,  672,  764,  418,
      419,  413,  412,  420,  415,  681,  680,  426,  679,  414,
      435,  421,  423,  438,  441,  442,  425,  445,  678,    0,
      658,  669,  667,  671,  453,  673,  447,  450,  451,  455,
      452,  672,  458,  456,  671,  670,  459,  669,  465,  467,
      460,  764,  660,  659,  764,  662,  479,  470,  475,  477,
      665,  664,  480,  484,  488,  489,  483,  486,  655,  764,

      646,  504,  493,  495,  661,  501,  643,  502,  505,  499,
      508,  764,  622,  592,  510,  514,  516,  515,  581,  580,
      519,  520,  537,  551,  521,  550,  549,  525,  526,  527,
      544,  527,  530,  521,  533,  534,  454,  535,  424,  414,
      537,  764,  539,  386,  764,  595,  603,  611,  616,  624,
      630,  634,  642,  313,  650,  658,  666,  674,  678,  308,
      686,  694,  282,  213,  208
    } ;

static const flex_int16_t yy_def[366] =
    {   0,
      345,    1,  346,  346,  347,  347,    1,    1,  345,  345,
      345,  345,  345,  348,  349,  345,  345,  350,  345,  345,
      345,  345,  345,  345,  345,  345,  351,  351,  345,  345,
      345,  345,  345,  345,  352,  352,  345,  345,  345,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  349,  345,  345,  345,  348,
      345,  353,  345,  354,  354,  345,  345,  345,  355,  345,
      356,  345,  350,  357,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  358,  345,  345,  351,  351,  351,

      351,  351,  359,  345,  345,  345,  345,  345,  345,  352,
      352,  345,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  345,  345,  345,
      345,  345,  345,  348,  348,  353,  360,  345,  345,  345,
      355,  345,  361,  356,  362,  350,  350,  357,  345,  345,
      358,  345,  345,  351,  351,  102,  359,  345,  345,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  363,  345,  345,  345,  345,

      355,  355,  361,  356,  356,  362,  345,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  364,  345,  345,  345,  345,  345,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  365,
      345,  345,  345,  345,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  345,  345,  345,  345,  345,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  345,  345,

      345,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  345,  345,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  345,  352,  352,  352,  352,  352,  352,  345,
      352,  352,  352,  345,  352,  352,  345,  352,  352,  345,
      352,  345,  352,  352,    0,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345
    } ;

static const flex_int16_t yy_nxt[837] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   28,
       28,   29,   30,   31,   32,   33,   34,   35,   35,   35,
       35,   35,   35,   36,   35,   35,   35,   35,   35,   35,
       37,   10,   38,   39,   35,   40,   41,   42,   43,   44,
       45,   46,   35,   47,   35,   48,   35,   49,   35,   50,
       51,   52,   53,   54,   35,   55,   35,   35,   56,   57,
       58,   59,   61,   61,   64,   64,   71,   65,   65,   66,
       66,   62,   62,   73,   79,   67,   67,   80,   81,   71,
       68,   68,   85,   87,  105,  106,   89,  108,  109,  103,

       86,  103,  152,  124,   82,   88,   90,   91,   91,   91,
       91,  103,   75,   72,   97,   93,   98,   99,   99,   98,
       76,   94,   84,  111,  184,  181,   95,  101,  103,  103,
       77,  103,  103,  103,   96,  155,  122,  127,  102,   97,
      103,   98,   98,   98,   98,  101,  103,  113,  111,  123,
      115,   92,  114,  103,  111,  103,  103,  116,  103,  103,
      103,  118,  138,  117,  103,  103,  103,  103,  125,  120,
      119,  121,  130,  128,  131,  126,  135,  129,  133,  111,
      103,  142,  143,   71,  136,   70,  134,  145,   94,  152,
      132,  137,   71,   95,   83,  345,   91,   91,   91,   91,

      157,   96,  162,  162,  162,  162,  345,  139,  165,  165,
       75,   97,  282,   98,   98,   98,   98,  260,   76,  103,
       72,  103,  103,  103,  146,   84,  153,  103,   77,  159,
      173,  172,  103,  158,  103,  163,   97,  103,  164,  164,
      164,   98,  103,  103,  103,  192,  103,  179,  174,  103,
      103,  103,  170,  178,  175,  176,  180,  103,  177,  103,
      171,  183,  103,  345,  103,  166,  166,  166,  166,  182,
      103,  170,  185,   71,  186,  166,  166,  166,  166,  166,
      187,   71,  152,  103,  188,  171,  234,  103,  103,  103,
      193,  103,  103,  166,  166,  166,  166,  166,  166,  189,

      190,  198,  152,  194,  195,   71,   70,  191,  145,  199,
       72,  151,  196,  202,  154,   71,   83,  147,   72,  153,
      205,  209,  157,  162,  162,  162,  162,  103,   97,  103,
      164,  164,  164,   98,  345,  155,  165,  165,   84,  103,
      208,  103,  103,  211,  210,  146,  209,  103,   84,  213,
      203,  103,  103,  206,  103,  158,  163,  103,  103,  208,
      103,  212,  216,  215,  103,  217,  214,  103,  103,  103,
      103,  103,  103,  103,  103,  103,  220,  221,  222,  103,
      103,  218,  224,  223,  226,  103,  103,  219,  229,  103,
      103,  152,  152,  230,  225,  227,  151,  231,  202,  228,

      152,  152,  154,  240,  233,  103,  241,  232,  205,  103,
      103,  103,  103,  103,  103,  103,  103,  243,  242,  248,
      247,  103,  240,  244,  103,  103,  103,  103,  153,  153,
      250,  241,  246,  155,  155,  203,  245,  103,  249,  103,
      251,  206,  103,  103,  252,  253,  255,  254,  103,  266,
      103,  265,  256,  103,  103,  103,  103,  257,  259,  103,
      103,  103,  103,  342,  103,  103,  103,  103,  266,  258,
      270,  265,  267,  271,  268,  276,  103,  269,  275,  103,
      272,  273,  103,  103,  274,  280,  103,  287,  103,  278,
      277,  103,  103,  103,  103,  279,  103,  103,  281,  103,

      103,  103,  289,  340,  292,  288,  103,  293,  103,  302,
      287,  103,  297,  294,  290,  298,  103,  291,  103,  295,
      103,  103,  296,  303,  103,  103,  305,  103,  302,  103,
      103,  306,  307,  314,  103,  304,  103,  308,  309,  310,
      103,  311,  103,  103,  316,  103,  103,  318,  320,  103,
      315,  103,  314,  319,  317,  103,  103,  103,  321,  325,
      103,  103,  103,  327,  322,  329,  103,  103,  103,  331,
      332,  103,  324,  326,  103,  103,  103,  336,  103,  328,
      103,  337,  338,  335,  341,  103,  339,  344,  333,  334,
      103,  103,  103,  330,  343,   60,   60,   60,   60,   60,

       60,   60,   60,   63,   63,   63,   63,   63,   63,   63,
       63,   70,   70,   70,   70,   70,   70,   70,   70,   74,
       74,  103,  103,   74,   83,   83,   83,   83,   83,   83,
       83,   83,  100,  103,  100,  100,  100,  100,  110,  110,
      110,  110,  144,  144,  144,  144,  144,  144,  144,  144,
      151,  151,  151,  151,  151,  151,  151,  151,  154,  154,
      154,  154,  154,  154,  154,  154,  156,  156,  156,  156,
      156,  156,  156,  156,  161,  323,  161,  161,  161,  161,
      161,  161,  167,  167,  103,  167,  201,  201,  201,  201,
      201,  201,  201,  201,  204,  204,  204,  204,  204,  204,

      204,  204,  103,  313,  312,  103,  103,  301,  300,  299,
      103,  103,  103,  103,  103,  286,  285,  284,  283,  103,
      103,  103,  103,  264,  263,  262,  261,  103,  103,  103,
      103,  103,  103,  103,  239,  238,  237,  236,  235,  103,
      207,  200,  197,  103,  103,  103,  103,  169,  168,  160,
      150,  149,  148,   86,  141,  140,  112,  103,  107,  104,
       78,   69,  345,    9,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,

      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345
    } ;

static const flex_int16_t yy_chk[837] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    5,    6,   14,    5,    6,    7,
        8,    3,    4,   15,   17,    7,    8,   17,   17,   18,
        7,    8,   21,   22,   31,   31,   24,   33,   33,   46,

       21,  127,   81,   46,   17,   22,   24,   25,   25,   25,
       25,  122,   15,   14,   27,   26,   27,   27,   27,   27,
       15,   26,   18,   36,  127,  122,   26,   27,   36,   48,
       15,   40,   45,   41,   26,   81,   45,   48,   27,   28,
       27,   28,   28,   28,   28,   27,   42,   40,   36,   45,
       42,   25,   41,   43,   47,   44,   49,   42,   50,   47,
       54,   43,   57,   42,   51,   28,   52,   53,   47,   44,
       43,   44,   51,   49,   52,   47,   54,   50,   53,   47,
       55,   66,   68,   70,   55,   72,   53,   72,   68,   79,
       52,   55,   83,   68,   84,  100,   91,   91,   91,   91,

       84,   68,   97,   97,   97,   97,  101,   57,  101,  101,
       66,   98,  365,   98,   98,   98,   98,  364,   66,  113,
       70,  100,  114,  134,   72,   83,   79,  120,   66,   91,
      114,  113,  101,   84,  115,   97,   99,   98,   99,   99,
       99,   99,  117,  116,  118,  134,  124,  120,  115,  121,
      123,  128,  111,  118,  115,  116,  121,  129,  117,  130,
      111,  124,   99,  102,  111,  102,  102,  102,  102,  123,
      131,  111,  128,  144,  129,  102,  102,  102,  102,  102,
      130,  145,  151,  135,  131,  111,  363,  132,  133,  102,
      135,  136,  137,  102,  102,  102,  102,  102,  102,  132,

      133,  149,  154,  136,  137,  156,  146,  133,  146,  149,
      144,  153,  360,  153,  155,  157,  158,  354,  145,  151,
      155,  171,  158,  162,  162,  162,  162,  171,  164,  172,
      164,  164,  164,  164,  165,  154,  165,  165,  156,  173,
      170,  175,  177,  173,  172,  146,  171,  174,  157,  175,
      153,  170,  176,  155,  164,  158,  162,  179,  178,  170,
      165,  174,  178,  177,  180,  179,  176,  181,  182,  183,
      184,  185,  187,  186,  189,  188,  182,  183,  184,  190,
      191,  180,  186,  185,  188,  192,  194,  181,  191,  193,
      195,  201,  202,  192,  187,  189,  203,  193,  203,  190,

      204,  205,  206,  208,  195,  211,  209,  194,  206,  209,
      214,  215,  219,  208,  216,  220,  218,  214,  211,  220,
      219,  223,  208,  215,  222,  225,  228,  344,  201,  202,
      223,  209,  218,  204,  205,  203,  216,  224,  222,  227,
      224,  206,  229,  231,  225,  227,  229,  228,  232,  241,
      233,  240,  231,  243,  242,  250,  245,  232,  233,  240,
      241,  244,  252,  340,  253,  339,  257,  248,  241,  232,
      245,  240,  242,  248,  243,  253,  251,  244,  252,  254,
      250,  251,  255,  256,  251,  257,  258,  265,  267,  255,
      254,  268,  269,  271,  265,  256,  270,  274,  258,  273,

      277,  281,  268,  337,  271,  267,  279,  273,  280,  287,
      265,  288,  280,  274,  269,  281,  289,  270,  290,  277,
      287,  293,  279,  288,  297,  294,  290,  298,  287,  295,
      296,  293,  294,  302,  303,  289,  304,  295,  296,  297,
      310,  298,  306,  308,  304,  302,  309,  308,  310,  311,
      303,  315,  302,  309,  306,  316,  318,  317,  311,  316,
      321,  322,  325,  318,  311,  322,  328,  329,  332,  325,
      328,  333,  315,  317,  335,  336,  338,  333,  341,  321,
      343,  334,  335,  332,  338,  331,  336,  343,  329,  330,
      327,  326,  324,  323,  341,  346,  346,  346,  346,  346,

      346,  346,  346,  347,  347,  347,  347,  347,  347,  347,
      347,  348,  348,  348,  348,  348,  348,  348,  348,  349,
      349,  320,  319,  349,  350,  350,  350,  350,  350,  350,
      350,  350,  351,  314,  351,  351,  351,  351,  352,  352,
      352,  352,  353,  353,  353,  353,  353,  353,  353,  353,
      355,  355,  355,  355,  355,  355,  355,  355,  356,  356,
      356,  356,  356,  356,  356,  356,  357,  357,  357,  357,
      357,  357,  357,  357,  358,  313,  358,  358,  358,  358,
      358,  358,  359,  359,  307,  359,  361,  361,  361,  361,
      361,  361,  361,  361,  362,  362,  362,  362,  362,  362,

      362,  362,  305,  301,  299,  292,  291,  286,  284,  283,
      278,  276,  275,  272,  266,  264,  263,  262,  261,  259,
      249,  247,  246,  238,  237,  236,  235,  230,  226,  221,
      217,  213,  212,  210,  207,  200,  199,  198,  197,  167,
      160,  150,  148,  126,  125,  119,  110,  109,  105,   92,
       77,   76,   75,   67,   65,   62,   39,   35,   32,   29,
       16,   13,    9,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,

      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      345,  345,  345,  345,  345,  345
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "lexer.lpp"
/* Copyright 2021 xensik. All rights reserved.
//
// Use of this source code is governed by a GNU GPLv3 license
// that can be found in the LICENSE file.
*/
#define YY_NO_INPUT 1
#define YY_NO_UNISTD_H 1

#line 25 "lexer.lpp"
#define YY_USER_ACTION  ctx->loc.columns(yyleng);
#line 951 "lexer.cpp"

#line 953 "lexer.cpp"

#define INITIAL 0
#define COMMENT_STATE 1
#define DEV_OFF_STATE 2
#define DEV_ON_STATE 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    }; /* end struct yyguts_t */

static int yy_init_globals ( yyscan_t yyscanner );

int yylex_init (yyscan_t* scanner);

int yylex_init_extra ( YY_EXTRA_TYPE user_defined, yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( yyscan_t yyscanner );

int yyget_debug ( yyscan_t yyscanner );

void yyset_debug ( int debug_flag , yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra ( yyscan_t yyscanner );

void yyset_extra ( YY_EXTRA_TYPE user_defined , yyscan_t yyscanner );

FILE *yyget_in ( yyscan_t yyscanner );

void yyset_in  ( FILE * _in_str , yyscan_t yyscanner );

FILE *yyget_out ( yyscan_t yyscanner );

void yyset_out  ( FILE * _out_str , yyscan_t yyscanner );

			int yyget_leng ( yyscan_t yyscanner );

char *yyget_text ( yyscan_t yyscanner );

int yyget_lineno ( yyscan_t yyscanner );

void yyset_lineno ( int _line_number , yyscan_t yyscanner );

int yyget_column  ( yyscan_t yyscanner );

void yyset_column ( int _column_no , yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( yyscan_t yyscanner );
#else
extern int yywrap ( yyscan_t yyscanner );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int , yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * , yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( yyscan_t yyscanner );
#else
static int input ( yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (yyscan_t yyscanner);

#define YY_DECL int yylex (yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
		}

		yy_load_buffer_state( yyscanner );
		}

	{
#line 43 "lexer.lpp"



#line 47 "lexer.lpp"
    ctx->loc.step();


#line 1222 "lexer.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 346 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 345 );
		yy_cp = yyg->yy_last_accepting_cpos;
		yy_current_state = yyg->yy_last_accepting_state;

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 50 "lexer.lpp"
{ ctx->loc.step(); }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 51 "lexer.lpp"
{ ctx->loc.lines(yyleng); ctx->loc.step(); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 53 "lexer.lpp"

	YY_BREAK
case 4:
YY_RULE_SETUP
#line 55 "lexer.lpp"
{ BEGIN(COMMENT_STATE); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 56 "lexer.lpp"

	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 57 "lexer.lpp"
{ ctx->loc.lines(yyleng); ctx->loc.step(); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 58 "lexer.lpp"
{ BEGIN(INITIAL); }
	YY_BREAK
case YY_STATE_EOF(COMMENT_STATE):
#line 59 "lexer.lpp"
{ throw iw8::parser::syntax_error(ctx->loc, "unmatched multiline comment start ('/*')"); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 60 "lexer.lpp"
{ throw iw8::parser::syntax_error(ctx->loc, "unmatched multiline comment end ('*/')"); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 62 "lexer.lpp"
{ throw iw8::parser::syntax_error(ctx->loc, "cannot recurse devblock ('/#')"); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 63 "lexer.lpp"
{ BEGIN(INITIAL); return iw8::parser::make_DEVEND(ctx->loc); }
	YY_BREAK
case YY_STATE_EOF(DEV_ON_STATE):
#line 64 "lexer.lpp"
{ throw iw8::parser::syntax_error(ctx->loc, "unmatched devblock start ('/#')"); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 66 "lexer.lpp"
{ BEGIN(ctx->mode == xsk::gsc::build::dev ? DEV_ON_STATE : DEV_OFF_STATE); if(ctx->mode == xsk::gsc::build::dev) return iw8::parser::make_DEVBEGIN(ctx->loc); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 67 "lexer.lpp"

	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 68 "lexer.lpp"
{ ctx->loc.lines(yyleng); ctx->loc.step(); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 69 "lexer.lpp"
{ BEGIN(INITIAL); }
	YY_BREAK
case YY_STATE_EOF(DEV_OFF_STATE):
#line 70 "lexer.lpp"
{ throw iw8::parser::syntax_error(ctx->loc, "unmatched devblock start ('/#')"); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 71 "lexer.lpp"
{ throw iw8::parser::syntax_error(ctx->loc, "unmatched devblock end ('#/')"); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 73 "lexer.lpp"
{ return iw8::parser::make_INLINE(ctx->loc); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 74 "lexer.lpp"
{ return iw8::parser::make_INCLUDE(ctx->loc); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 75 "lexer.lpp"
{ return iw8::parser::make_USINGTREE(ctx->loc); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 76 "lexer.lpp"
{ return iw8::parser::make_ANIMTREE(ctx->loc); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 77 "lexer.lpp"
{ return iw8::parser::make_ENDON(ctx->loc); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 78 "lexer.lpp"
{ return iw8::parser::make_NOTIFY(ctx->loc); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 79 "lexer.lpp"
{ return iw8::parser::make_WAIT(ctx->loc); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 80 "lexer.lpp"
{ return iw8::parser::make_WAITTILL(ctx->loc); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 81 "lexer.lpp"
{ return iw8::parser::make_WAITTILLMATCH(ctx->loc); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 82 "lexer.lpp"
{ return iw8::parser::make_WAITTILLFRAMEEND(ctx->loc); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 83 "lexer.lpp"
{ return iw8::parser::make_WAITFRAME(ctx->loc); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 84 "lexer.lpp"
{ return iw8::parser::make_IF(ctx->loc); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 85 "lexer.lpp"
{ return iw8::parser::make_ELSE(ctx->loc); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 86 "lexer.lpp"
{ return iw8::parser::make_DO(ctx->loc); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 87 "lexer.lpp"
{ return iw8::parser::make_WHILE(ctx->loc); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 88 "lexer.lpp"
{ return iw8::parser::make_FOR(ctx->loc); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 89 "lexer.lpp"
{ return iw8::parser::make_FOREACH(ctx->loc); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 90 "lexer.lpp"
{ return iw8::parser::make_IN(ctx->loc); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 91 "lexer.lpp"
{ return iw8::parser::make_SWITCH(ctx->loc); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 92 "lexer.lpp"
{ return iw8::parser::make_CASE(ctx->loc); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 93 "lexer.lpp"
{ return iw8::parser::make_DEFAULT(ctx->loc); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 94 "lexer.lpp"
{ return iw8::parser::make_BREAK(ctx->loc); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 95 "lexer.lpp"
{ return iw8::parser::make_CONTINUE(ctx->loc); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 96 "lexer.lpp"
{ return iw8::parser::make_RETURN(ctx->loc); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 97 "lexer.lpp"
{ return iw8::parser::make_BREAKPOINT(ctx->loc); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 98 "lexer.lpp"
{ return iw8::parser::make_PROFBEGIN(ctx->loc); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 99 "lexer.lpp"
{ return iw8::parser::make_PROFEND(ctx->loc); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 100 "lexer.lpp"
{ return iw8::parser::make_THREAD(ctx->loc); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 101 "lexer.lpp"
{ return iw8::parser::make_CHILDTHREAD(ctx->loc); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 102 "lexer.lpp"
{ return iw8::parser::make_THISTHREAD(ctx->loc); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 103 "lexer.lpp"
{ return iw8::parser::make_CALL(ctx->loc); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 104 "lexer.lpp"
{ return iw8::parser::make_TRUE(ctx->loc); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 105 "lexer.lpp"
{ return iw8::parser::make_FALSE(ctx->loc); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 106 "lexer.lpp"
{ return iw8::parser::make_UNDEFINED(ctx->loc); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 107 "lexer.lpp"
{ return iw8::parser::make_SIZE(ctx->loc); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 108 "lexer.lpp"
{ return iw8::parser::make_GAME(ctx->loc); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 109 "lexer.lpp"
{ return iw8::parser::make_SELF(ctx->loc); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 110 "lexer.lpp"
{ return iw8::parser::make_ANIM(ctx->loc); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 111 "lexer.lpp"
{ return iw8::parser::make_LEVEL(ctx->loc); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 112 "lexer.lpp"
{ return iw8::parser::make_ISDEFINED(ctx->loc); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 113 "lexer.lpp"
{ return iw8::parser::make_ISTRUE(ctx->loc); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 114 "lexer.lpp"
{ return iw8::parser::make_LPAREN(ctx->loc); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 115 "lexer.lpp"
{ return iw8::parser::make_RPAREN(ctx->loc); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 116 "lexer.lpp"
{ return iw8::parser::make_LBRACE(ctx->loc); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 117 "lexer.lpp"
{ return iw8::parser::make_RBRACE(ctx->loc); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 118 "lexer.lpp"
{ return iw8::parser::make_LBRACKET(ctx->loc); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 119 "lexer.lpp"
{ return iw8::parser::make_RBRACKET(ctx->loc); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 120 "lexer.lpp"
{ return iw8::parser::make_COMMA(ctx->loc); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 121 "lexer.lpp"
{ return iw8::parser::make_DOT(ctx->loc); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 122 "lexer.lpp"
{ return iw8::parser::make_DOUBLECOLON(ctx->loc); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 123 "lexer.lpp"
{ return iw8::parser::make_COLON(ctx->loc); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 124 "lexer.lpp"
{ return iw8::parser::make_SEMICOLON(ctx->loc); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 125 "lexer.lpp"
{ return iw8::parser::make_QMARK(ctx->loc); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 126 "lexer.lpp"
{ return iw8::parser::make_INCREMENT(ctx->loc); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 127 "lexer.lpp"
{ return iw8::parser::make_DECREMENT(ctx->loc); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 128 "lexer.lpp"
{ return iw8::parser::make_ASSIGN_LSHIFT(ctx->loc); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 129 "lexer.lpp"
{ return iw8::parser::make_ASSIGN_RSHIFT(ctx->loc); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 130 "lexer.lpp"
{ return iw8::parser::make_LSHIFT(ctx->loc); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 131 "lexer.lpp"
{ return iw8::parser::make_RSHIFT(ctx->loc); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 132 "lexer.lpp"
{ return iw8::parser::make_OR(ctx->loc); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 133 "lexer.lpp"
{ return iw8::parser::make_AND(ctx->loc); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 134 "lexer.lpp"
{ return iw8::parser::make_EQUALITY(ctx->loc); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 135 "lexer.lpp"
{ return iw8::parser::make_INEQUALITY(ctx->loc); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 136 "lexer.lpp"
{ return iw8::parser::make_LESS_EQUAL(ctx->loc); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 137 "lexer.lpp"
{ return iw8::parser::make_GREATER_EQUAL(ctx->loc); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 138 "lexer.lpp"
{ return iw8::parser::make_LESS(ctx->loc); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 139 "lexer.lpp"
{ return iw8::parser::make_GREATER(ctx->loc); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 140 "lexer.lpp"
{ return iw8::parser::make_ASSIGN_ADD(ctx->loc); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 141 "lexer.lpp"
{ return iw8::parser::make_ASSIGN_SUB(ctx->loc); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 142 "lexer.lpp"
{ return iw8::parser::make_ASSIGN_MUL(ctx->loc); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 143 "lexer.lpp"
{ return iw8::parser::make_ASSIGN_DIV(ctx->loc); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 144 "lexer.lpp"
{ return iw8::parser::make_ASSIGN_MOD(ctx->loc); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 145 "lexer.lpp"
{ return iw8::parser::make_ASSIGN_BW_OR(ctx->loc); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 146 "lexer.lpp"
{ return iw8::parser::make_ASSIGN_BW_AND(ctx->loc); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 147 "lexer.lpp"
{ return iw8::parser::make_ASSIGN_BW_EXOR(ctx->loc); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 148 "lexer.lpp"
{ return iw8::parser::make_ASSIGN(ctx->loc); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 149 "lexer.lpp"
{ return iw8::parser::make_ADD(ctx->loc); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 150 "lexer.lpp"
{ return iw8::parser::make_SUB(ctx->loc); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 151 "lexer.lpp"
{ return iw8::parser::make_MUL(ctx->loc); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 152 "lexer.lpp"
{ return iw8::parser::make_DIV(ctx->loc); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 153 "lexer.lpp"
{ return iw8::parser::make_MOD(ctx->loc); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 154 "lexer.lpp"
{ return iw8::parser::make_NOT(ctx->loc); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 155 "lexer.lpp"
{ return iw8::parser::make_COMPLEMENT(ctx->loc); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 156 "lexer.lpp"
{ return iw8::parser::make_BITWISE_OR(ctx->loc); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 157 "lexer.lpp"
{ return iw8::parser::make_BITWISE_AND(ctx->loc); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 158 "lexer.lpp"
{ return iw8::parser::make_BITWISE_EXOR(ctx->loc); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 159 "lexer.lpp"
{ return iw8::parser::make_PATH(xsk::utils::string::fordslash(yytext), ctx->loc); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 160 "lexer.lpp"
{ return iw8::parser::make_IDENTIFIER((std::string(yytext, 3) == "_ID") ? std::string(yytext) : xsk::utils::string::to_lower(yytext), ctx->loc); }
	YY_BREAK
case 104:
/* rule 104 can match eol */
YY_RULE_SETUP
#line 161 "lexer.lpp"
{ return iw8::parser::make_ISTRING(std::string(yytext).substr(1), ctx->loc); }
	YY_BREAK
case 105:
/* rule 105 can match eol */
YY_RULE_SETUP
#line 162 "lexer.lpp"
{ return iw8::parser::make_STRING(std::string(yytext), ctx->loc); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 163 "lexer.lpp"
{ return iw8::parser::make_COLOR(std::string(yytext).substr(1), ctx->loc); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 164 "lexer.lpp"
{ return iw8::parser::make_FLOAT(std::string(yytext), ctx->loc); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 165 "lexer.lpp"
{ return iw8::parser::make_INT_OCT(xsk::utils::string::oct_to_dec(yytext), ctx->loc); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 166 "lexer.lpp"
{ return iw8::parser::make_INT_BIN(xsk::utils::string::bin_to_dec(yytext), ctx->loc); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 167 "lexer.lpp"
{ return iw8::parser::make_INT_HEX(xsk::utils::string::hex_to_dec(yytext), ctx->loc); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 168 "lexer.lpp"
{ return iw8::parser::make_INT_DEC(std::string(yytext), ctx->loc); }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 169 "lexer.lpp"
{ if(ctx->header_top > 0) iw8_pop_header(ctx); else return iw8::parser::make_IW8EOF(ctx->loc); }
	YY_BREAK
case 112:
/* rule 112 can match eol */
YY_RULE_SETUP
#line 170 "lexer.lpp"
{ throw iw8::parser::syntax_error(ctx->loc, "bad token: \'" + std::string(yytext) + "\'"); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 172 "lexer.lpp"
ECHO;
	YY_BREAK
#line 1862 "lexer.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_last_accepting_cpos;
				yy_current_state = yyg->yy_last_accepting_state;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap( yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  , yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size , yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 346 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	char *yy_cp = yyg->yy_c_buf_p;

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 346 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 345);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr);
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin , yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file , yyscanner);
	yy_load_buffer_state( yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file , yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf , yyscanner );

	yyfree( (void *) b , yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer( b , yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER , yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b , yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) , yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n , yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n , yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param _line_number line number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  _line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_lineno called with no buffer" );
    
    yylineno = _line_number;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_column called with no buffer" );
    
    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

void yyset_out (FILE *  _out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = _out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  _bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = _bdebug ;
}

/* Accessor methods for yylval and yylloc */

/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */
int yylex_init(yyscan_t* ptr_yy_globals)
{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */
int yylex_init_extra( YY_EXTRA_TYPE yy_user_defined, yyscan_t* ptr_yy_globals )
{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    yyset_extra (yy_user_defined, *ptr_yy_globals);

    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = NULL;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = NULL;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER , yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack , yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree( yyg->yy_start_stack , yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 172 "lexer.lpp"


void iw8_push_header(xsk::gsc::context* ctx, const std::string& file)
{
	try
    {
		if (ctx->header_top >= 4)
		{
			throw xsk::gsc::error("maximum gsh depth exceeded '4'");
		}

		ctx->header_top++;

		char* buf_data = 0;
		size_t buf_size = 0;

		for (auto& src : *ctx->sources)
		{
			if (src.name == file)
			{
				buf_data = reinterpret_cast<char*>(src.buf.data());
				buf_size = src.buf.size();

				ctx->locs.push(ctx->loc);
				ctx->loc.initialize(&src.name);
			}
		}

		if (buf_data == 0)
		{
			ctx->sources->push_back(xsk::gsc::source());
			auto& source = ctx->sources->back();
			source.name = file;
			source.buf = ctx->read_callback(file + ".gsh");
			source.buf.push_back(0);
			source.buf.push_back(0);

			buf_data = reinterpret_cast<char*>(source.buf.data());
			buf_size = source.buf.size();

			ctx->locs.push(ctx->loc);
			ctx->loc.initialize(&source.name);
		}

		auto state = new yy_buffer_state();
		state->yy_buf_size = buf_size - 2;
		state->yy_buf_pos = state->yy_ch_buf = buf_data;
		state->yy_is_our_buffer = 0;
		state->yy_input_file = NULL;
		state->yy_n_chars = state->yy_buf_size;
		state->yy_is_interactive = 0;
		state->yy_at_bol = 1;
		state->yy_fill_buffer = 0;
		state->yy_buffer_status = 0;

		yypush_buffer_state(state, ctx->scanner);
	}
	catch (const std::exception& e)
    {
        throw xsk::gsc::error("parsing header file '" + file + "': " + e.what());
    }
}

void iw8_pop_header(xsk::gsc::context* ctx)
{
	ctx->header_top--;
	ctx->loc = ctx->locs.top();
	ctx->locs.pop();
	yypop_buffer_state(ctx->scanner);
}

