// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
/*QUAKED actor_ally_ac130_delta_ucp_M16 (0.0 0.25 1.0) (-16 -16 0) (16 16 72) SPAWNER FORCESPAWN UNDELETABLE PERFECTENEMYINFO DONTSHAREENEMYINFO
defaultmdl="body_delta_urban_assault_aa"
"count" -- max AI to ever spawn from this spawner
SPAWNER -- makes this a spawner instead of a guy
FORCESPAWN -- will try to delete an AI if spawning fails from too many AI
UNDELETABLE -- this AI (or AI spawned from here) cannot be deleted to make room for FORCESPAWN guys
PERFECTENEMYINFO -- this AI when spawned will get a snapshot of perfect info about all enemies
DONTSHAREENEMYINFO -- do not get shared info about enemies at spawn time from teammates
*/
main()
{
	self.animTree = "";
	self.additionalAssets = "";
	self.team = "allies";
	self.type = "human";
	self.subclass = "regular";
	self.accuracy = 0.2;
	self.health = 100;
	self.secondaryweapon = "";
	self.sidearm = "beretta";
	self.grenadeWeapon = "fraggrenade";
	self.grenadeAmmo = 0;

	if ( isAI( self ) )
	{
		self setEngagementMinDist( 256.000000, 0.000000 );
		self setEngagementMaxDist( 768.000000, 1024.000000 );
	}

	switch( codescripts\character::get_random_weapon(3) )
	{
	case 0:
		self.weapon = "m16_basic";
		break;
	case 1:
		self.weapon = "m16_acog";
		break;
	case 2:
		self.weapon = "m16_grenadier";
		break;
	}

	switch( codescripts\character::get_random_character(4) )
	{
	case 0:
		character\character_delta_elite_assault_aa::main();
		break;
	case 1:
		character\character_delta_elite_assault_ab::main();
		break;
	case 2:
		character\character_delta_elite_assault_ba::main();
		break;
	case 3:
		character\character_delta_elite_assault_bb::main();
		break;
	}
}

spawner()
{
	self setspawnerteam("allies");
}

precache()
{
	character\character_delta_elite_assault_aa::precache();
	character\character_delta_elite_assault_ab::precache();
	character\character_delta_elite_assault_ba::precache();
	character\character_delta_elite_assault_bb::precache();

	precacheItem("m16_basic");
	precacheItem("m16_acog");
	precacheItem("m16_grenadier");
	precacheItem("m203");
	precacheItem("beretta");
	precacheItem("fraggrenade");
}
