#line 1 "./IW7/compiler_lexer.cpp"
#include "IW7.hpp"
#include "compiler_parser.hpp"
#ifndef YY_NO_UNISTD_H
#define YY_NO_UNISTD_H
#endif

#line 8 "./IW7/compiler_lexer.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define IW7_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer IW7_create_buffer
#endif

#ifdef yy_delete_buffer
#define IW7_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer IW7_delete_buffer
#endif

#ifdef yy_scan_buffer
#define IW7_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer IW7_scan_buffer
#endif

#ifdef yy_scan_string
#define IW7_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string IW7_scan_string
#endif

#ifdef yy_scan_bytes
#define IW7_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes IW7_scan_bytes
#endif

#ifdef yy_init_buffer
#define IW7_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer IW7_init_buffer
#endif

#ifdef yy_flush_buffer
#define IW7_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer IW7_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define IW7_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state IW7_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define IW7_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer IW7_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define IW7push_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state IW7push_buffer_state
#endif

#ifdef yypop_buffer_state
#define IW7pop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state IW7pop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define IW7ensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack IW7ensure_buffer_stack
#endif

#ifdef yylex
#define IW7lex_ALREADY_DEFINED
#else
#define yylex IW7lex
#endif

#ifdef yyrestart
#define IW7restart_ALREADY_DEFINED
#else
#define yyrestart IW7restart
#endif

#ifdef yylex_init
#define IW7lex_init_ALREADY_DEFINED
#else
#define yylex_init IW7lex_init
#endif

#ifdef yylex_init_extra
#define IW7lex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra IW7lex_init_extra
#endif

#ifdef yylex_destroy
#define IW7lex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy IW7lex_destroy
#endif

#ifdef yyget_debug
#define IW7get_debug_ALREADY_DEFINED
#else
#define yyget_debug IW7get_debug
#endif

#ifdef yyset_debug
#define IW7set_debug_ALREADY_DEFINED
#else
#define yyset_debug IW7set_debug
#endif

#ifdef yyget_extra
#define IW7get_extra_ALREADY_DEFINED
#else
#define yyget_extra IW7get_extra
#endif

#ifdef yyset_extra
#define IW7set_extra_ALREADY_DEFINED
#else
#define yyset_extra IW7set_extra
#endif

#ifdef yyget_in
#define IW7get_in_ALREADY_DEFINED
#else
#define yyget_in IW7get_in
#endif

#ifdef yyset_in
#define IW7set_in_ALREADY_DEFINED
#else
#define yyset_in IW7set_in
#endif

#ifdef yyget_out
#define IW7get_out_ALREADY_DEFINED
#else
#define yyget_out IW7get_out
#endif

#ifdef yyset_out
#define IW7set_out_ALREADY_DEFINED
#else
#define yyset_out IW7set_out
#endif

#ifdef yyget_leng
#define IW7get_leng_ALREADY_DEFINED
#else
#define yyget_leng IW7get_leng
#endif

#ifdef yyget_text
#define IW7get_text_ALREADY_DEFINED
#else
#define yyget_text IW7get_text
#endif

#ifdef yyget_lineno
#define IW7get_lineno_ALREADY_DEFINED
#else
#define yyget_lineno IW7get_lineno
#endif

#ifdef yyset_lineno
#define IW7set_lineno_ALREADY_DEFINED
#else
#define yyset_lineno IW7set_lineno
#endif

#ifdef yyget_column
#define IW7get_column_ALREADY_DEFINED
#else
#define yyget_column IW7get_column
#endif

#ifdef yyset_column
#define IW7set_column_ALREADY_DEFINED
#else
#define yyset_column IW7set_column
#endif

#ifdef yywrap
#define IW7wrap_ALREADY_DEFINED
#else
#define yywrap IW7wrap
#endif

#ifdef yyalloc
#define IW7alloc_ALREADY_DEFINED
#else
#define yyalloc IW7alloc
#endif

#ifdef yyrealloc
#define IW7realloc_ALREADY_DEFINED
#else
#define yyrealloc IW7realloc
#endif

#ifdef yyfree
#define IW7free_ALREADY_DEFINED
#else
#define yyfree IW7free
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin , yyscanner )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart ( FILE *input_file , yyscan_t yyscanner );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size , yyscan_t yyscanner );
void yy_delete_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yy_flush_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
void yypop_buffer_state ( yyscan_t yyscanner );

static void yyensure_buffer_stack ( yyscan_t yyscanner );
static void yy_load_buffer_state ( yyscan_t yyscanner );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file , yyscan_t yyscanner );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER , yyscanner)

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len , yyscan_t yyscanner );

void *yyalloc ( yy_size_t , yyscan_t yyscanner );
void *yyrealloc ( void *, yy_size_t , yyscan_t yyscanner );
void yyfree ( void * , yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define IW7wrap(yyscanner) (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state ( yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  , yyscan_t yyscanner);
static int yy_get_next_buffer ( yyscan_t yyscanner );
static void yynoreturn yy_fatal_error ( const char* msg , yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;
#define YY_NUM_RULES 97
#define YY_END_OF_BUFFER 98
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[269] =
    {   0,
        0,    0,    0,    0,    0,    0,   98,   96,    1,    2,
       84,   96,   96,   83,   87,   96,   44,   45,   81,   79,
       50,   80,   51,   82,   95,   53,   54,   68,   78,   69,
       55,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   48,   49,   88,
       46,   86,   47,   85,    5,    6,    5,    9,   10,    9,
       65,    0,   93,    0,    0,    0,    0,   74,   91,    0,
       63,    0,   76,    0,    0,   72,   56,   70,   57,   95,
       71,   94,    8,    4,    3,   73,   94,   95,    0,    0,
       52,   60,   66,   64,   67,   61,   90,   90,   90,   90,

       90,   90,   90,   90,   90,   90,   90,   90,   21,   26,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   43,   77,   75,   62,    7,   11,    0,   93,    0,
        0,    0,    0,   91,    0,   92,    0,    0,    0,    0,
       93,    0,   94,    3,   94,   94,   89,   58,   59,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   24,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,    0,    0,    0,    0,   92,    0,    0,   92,    0,
       41,   90,   34,   28,   90,   90,   22,   90,   90,   90,
       39,   90,   90,   90,   40,   38,   90,   90,   35,   90,

       17,   90,    0,    0,    0,   30,   90,   90,   15,   36,
       90,   42,   90,   90,   90,   90,   90,   90,   23,    0,
        0,    0,   90,   90,   90,   16,   32,   27,   33,   90,
       90,    0,    0,    0,   90,   29,   25,   90,   90,    0,
       12,    0,   31,   90,   18,   14,    0,   37,   90,   90,
        0,   90,   90,    0,   90,   90,    0,   90,   90,    0,
       90,   19,    0,   90,   13,   90,   20,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,   24,    1,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,   34,
       34,   40,   41,   42,   43,   44,   45,   34,   46,   47,
       48,   49,   50,   51,   52,    1,   53,   54,   55,   56,

       57,   58,   59,   60,   61,   34,   62,   63,   64,   65,
       66,   34,   34,   67,   68,   69,   70,   71,   72,   34,
       73,   74,   75,   76,   77,   78,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[79] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    4,    1,    5,    1,    1,
        1,    6,    1,    1,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    1,    8,    1,
        1,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[286] =
    {   0,
        0,    0,   76,   77,   78,   79,  369,  890,  890,  890,
      342,   78,   61,  341,   87,   81,  890,  890,  233,   78,
      890,   83,  236,   91,   94,  232,  890,   85,  180,   93,
      890,   87,   84,   96,  108,  104,  119,  131,  105,  117,
      144,  111,  149,  159,  175,  148,  180,  120,  890,  126,
      890,   65,  890,  890,  890,  890,  122,  890,  890,  121,
      890,  112,  890,  176,  138,  145,  146,  890,    0,  189,
      890,  162,  890,  187,  214,  890,  890,  890,  890,  173,
      890,  191,  890,  890,    0,  890,  200,  210,  183,    0,
      890,  107,  890,  890,  890,  106,    0,  185,  204,  212,

      207,  224,  230,  231,  229,  232,  237,  256,  235,  249,
      252,  261,  267,  251,  259,  279,  275,  268,  298,  292,
      306,  890,  890,  890,  890,  890,  890,  286,  297,  324,
      289,  304,  299,    0,  313,  890,  340,  288,  348,  325,
      335,  349,  890,    0,  338,  890,   69,  890,  890,  346,
      350,  351,  356,  362,  363,  377,  376,  378,  379,  392,
      394,  405,  375,  407,  415,  418,  424,  433,  440,  435,
      425,  255,  313,  364,  427,  430,  454,  443,  449,  477,
      333,  456,  453,  460,  463,  468,  470,  478,  479,  495,
      480,  486,  484,  485,  491,  492,  524,  506,  498,  531,

      508,  538,  495,  502,  499,  517,  545,  539,  541,  547,
      554,  548,  555,  567,  559,  550,  578,  585,  571,  531,
      556,   41,  592,  598,  599,  577,  600,  602,  606,  607,
      608,  595,  596,  605,  621,  614,  627,  639,  628,  604,
      890,  600,  645,  651,  660,  890,  640,  654,  659,  667,
      646,  670,  672,  642,  678,  690,  646,  683,  714,  673,
      707,  689,  677,  710,  890,  716,  713,  890,  775,  783,
      791,  794,  801,  806,  812,  820,  826,  833,  841,  849,
      857,  861,  866,  873,  881
    } ;

static const flex_int16_t yy_def[286] =
    {   0,
      268,    1,  269,  269,  270,  270,  268,  268,  268,  268,
      268,  271,  268,  272,  268,  273,  268,  268,  268,  268,
      268,  268,  268,  268,  274,  268,  268,  268,  268,  268,
      268,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  271,  268,  276,  268,  268,  268,  268,  277,  278,
      268,  279,  268,  273,  280,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  281,  268,  268,  274,  274,  282,
      268,  268,  268,  268,  268,  268,  283,  275,  275,  275,

      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  268,  268,  268,  268,  268,  268,  271,  271,  276,
      268,  268,  268,  277,  278,  268,  284,  279,  285,  273,
      273,  280,  268,  281,  268,  268,  282,  268,  268,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  268,  268,  268,  278,  278,  284,  279,  279,  285,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,

      275,  275,  268,  268,  268,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  268,
      268,  268,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  268,  268,  268,  275,  275,  275,  275,  275,  268,
      268,  268,  275,  275,  275,  268,  268,  275,  275,  275,
      268,  275,  275,  268,  275,  275,  268,  275,  275,  268,
      275,  275,  268,  275,  268,  275,  275,    0,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268
    } ;

static const flex_int16_t yy_nxt[969] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   34,   35,   36,   37,
       38,   39,   40,   39,   39,   41,   39,   42,   39,   43,
       44,   45,   46,   39,   47,   39,   39,   48,    8,   49,
       50,   39,   32,   33,   34,   35,   36,   37,   38,   39,
       40,   39,   41,   39,   42,   39,   43,   44,   45,   46,
       39,   47,   39,   39,   51,   52,   53,   54,   56,   56,
       59,   59,   63,   60,   60,   65,  124,   57,   57,   63,
       77,   70,  234,   66,   71,   72,   83,   79,   97,   78,

       80,   97,   84,   67,   81,   92,   93,   85,   73,   87,
       97,   88,   86,   65,   95,   96,   63,   90,   97,   97,
      101,   66,   97,  100,   99,   97,   64,  149,  148,   75,
       67,   97,   90,   97,  102,   90,  103,  127,  126,  104,
      125,  105,   90,  106,   90,   97,  109,  123,  101,  112,
      100,   99,   90,   90,  110,  108,   90,  107,   97,   90,
       64,  102,   97,   97,  103,   90,  104,   90,  105,  122,
      136,  106,  111,   97,  109,  131,  112,  113,   62,   90,
      129,  110,  132,  108,  107,  119,  133,  114,   87,   97,
       80,  115,   90,  136,   97,   63,   90,   90,  268,   97,

      111,   94,  131,  116,  120,  113,  117,   90,   82,  132,
      139,  121,  119,  133,  118,  114,   74,  145,   97,  115,
      143,   97,  141,   90,  130,   87,   97,   88,   90,  146,
      116,   90,  120,   90,  117,   75,  150,  137,   97,  121,
      151,  118,  152,   97,   97,   97,   97,  153,  143,   97,
       91,   97,   90,   82,   76,   90,  157,  146,   90,  155,
       90,  154,  142,   97,  150,   97,   97,  158,  151,  152,
       97,  156,   90,   97,  153,   97,  159,   90,   90,   90,
       90,   97,   97,   90,  157,   90,  164,  155,  154,   97,
       63,  203,  160,   97,  158,  161,  136,   90,  156,   90,

       90,   63,  162,  159,   90,  165,   97,   90,  163,   90,
      168,  166,   97,  164,  167,   90,   90,  136,  203,  160,
       97,  172,  161,   90,  170,  169,   62,   90,  129,  162,
      173,  174,  165,   63,   64,  163,  139,  168,  171,  166,
       90,  167,  135,   63,  176,   64,   90,   97,  204,  172,
      138,   74,  170,  169,   90,  145,  179,  141,  173,  174,
       97,  137,   68,   61,   97,   97,  171,  146,  268,  268,
       97,  268,  130,   75,  182,  204,   97,   97,  268,  268,
      268,   90,  181,   75,  184,  268,  183,  186,  177,   97,
       97,   97,   97,   97,   90,  146,  180,  142,   90,   90,

      268,  205,  182,  185,   90,  187,   97,  190,   97,  181,
       90,   90,  184,  183,  188,  186,  268,  194,  189,   97,
      191,   97,  192,   90,   90,   90,   90,   90,  205,   97,
      185,  136,   97,  187,  136,  190,  195,  193,   97,   97,
       90,  188,   90,  196,  194,  189,  268,   97,  191,   97,
      192,  136,  198,   90,   97,   90,  135,  136,  176,  197,
      202,  199,  268,   90,  195,  193,   90,   97,  200,  268,
       97,  196,   90,   90,   97,  137,  201,   97,  137,  138,
      198,   90,   97,   90,   97,  179,  197,  202,   90,  199,
      206,  139,   97,   97,   97,  207,  200,  139,   97,   97,

       97,   90,  177,  201,   90,   97,   97,  210,   90,   97,
      208,   90,   97,  213,  268,  209,   90,  206,   90,  211,
       97,  212,   97,  207,  214,  180,   90,   90,   90,  222,
      216,   97,   90,   90,   90,  210,  220,  208,   97,   90,
       90,  213,  209,   90,  221,   97,   90,  211,  212,  218,
      215,  214,   97,   97,   90,   97,   90,  222,  216,   97,
      217,   97,   97,  220,   97,   90,  219,  268,   97,   97,
      232,  221,   90,   97,  224,  268,  218,  229,  215,   90,
      225,   97,  223,  233,  268,   97,   90,   90,  217,   90,
      228,   97,   97,   90,  219,   90,   90,  232,   90,   97,

      226,  224,   90,   90,  227,  229,   97,   90,  225,  223,
      230,  233,   97,   97,   97,   90,   97,  231,  228,   90,
       97,   97,   97,  240,  241,   90,   90,  226,   97,  242,
      237,  227,  246,   90,  235,   97,  268,  247,  230,  236,
       90,   97,   97,  239,  238,  231,   90,   90,   90,  243,
       90,  240,  241,   97,   90,   90,   90,  242,  237,   97,
      246,  235,   90,  245,  247,   97,  236,  244,   97,   90,
      239,  238,  251,   97,   97,   90,   90,  243,  248,  268,
      268,   97,  254,  257,   97,  260,   97,   90,  268,  249,
      245,  253,   97,   90,  255,  244,  250,   97,  252,   90,

      251,  263,   90,   97,   97,  265,  248,   90,   90,  254,
      257,  261,  260,  256,  258,   90,  259,  249,   90,  253,
       90,   97,  255,  250,   97,  252,   90,   97,   97,  263,
       97,   90,  268,  265,  268,  264,  268,   90,   90,  261,
      256,  258,  268,  267,  259,  262,  268,  266,  268,  268,
      268,  268,  268,  268,  268,   90,  268,  268,   90,  268,
      268,   90,   90,  264,   90,  268,  268,  268,  268,  268,
      268,  267,  268,  262,  266,   55,   55,   55,   55,   55,
       55,   55,   55,   58,   58,   58,   58,   58,   58,   58,
       58,   62,   62,   62,   62,   62,   62,   62,   62,   69,

       69,   74,   74,   74,   74,   74,   74,   74,   74,   89,
       89,  268,   89,   89,   98,  268,   98,  268,   98,   98,
      128,  128,  128,  128,  128,  128,  128,  128,  134,  268,
      134,  268,  134,  135,  135,  135,  135,  135,  135,  135,
      135,  138,  138,  138,  138,  138,  138,  138,  138,  140,
      140,  140,  140,  140,  140,  140,  140,  144,  268,  144,
      144,  144,  144,  144,  144,  147,  268,  147,   97,  268,
       97,  268,   97,  175,  175,  175,  175,  175,  175,  175,
      175,  178,  178,  178,  178,  178,  178,  178,  178,    7,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,

      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268
    } ;

static const flex_int16_t yy_chk[969] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    4,
        5,    6,   12,    5,    6,   13,   52,    3,    4,   16,
       20,   15,  222,   13,   15,   15,   24,   22,   33,   20,

       22,   32,   24,   13,   22,   28,   28,   24,   15,   25,
       34,   25,   24,   13,   30,   30,   62,  147,   36,   39,
       34,   13,   35,   33,   32,   42,   12,   96,   92,   16,
       13,   40,   33,   37,   34,   32,   35,   60,   57,   36,
       52,   36,   25,   37,   34,   38,   40,   50,   34,   42,
       33,   32,   36,   39,   40,   38,   35,   37,   41,   42,
       62,   34,   46,   43,   35,   40,   36,   37,   36,   48,
       72,   37,   41,   44,   40,   65,   42,   43,   64,   38,
       64,   40,   66,   38,   37,   46,   67,   44,   80,   45,
       80,   44,   41,   70,   47,   74,   46,   43,   89,   98,

       41,   29,   65,   44,   47,   43,   45,   44,   82,   66,
       72,   47,   46,   67,   45,   44,   75,   87,   99,   44,
       82,  101,   75,   45,   64,   88,  100,   88,   47,   87,
       44,   89,   47,   98,   45,   74,   99,   70,  102,   47,
      100,   45,  101,  105,  103,  104,  106,  101,   82,  109,
       26,  107,   99,   23,   19,  101,  105,   87,   88,  103,
      100,  102,   75,  110,   99,  114,  111,  106,  100,  101,
      108,  104,  102,  115,  101,  112,  107,  105,  103,  104,
      106,  113,  118,  109,  105,  107,  114,  103,  102,  117,
      128,  172,  108,  116,  106,  111,  138,  110,  104,  114,

      111,  129,  112,  107,  108,  115,  120,  115,  113,  112,
      118,  116,  119,  114,  117,  113,  118,  135,  172,  108,
      121,  131,  111,  117,  120,  119,  130,  116,  130,  112,
      132,  133,  115,  140,  128,  113,  138,  118,  121,  116,
      120,  117,  137,  141,  137,  129,  119,  181,  173,  131,
      139,  142,  120,  119,  121,  145,  139,  142,  132,  133,
      150,  135,   14,   11,  151,  152,  121,  145,    7,    0,
      153,    0,  130,  140,  151,  173,  154,  155,    0,    0,
        0,  181,  150,  141,  153,    0,  152,  155,  137,  163,
      157,  156,  158,  159,  150,  145,  139,  142,  151,  152,

        0,  174,  151,  154,  153,  156,  160,  159,  161,  150,
      154,  155,  153,  152,  157,  155,    0,  163,  158,  162,
      160,  164,  161,  163,  157,  156,  158,  159,  174,  165,
      154,  175,  166,  156,  176,  159,  164,  162,  167,  171,
      160,  157,  161,  165,  163,  158,    0,  168,  160,  170,
      161,  178,  167,  162,  169,  164,  177,  179,  177,  166,
      171,  168,    0,  165,  164,  162,  166,  183,  169,    0,
      182,  165,  167,  171,  184,  175,  170,  185,  176,  180,
      167,  168,  186,  170,  187,  180,  166,  171,  169,  168,
      182,  178,  188,  189,  191,  185,  169,  179,  193,  194,

      192,  183,  177,  170,  182,  195,  196,  189,  184,  190,
      186,  185,  199,  193,    0,  188,  186,  182,  187,  190,
      198,  192,  201,  185,  194,  180,  188,  189,  191,  205,
      198,  206,  193,  194,  192,  189,  203,  186,  197,  195,
      196,  193,  188,  190,  204,  200,  199,  190,  192,  201,
      197,  194,  202,  208,  198,  209,  201,  205,  198,  207,
      200,  210,  212,  203,  216,  206,  202,    0,  211,  213,
      220,  204,  197,  215,  208,    0,  201,  216,  197,  200,
      211,  214,  207,  221,    0,  219,  202,  208,  200,  209,
      215,  226,  217,  207,  202,  210,  212,  220,  216,  218,

      213,  208,  211,  213,  214,  216,  223,  215,  211,  207,
      217,  221,  224,  225,  227,  214,  228,  218,  215,  219,
      229,  230,  231,  232,  233,  226,  217,  213,  236,  234,
      225,  214,  240,  218,  223,  235,    0,  242,  217,  224,
      223,  237,  239,  231,  230,  218,  224,  225,  227,  235,
      228,  232,  233,  238,  229,  230,  231,  234,  225,  243,
      240,  223,  236,  239,  242,  244,  224,  238,  248,  235,
      231,  230,  247,  249,  245,  237,  239,  235,  244,    0,
        0,  250,  251,  254,  252,  257,  253,  238,    0,  245,
      239,  250,  255,  243,  252,  238,  245,  258,  249,  244,

      247,  260,  248,  262,  256,  263,  244,  249,  245,  251,
      254,  258,  257,  253,  255,  250,  256,  245,  252,  250,
      253,  261,  252,  245,  264,  249,  255,  267,  259,  260,
      266,  258,    0,  263,    0,  261,    0,  262,  256,  258,
      253,  255,    0,  266,  256,  259,    0,  264,    0,    0,
        0,    0,    0,    0,    0,  261,    0,    0,  264,    0,
        0,  267,  259,  261,  266,    0,    0,    0,    0,    0,
        0,  266,    0,  259,  264,  269,  269,  269,  269,  269,
      269,  269,  269,  270,  270,  270,  270,  270,  270,  270,
      270,  271,  271,  271,  271,  271,  271,  271,  271,  272,

      272,  273,  273,  273,  273,  273,  273,  273,  273,  274,
      274,    0,  274,  274,  275,    0,  275,    0,  275,  275,
      276,  276,  276,  276,  276,  276,  276,  276,  277,    0,
      277,    0,  277,  278,  278,  278,  278,  278,  278,  278,
      278,  279,  279,  279,  279,  279,  279,  279,  279,  280,
      280,  280,  280,  280,  280,  280,  280,  281,    0,  281,
      281,  281,  281,  281,  281,  282,    0,  282,  283,    0,
      283,    0,  283,  284,  284,  284,  284,  284,  284,  284,
      284,  285,  285,  285,  285,  285,  285,  285,  285,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,

      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "IW7.lexer.lpp"
/* Copyright 2021 xensik. All rights reserved.
//
// Use of this source code is governed by a GNU GPLv3 license
// that can be found in the LICENSE file.
*/
#define YY_NO_INPUT 1
#define YY_NO_UNISTD_H 1



#line 951 "./IW7/compiler_lexer.cpp"

#define INITIAL 0
#define COMMENT_BLOCK_STATE 1
#define DEVELOPER_BLOCK_STATE 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    }; /* end struct yyguts_t */

static int yy_init_globals ( yyscan_t yyscanner );

int yylex_init (yyscan_t* scanner);

int yylex_init_extra ( YY_EXTRA_TYPE user_defined, yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( yyscan_t yyscanner );

int yyget_debug ( yyscan_t yyscanner );

void yyset_debug ( int debug_flag , yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra ( yyscan_t yyscanner );

void yyset_extra ( YY_EXTRA_TYPE user_defined , yyscan_t yyscanner );

FILE *yyget_in ( yyscan_t yyscanner );

void yyset_in  ( FILE * _in_str , yyscan_t yyscanner );

FILE *yyget_out ( yyscan_t yyscanner );

void yyset_out  ( FILE * _out_str , yyscan_t yyscanner );

			int yyget_leng ( yyscan_t yyscanner );

char *yyget_text ( yyscan_t yyscanner );

int yyget_lineno ( yyscan_t yyscanner );

void yyset_lineno ( int _line_number , yyscan_t yyscanner );

int yyget_column  ( yyscan_t yyscanner );

void yyset_column ( int _column_no , yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( yyscan_t yyscanner );
#else
extern int yywrap ( yyscan_t yyscanner );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int , yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * , yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( yyscan_t yyscanner );
#else
static int input ( yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (yyscan_t yyscanner);

#define YY_DECL int yylex (yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
		}

		yy_load_buffer_state( yyscanner );
		}

	{
#line 35 "IW7.lexer.lpp"


#line 1214 "./IW7/compiler_lexer.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 269 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 268 );
		yy_cp = yyg->yy_last_accepting_cpos;
		yy_current_state = yyg->yy_last_accepting_state;

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 37 "IW7.lexer.lpp"

	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 38 "IW7.lexer.lpp"
{ (*location)++; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 39 "IW7.lexer.lpp"

	YY_BREAK
case 4:
YY_RULE_SETUP
#line 41 "IW7.lexer.lpp"
{ BEGIN(COMMENT_BLOCK_STATE); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 42 "IW7.lexer.lpp"

	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 43 "IW7.lexer.lpp"
{ (*location)++; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 44 "IW7.lexer.lpp"
{ BEGIN(INITIAL); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 46 "IW7.lexer.lpp"
{ BEGIN(DEVELOPER_BLOCK_STATE); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 47 "IW7.lexer.lpp"

	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 48 "IW7.lexer.lpp"
{ (*location)++; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 49 "IW7.lexer.lpp"
{ BEGIN(INITIAL); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 51 "IW7.lexer.lpp"
{ return IW7::parser::make_INCLUDE(); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 52 "IW7.lexer.lpp"
{ return IW7::parser::make_USING_ANIMTREE(); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 53 "IW7.lexer.lpp"
{ return IW7::parser::make_ANIMTREE(); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 54 "IW7.lexer.lpp"
{ return IW7::parser::make_ENDON(); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 55 "IW7.lexer.lpp"
{ return IW7::parser::make_NOTIFY(); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 56 "IW7.lexer.lpp"
{ return IW7::parser::make_WAIT(); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 57 "IW7.lexer.lpp"
{ return IW7::parser::make_WAITTILL(); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 58 "IW7.lexer.lpp"
{ return IW7::parser::make_WAITTILLMATCH(); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 59 "IW7.lexer.lpp"
{ return IW7::parser::make_WAITTILLFRAMEEND(); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 60 "IW7.lexer.lpp"
{ return IW7::parser::make_IF(); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 61 "IW7.lexer.lpp"
{ return IW7::parser::make_ELSE(); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 62 "IW7.lexer.lpp"
{ return IW7::parser::make_WHILE(); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 63 "IW7.lexer.lpp"
{ return IW7::parser::make_FOR(); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 64 "IW7.lexer.lpp"
{ return IW7::parser::make_FOREACH(); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 65 "IW7.lexer.lpp"
{ return IW7::parser::make_IN(); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 66 "IW7.lexer.lpp"
{ return IW7::parser::make_SWITCH(); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 67 "IW7.lexer.lpp"
{ return IW7::parser::make_CASE(); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 68 "IW7.lexer.lpp"
{ return IW7::parser::make_DEFAULT(); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 69 "IW7.lexer.lpp"
{ return IW7::parser::make_BREAK(); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 70 "IW7.lexer.lpp"
{ return IW7::parser::make_CONTINUE(); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 71 "IW7.lexer.lpp"
{ return IW7::parser::make_RETURN(); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 72 "IW7.lexer.lpp"
{ return IW7::parser::make_THREAD(); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 73 "IW7.lexer.lpp"
{ return IW7::parser::make_CALL(); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 74 "IW7.lexer.lpp"
{ return IW7::parser::make_TRUE(); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 75 "IW7.lexer.lpp"
{ return IW7::parser::make_FALSE(); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 76 "IW7.lexer.lpp"
{ return IW7::parser::make_UNDEFINED(); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 77 "IW7.lexer.lpp"
{ return IW7::parser::make_SIZE(); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 78 "IW7.lexer.lpp"
{ return IW7::parser::make_GAME(); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 79 "IW7.lexer.lpp"
{ return IW7::parser::make_SELF(); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 80 "IW7.lexer.lpp"
{ return IW7::parser::make_ANIM(); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 81 "IW7.lexer.lpp"
{ return IW7::parser::make_LEVEL(); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 82 "IW7.lexer.lpp"
{ return IW7::parser::make_EMPTY_ARRAY(); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 83 "IW7.lexer.lpp"
{ return IW7::parser::make_LPAREN(); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 84 "IW7.lexer.lpp"
{ return IW7::parser::make_RPAREN(); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 85 "IW7.lexer.lpp"
{ return IW7::parser::make_LBRACE(); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 86 "IW7.lexer.lpp"
{ return IW7::parser::make_RBRACE(); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 87 "IW7.lexer.lpp"
{ return IW7::parser::make_LBRACKET(); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 88 "IW7.lexer.lpp"
{ return IW7::parser::make_RBRACKET(); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 89 "IW7.lexer.lpp"
{ return IW7::parser::make_COMMA(); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 90 "IW7.lexer.lpp"
{ return IW7::parser::make_DOT(); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 91 "IW7.lexer.lpp"
{ return IW7::parser::make_DOUBLECOLON(); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 92 "IW7.lexer.lpp"
{ return IW7::parser::make_COLON(); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 93 "IW7.lexer.lpp"
{ return IW7::parser::make_SEMICOLON(); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 94 "IW7.lexer.lpp"
{ return IW7::parser::make_QMARK(); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 95 "IW7.lexer.lpp"
{ return IW7::parser::make_INCREMENT(); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 96 "IW7.lexer.lpp"
{ return IW7::parser::make_DECREMENT(); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 97 "IW7.lexer.lpp"
{ return IW7::parser::make_ASSIGN_LSHIFT(); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 98 "IW7.lexer.lpp"
{ return IW7::parser::make_ASSIGN_RSHIFT(); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 99 "IW7.lexer.lpp"
{ return IW7::parser::make_LSHIFT(); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 100 "IW7.lexer.lpp"
{ return IW7::parser::make_RSHIFT(); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 101 "IW7.lexer.lpp"
{ return IW7::parser::make_OR(); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 102 "IW7.lexer.lpp"
{ return IW7::parser::make_AND(); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 103 "IW7.lexer.lpp"
{ return IW7::parser::make_EQUALITY(); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 104 "IW7.lexer.lpp"
{ return IW7::parser::make_INEQUALITY(); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 105 "IW7.lexer.lpp"
{ return IW7::parser::make_LESS_EQUAL(); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 106 "IW7.lexer.lpp"
{ return IW7::parser::make_GREATER_EQUAL(); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 107 "IW7.lexer.lpp"
{ return IW7::parser::make_LESS(); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 108 "IW7.lexer.lpp"
{ return IW7::parser::make_GREATER(); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 109 "IW7.lexer.lpp"
{ return IW7::parser::make_ASSIGN_ADD(); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 110 "IW7.lexer.lpp"
{ return IW7::parser::make_ASSIGN_SUB(); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 111 "IW7.lexer.lpp"
{ return IW7::parser::make_ASSIGN_MULT(); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 112 "IW7.lexer.lpp"
{ return IW7::parser::make_ASSIGN_DIV(); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 113 "IW7.lexer.lpp"
{ return IW7::parser::make_ASSIGN_MOD(); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 114 "IW7.lexer.lpp"
{ return IW7::parser::make_ASSIGN_BITWISE_OR(); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 115 "IW7.lexer.lpp"
{ return IW7::parser::make_ASSIGN_BITWISE_AND(); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 116 "IW7.lexer.lpp"
{ return IW7::parser::make_ASSIGN_BITWISE_EXOR(); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 117 "IW7.lexer.lpp"
{ return IW7::parser::make_ASSIGN(); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 118 "IW7.lexer.lpp"
{ return IW7::parser::make_ADD(); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 119 "IW7.lexer.lpp"
{ return IW7::parser::make_SUB(); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 120 "IW7.lexer.lpp"
{ return IW7::parser::make_MULT(); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 121 "IW7.lexer.lpp"
{ return IW7::parser::make_DIV(); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 122 "IW7.lexer.lpp"
{ return IW7::parser::make_MOD(); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 123 "IW7.lexer.lpp"
{ return IW7::parser::make_NOT(); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 124 "IW7.lexer.lpp"
{ return IW7::parser::make_COMPLEMENT(); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 125 "IW7.lexer.lpp"
{ return IW7::parser::make_BITWISE_OR(); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 126 "IW7.lexer.lpp"
{ return IW7::parser::make_BITWISE_AND(); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 127 "IW7.lexer.lpp"
{ return IW7::parser::make_BITWISE_EXOR(); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 129 "IW7.lexer.lpp"
{ return IW7::parser::make_FILEPATH(std::string(yytext)); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 130 "IW7.lexer.lpp"
{ return IW7::parser::make_IDENTIFIER(utils::string::to_lower(yytext)); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 131 "IW7.lexer.lpp"
{ return IW7::parser::make_ANIMREF(utils::string::to_lower(yytext)); }
	YY_BREAK
case 92:
/* rule 92 can match eol */
YY_RULE_SETUP
#line 132 "IW7.lexer.lpp"
{ return IW7::parser::make_STRING_LOC(std::string(yytext)); }
	YY_BREAK
case 93:
/* rule 93 can match eol */
YY_RULE_SETUP
#line 133 "IW7.lexer.lpp"
{ return IW7::parser::make_STRING(std::string(yytext)); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 134 "IW7.lexer.lpp"
{ return IW7::parser::make_FLOAT(std::string(yytext)); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 135 "IW7.lexer.lpp"
{ return IW7::parser::make_INTEGER(std::string(yytext)); }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT_BLOCK_STATE):
case YY_STATE_EOF(DEVELOPER_BLOCK_STATE):
#line 137 "IW7.lexer.lpp"
{ return IW7::parser::make_IW7EOF(); }
	YY_BREAK
case 96:
/* rule 96 can match eol */
YY_RULE_SETUP
#line 138 "IW7.lexer.lpp"
{ throw IW7::parser::syntax_error("invalid character: " + std::string(yytext)); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 139 "IW7.lexer.lpp"
ECHO;
	YY_BREAK
#line 1764 "./IW7/compiler_lexer.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_last_accepting_cpos;
				yy_current_state = yyg->yy_last_accepting_state;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap( yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  , yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size , yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 269 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	char *yy_cp = yyg->yy_c_buf_p;

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 269 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 268);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr);
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin , yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file , yyscanner);
	yy_load_buffer_state( yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file , yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf , yyscanner );

	yyfree( (void *) b , yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer( b , yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER , yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b , yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) , yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n , yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n , yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param _line_number line number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  _line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_lineno called with no buffer" );
    
    yylineno = _line_number;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_column called with no buffer" );
    
    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

void yyset_out (FILE *  _out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = _out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  _bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = _bdebug ;
}

/* Accessor methods for yylval and yylloc */

/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */
int yylex_init(yyscan_t* ptr_yy_globals)
{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */
int yylex_init_extra( YY_EXTRA_TYPE yy_user_defined, yyscan_t* ptr_yy_globals )
{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    yyset_extra (yy_user_defined, *ptr_yy_globals);

    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = NULL;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = NULL;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER , yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack , yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree( yyg->yy_start_stack , yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 139 "IW7.lexer.lpp"


